const {Button,Card,Badge,Stat,SearchBar,Tag,Icon,Table,Breadcrumb,Accordion,VoteCard,Tabs}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
function Accueil({go,falc,user}){
  const [q,setQ]=React.useState('');
  const top=['papiers','sante','impots','famille','education','travail'].map(id=>BESOINS.find(b=>b.id===id));
  return <>
    <section style={{background:'var(--cm-ebene)',color:'#fff',position:'relative',isolation:'isolate'}}>
      <div aria-hidden="true" style={{position:'absolute',inset:0,background:'var(--motif-ndop)',opacity:.35,overflow:'hidden',zIndex:-1}}/>
      <Container style={{position:'relative',padding:'var(--space-16) var(--gutter) var(--space-12)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'end'}}>
        <div>
          <Overline color="var(--cm-jaune-500)">{tr('République du Cameroun','Republic of Cameroon')} · Cameroun numérique</Overline>
          <div aria-hidden="true" style={{width:48,height:1,background:OR,margin:'14px 0 0'}}/>
          <h1 style={{font:'var(--type-display)',color:'#fff',fontSize:'clamp(2.25rem,5vw,3.75rem)',marginTop:14,letterSpacing:'var(--tracking-tight)'}}>{falc?tr('Tous les services de l’État, au même endroit.','All State services, in one place.'):tr('Un État, un langage, un compte.','One State, one language, one account.')}</h1>
          <p style={{font:'var(--type-lead)',color:'var(--cm-gris-200)',maxWidth:'52ch',marginTop:14}}>{falc?tr('Vous cherchez une démarche ? Tapez un mot. Vous voulez vos papiers ? Connectez-vous une seule fois.','Looking for a service? Type a word. Need your papers? Sign in once.'):tr('Trouvez une démarche par besoin, pas par organigramme. Connectez-vous une fois avec Identité Cameroun ; vos documents, vos échéances et vos préférences vous suivent sur tous les sites de l’État.','Find a service by need, not by org chart. Sign in once with Identité Cameroun; your documents, deadlines and preferences follow you across every State site.')}</p>
          <RechercheGlobale onSubmit={q=>go('recherche',q)} style={{marginTop:28,maxWidth:680}} exemples={['Acte de naissance','Renouveler sa CNI','Obtenir son NIU','e-Visa','Résultats d’examen','Péage']}/>
        </div>
        <div style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.2)',borderTop:'2px solid '+OR,padding:'var(--space-6)',display:'grid',gap:12}}>
          <Overline color="var(--cm-jaune-500)">Identité Cameroun</Overline>
          {user?<><div style={{display:'flex',gap:12,alignItems:'center'}}><span style={{width:44,height:44,background:'var(--cm-vert-500)',color:'var(--cm-ebene)',display:'grid',placeItems:'center',fontFamily:'var(--font-display)',fontWeight:800}}>{user.initials}</span><div><div style={{font:'var(--type-h6)',color:'#fff'}}>{user.nom}</div><div style={{font:'var(--type-caption)',color:'var(--cm-gris-300)'}}>{user.type==='pro'?'Compte professionnel':'Compte citoyen'} · {user.type==='pro'?PRO.niu:CITOYEN.id}</div></div></div><Button variant="inverse" iconRight="arrow-right" onClick={()=>go(user.type==='pro'?'pro':'citoyen')}>Ouvrir mon tableau de bord</Button></>
          :<><p style={{font:'var(--type-body-sm)',color:'var(--cm-gris-200)'}}>Une identité numérique, deux contextes : <b style={{color:'#fff'}}>citoyen</b> pour vos papiers, votre santé, votre famille ; <b style={{color:'#fff'}}>professionnel</b> pour votre entreprise.</p><div style={{display:'grid',gap:8}}><Button variant="inverse" iconLeft="fingerprint" onClick={()=>go('connexion')}>Se connecter</Button><Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('identite')} style={{color:'#fff'}}>Découvrir Identité Cameroun</Button></div></>}
        </div>
      </Container>
    </section>
    <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',borderTop:'2px solid '+OR}}><Container style={{padding:'var(--space-8) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-6)'}}>
      <Stat size="sm" value={INSTITUTIONS.length} label={tr('institutions','institutions')} detail={tr('présidence, ministères, délégations','presidency, ministries, delegations')} accent="vert"/><Stat size="sm" value={INSTITUTIONS.length} label={tr('sites au nouveau langage','sites on the new language')} detail={INSTITUTIONS.filter(i=>i.statut==='livré').length+tr(' sites dédiés · ',' dedicated sites · ')+INSTITUTIONS.filter(i=>i.statut!=='livré').length+tr(' gabarit commun',' common template')} accent="kola"/><Stat size="sm" value={BESOINS.reduce((s,b)=>s+b.demarches.length,0)} label={tr('démarches référencées','referenced services')} detail={tr('coût et délai affichés','fee and lead time shown')} accent="laterite"/><Stat size="sm" value="1" label={tr('compte unique','single account')} detail="Identité Cameroun" accent="indigo"/><Stat size="sm" value="AA" label={tr('accessibilité visée','target accessibility')} detail="RGAA 4 / WCAG 2.2" accent="neutre"/>
    </Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)'}}>
      <SectionTitle overline="Démarches" num={1} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('besoins')}>Les {BESOINS.length} besoins</Button>}>Par besoin, puis par ministère</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'var(--space-4)'}}>{top.map(b=><button key={b.id} type="button" onClick={()=>go('besoin',b.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'40px 1fr',gap:14,padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',textAlign:'left',alignItems:'start',minHeight:132}}><span style={{width:40,height:40,background:'var(--surface-brand-soft)',display:'grid',placeItems:'center'}}><Icon name={b.icon} size={20} color="var(--cm-vert-800)"/></span><span><span style={{font:'var(--type-h5)',color:'var(--text-heading)',display:'block'}}>{b.nom}</span><span style={{font:'var(--type-body-sm)',color:'var(--text-muted)',display:'block',marginTop:4}}>{b.d}</span><span style={{font:'var(--type-caption)',color:'var(--cm-vert-800)',fontWeight:600,display:'inline-flex',alignItems:'center',gap:6,marginTop:10}}>{b.demarches.length} démarches · {b.min.length} ministère{b.min.length>1?'s':''} <Icon name="arrow-right" size={14}/></span></span></button>)}</div>
    </Container></section>
    <section style={{background:'var(--surface-card)',borderTop:'var(--hairline)',borderBottom:'var(--hairline)'}}><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'start'}}>
      <div><SectionTitle overline="Le réseau" num={2} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('annuaire')}>Annuaire complet</Button>}>Les sites de l’État, un même langage</SectionTitle>
        <div style={{display:'grid',gap:2}}>{INSTITUTIONS.filter(i=>i.statut!=='à venir').sort((a,b)=>b.poids-a.poids).slice(0,9).map(i=><Row key={i.id} title={i.nom} meta={i.sigle+' · '+i.site} right={<Badge status={STATUT[i.statut]} size="sm">{i.statut}</Badge>} onClick={()=>i.lien?location.href=i.lien:go('institution',i.id)}/>)}</div></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}>
        <div style={{border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)',padding:'var(--space-5)',background:'var(--surface-page)'}}><Overline>Ce qui ne change jamais</Overline><ul style={{margin:'10px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)'}}><li>La barre gouvernementale et le bouton Identité Cameroun, en haut.</li><li>La recherche, qui cherche sur tous les sites.</li><li>Le panneau d’accessibilité et vos réglages.</li><li>Le pied de page avec l’annuaire.</li><li>Le coût et le délai d’une démarche, en première ligne.</li></ul></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Sites déjà en ligne</Overline><div style={{display:'grid',gap:8,marginTop:10}}><Button size="sm" variant="secondary" iconRight="arrow-up-right" href={LINKS.musee}>Musée numérique du Cameroun</Button><Button size="sm" variant="secondary" iconRight="arrow-up-right" href={LINKS.impots}>Impôts — DGI</Button><Button size="sm" variant="secondary" iconRight="arrow-up-right" href={LINKS.tourisme}>Visiter le Cameroun</Button></div></div>
      </aside>
    </Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)'}}>
      <SectionTitle overline="Communauté" num={3} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('communaute')}>Tous les votes</Button>}>Le langage évolue avec vous</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'var(--space-4)'}}>{VOTES.slice(0,3).map((v,i)=><VoteCard key={i} {...v}/>)}</div>
    </Container></section>
  </>;
}
function Besoins({go,query}){
  const [q,setQ]=React.useState(query||'');
  const list=BESOINS.map(b=>({...b,hits:b.demarches.filter(d=>!q||(d.t+' '+d.svc+' '+b.nom+' '+b.d).toLowerCase().includes(q.toLowerCase()))})).filter(b=>!q||b.hits.length||b.nom.toLowerCase().includes(q.toLowerCase()));
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Démarches" num={1}>Par besoin, puis par ministère</SectionTitle>
    <SearchBar value={q} onChange={setQ} onSubmit={()=>{}} placeholder="Rechercher une démarche" label="Rechercher une démarche" style={{maxWidth:560}}/>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:12}} aria-live="polite">{list.length} besoin{list.length>1?'s':''} · {list.reduce((s,b)=>s+(q?b.hits.length:b.demarches.length),0)} démarches</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(320px,1fr))',gap:'var(--space-4)',marginTop:'var(--space-6)'}}>{list.map(b=><article key={b.id} style={{background:'var(--surface-card)',border:'var(--hairline)',display:'grid',gridTemplateRows:'auto 1fr auto'}}><button type="button" onClick={()=>go('besoin',b.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'36px 1fr',gap:12,padding:'var(--space-4) var(--space-5)',borderBottom:'var(--hairline)',alignItems:'center'}}><span style={{width:36,height:36,background:'var(--surface-brand-soft)',display:'grid',placeItems:'center'}}><Icon name={b.icon} size={18} color="var(--cm-vert-800)"/></span><span><span style={{font:'var(--type-h6)',display:'block'}}>{b.nom}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{b.en}</span></span></button><ul style={{margin:0,padding:'8px 0',listStyle:'none'}}>{(q?b.hits:b.demarches).map(d=><li key={d.t}><button type="button" onClick={()=>go('besoin',b.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'1fr auto 16px',gap:8,width:'100%',padding:'8px var(--space-5)',font:'var(--type-body-sm)',color:'var(--text-body)',alignItems:'center'}}>{d.t}<span style={{font:'var(--type-caption)',fontFamily:'var(--font-mono)',color:'var(--text-muted)'}}>{(instOf(d.min)||{}).sigle}</span><Icon name="chevron-right" size={14} color="var(--text-subtle)"/></button></li>)}</ul><div style={{padding:'10px var(--space-5)',borderTop:'var(--hairline)',display:'flex',gap:6,flexWrap:'wrap'}}>{b.min.map(id=>{const i=instOf(id);return i?<Tag key={id} size="sm" onClick={()=>go('institution',id)}>{i.sigle}</Tag>:null;})}</div></article>)}</div>
  </Container>;
}
function Besoin({go,id,user}){
  const b=BESOINS.find(x=>x.id===id)||BESOINS[0];
  return <Container style={{padding:'var(--space-8) var(--gutter) var(--space-16)'}}>
    <Breadcrumb items={[{label:'Accueil',href:'#'},{label:'Démarches par besoin',href:'#'},{label:b.nom}]}/>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-12)',marginTop:'var(--space-8)',alignItems:'start'}}>
      <div><Overline>{b.en}</Overline><h1 style={{font:'var(--type-h1)',marginTop:8,letterSpacing:'var(--tracking-tight)'}}>{b.nom}</h1><p style={{font:'var(--type-lead)',color:'var(--text-muted)',marginTop:10,maxWidth:'var(--measure)'}}>{b.d}</p>
        <h2 style={{font:'var(--type-h4)',marginTop:'var(--space-10)'}}>Démarches</h2><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:4}}>Coût et délai réglementaires, service en ligne existant. Connecté·e, les formulaires sont pré-remplis avec votre identité.</p>
        <div style={{display:'grid',gap:2,marginTop:12}}>{b.demarches.map(d=>{const i=instOf(d.min)||{};return <div key={d.t} style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'center',padding:'12px 14px'}}><div style={{minWidth:0}}><div style={{font:'var(--type-label)',fontWeight:600,color:'var(--text-heading)'}}>{d.t}</div><div style={{display:'flex',gap:14,flexWrap:'wrap',marginTop:6,font:'var(--type-caption)',color:'var(--text-muted)'}}><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name="coins" size={12}/>{d.cout}</span><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name="clock" size={12}/>{d.delai}</span><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name="landmark" size={12}/>{i.sigle} · {d.svc}</span><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name={RELAIS_DEF[d.relais].icon} size={12}/>{RELAIS_DEF[d.relais].nom}</span></div></div><Button size="sm" variant={user?'primary':'secondary'} iconRight="arrow-right" onClick={()=>go(user?'citoyen':'connexion')}>{user?'Commencer':'Se connecter'}</Button></div>;})}</div>
        <div style={{marginTop:'var(--space-6)',padding:'var(--space-4) var(--space-5)',background:'var(--surface-brand-soft)',border:'1px solid var(--cm-vert-200)',font:'var(--type-body-sm)',display:'grid',gridTemplateColumns:'20px 1fr',gap:12}}><Icon name="info" size={18} color="var(--cm-vert-800)"/><span>Le coût et le délai indiqués sont ceux fixés par les textes en vigueur. Aucun paiement n’est demandé en dehors du portail ; toute sollicitation contraire peut être signalée.</span></div></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)" style={{marginBottom:8}}>Ministères concernés</Overline><div style={{display:'grid',gap:2}}>{b.min.map(id=>{const i=instOf(id);return i?<Row key={id} title={i.sigle} meta={i.nom} right={<Badge status={STATUT[i.statut]} size="sm">{i.statut}</Badge>} onClick={()=>i.lien?location.href=i.lien:go('institution',id)} style={{padding:'8px 0'}}/>:null;})}</div></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)" style={{marginBottom:8}}>Où se rendre</Overline><div style={{display:'grid',gap:2}}>{[...new Set(b.demarches.map(d=>d.relais))].map(r=><Row key={r} icon={RELAIS_DEF[r].icon} title={RELAIS_DEF[r].nom} meta={RELAIS_DEF[r].ou} onClick={()=>go('relais',r)} style={{padding:'8px 0'}}/>)}</div></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Besoin d’aide ?</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Centre d’appel <b style={{fontFamily:'var(--font-mono)'}}>8100</b> (gratuit, 7 j/7, FR/EN), guichets Cameroun numérique dans chaque chef-lieu, version facile à lire dans le panneau d’accessibilité.</p></div></aside>
    </div>
  </Container>;
}
function Annuaire({go}){
  const [cat,setCat]=React.useState('Toutes');const [st,setSt]=React.useState('Tous');
  const list=INSTITUTIONS.filter(i=>(cat==='Toutes'||i.cat===cat)&&(st==='Tous'||i.statut===st));
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Institutions" num={2}>Ministères, délégations et sites</SectionTitle>
    <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>Chaque institution est décrite par son rôle dans la vie intérieure du pays et dans ses relations extérieures. Le poids (1 à 5) reflète l’importance des services rendus au citoyen et le rayonnement international. Liste à valider sur le décret d’organisation du gouvernement en vigueur.</p>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:'var(--space-6)'}}><Tag selected={cat==='Toutes'} onClick={()=>setCat('Toutes')}>Toutes</Tag>{CAT_INST.map(c=><Tag key={c} selected={cat===c} onClick={()=>setCat(c)}>{c}<span style={{color:'var(--text-subtle)',marginLeft:6}}>{INSTITUTIONS.filter(i=>i.cat===c).length}</span></Tag>)}</div>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{['Tous','livré','gabarit commun'].map(s=><Tag key={s} size="sm" selected={st===s} onClick={()=>setSt(s)}>{s==='Tous'?'Tous les statuts':s}</Tag>)}</div>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:14}} aria-live="polite">{list.length} institution{list.length>1?'s':''}</p>
    <div style={{marginTop:'var(--space-4)'}}><Table caption="Institutions de l’État, rôle intérieur et extérieur, statut de bascule vers le nouveau langage" columns={[{key:'sigle',label:'Sigle',mono:true},{key:'nom',label:'Institution',strong:true},{key:'int',label:'Vie intérieure'},{key:'ext',label:'Relations extérieures'},{key:'poids',label:'Poids',align:'right',render:v=><span aria-label={v+' sur 5'} style={{display:'inline-flex',gap:2}}>{[1,2,3,4,5].map(n=><Star key={n} size={10} color={n<=v?OR:'var(--cm-gris-200)'}/>)}</span>},{key:'statut',label:'Statut',render:v=><Badge status={STATUT[v]} size="sm">{v}</Badge>},{key:'x',label:'',align:'right',render:(_,row)=><Button size="sm" variant="tertiary" iconRight={row.lien?'arrow-up-right':'chevron-right'} onClick={()=>location.href=(MINISTERES.find(m=>m.id===row.id)||{}).href||('../ministeres/index.html#'+row.id)}>{tr('Ouvrir le site','Open site')}</Button>}]} rows={list}/></div>
  </Container>;
}
function Institution({go,id}){
  const i=instOf(id)||INSTITUTIONS[0];const besoins=BESOINS.filter(b=>b.min.includes(i.id));
  return <Container style={{padding:'var(--space-8) var(--gutter) var(--space-16)'}}>
    <Breadcrumb items={[{label:'Accueil',href:'#'},{label:'Ministères & sites',href:'#'},{label:i.sigle}]}/>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-12)',marginTop:'var(--space-8)',alignItems:'start'}}>
      <div><Overline>{i.cat}</Overline><h1 style={{font:'var(--type-h1)',marginTop:8,letterSpacing:'var(--tracking-tight)'}}>{i.nom}</h1><div style={{display:'flex',gap:12,alignItems:'center',marginTop:10,flexWrap:'wrap'}}><span style={{fontFamily:'var(--font-mono)',color:'var(--text-muted)'}}>{i.sigle} · {i.site}</span><Badge status={STATUT[i.statut]}>{i.statut}</Badge><span aria-label={'Poids '+i.poids+' sur 5'} style={{display:'inline-flex',gap:2}}>{[1,2,3,4,5].map(n=><Star key={n} size={12} color={n<=i.poids?OR:'var(--cm-gris-200)'}/>)}</span></div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)',marginTop:'var(--space-8)'}}><div style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)'}}><Overline>Vie intérieure</Overline><p style={{marginTop:8}}>{i.int}</p></div><div style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-indigo-600)'}}><Overline color="var(--cm-indigo-700)">Relations extérieures</Overline><p style={{marginTop:8}}>{i.ext}</p></div></div>
        {besoins.length>0&&<><h2 style={{font:'var(--type-h4)',marginTop:'var(--space-10)'}}>Services proposés</h2><div style={{display:'grid',gap:2,marginTop:12}}>{besoins.flatMap(b=>b.demarches.filter(d=>d.min===i.id).map(d=><Row key={d.t} icon={b.icon} title={d.t} meta={d.svc+' · '+d.cout+' · '+d.delai} right={b.nom} onClick={()=>go('besoin',b.id)} style={{background:'var(--surface-card)'}}/>))}</div></>}
        
      </div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Gabarit du site</Overline><ul style={{margin:'8px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)'}}><li>Barre gouvernementale + en-tête « {i.sigle} »</li><li>Accueil : 3 démarches phares, actualités, organigramme</li><li>Démarches : coût, délai, pièces, suivi</li><li>Le ministère : missions, ministre, textes</li><li>Pied de page réseau</li></ul></div><Button iconRight="arrow-up-right" href={(MINISTERES.find(m=>m.id===i.id)||{}).href||('../ministeres/index.html#'+i.id)}>{tr('Ouvrir le site','Open site')}</Button><Button variant="secondary" iconLeft="arrow-left" onClick={()=>go('annuaire')}>Toutes les institutions</Button></aside>
    </div>
  </Container>;
}
function Communaute({go}){
  const [votes,setVotes]=React.useState(VOTES.map(v=>({...v,userVote:null})));
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Communauté" num={3}>Voter, proposer, faire évoluer le langage</SectionTitle>
    <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>Chaque évolution du langage de conception (composants, contenus, accessibilité) est soumise au vote des citoyens connectés avec Identité Cameroun. Une proposition adoptée entre dans le guide et s’applique à tous les sites.</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'var(--space-4)',marginTop:'var(--space-8)'}}>{votes.map((v,i)=><VoteCard key={i} {...v} onVote={w=>setVotes(s=>s.map((x,j)=>j===i?{...x,userVote:w,votesFor:x.votesFor+(w==='for'&&x.userVote!=='for'?1:0),votesAgainst:x.votesAgainst+(w==='against'&&x.userVote!=='against'?1:0)}:x))}/>)}</div>
  </Container>;
}
function Relais({go,focus}){
  const [sel,setSel]=React.useState(focus||'guichet');const r=RELAIS_DEF[sel];
  const dem=BESOINS.flatMap(b=>b.demarches.filter(d=>d.relais===sel).map(d=>({...d,besoin:b})));
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Relais locaux" num={4}>Là où l’État vous reçoit</SectionTitle>
    <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>Chaque démarche indique son relais : le lieu physique qui accompagne, vérifie ou remet. Les chefferies attestent l’identité et la résidence ; les mairies tiennent l’état civil ; les commissariats enrôlent la biométrie ; les guichets Cameroun numérique accompagnent tout le reste. Un même dossier suit le citoyen d’un relais à l’autre.</p>
    <div role="tablist" aria-label="Type de relais" style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:'var(--space-6)'}}>{Object.entries(RELAIS_DEF).map(([k,v])=><button key={k} type="button" role="tab" aria-selected={sel===k} onClick={()=>setSel(k)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'inline-flex',gap:8,alignItems:'center',minHeight:40,padding:'0 12px',font:'var(--type-caption)',fontWeight:600,border:'2px solid '+(sel===k?'var(--cm-vert-800)':'var(--border-default)'),background:sel===k?'var(--surface-brand-soft)':'var(--surface-card)'}}><Icon name={v.icon} size={14}/>{v.nom}</button>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-8)',marginTop:'var(--space-8)',alignItems:'start'}}>
      <div><div style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)',padding:'var(--space-6)'}}><div style={{display:'flex',gap:14,alignItems:'center'}}><span style={{width:48,height:48,background:'var(--cm-ebene)',display:'grid',placeItems:'center'}}><Icon name={r.icon} size={22} color="var(--cm-jaune-500)"/></span><div><h2 style={{font:'var(--type-h4)'}}>{r.nom}</h2><div style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{r.ou}</div></div></div><p style={{marginTop:14}}>{r.role}</p></div>
        <h3 style={{font:'var(--type-h5)',marginTop:'var(--space-8)'}}>Démarches prises en charge <span style={{color:'var(--text-muted)',fontFamily:'var(--font-mono)',fontWeight:500}}>{dem.length}</span></h3>
        <div style={{display:'grid',gap:2,marginTop:12}}>{dem.map(d=><Row key={d.t} icon={d.besoin.icon} title={d.t} meta={(instOf(d.min)||{}).sigle+' · '+d.cout+' · '+d.delai} right={d.besoin.nom} onClick={()=>go('besoin',d.besoin.id)} style={{background:'var(--surface-card)'}}/>)}{dem.length===0&&<p style={{color:'var(--text-muted)',font:'var(--type-body-sm)'}}>Aucune démarche référencée pour ce relais.</p>}</div></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Comment ça se passe</Overline><ol style={{margin:'10px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)'}}><li>Vous préparez la démarche en ligne ; un code de dossier <span style={{fontFamily:'var(--font-mono)'}}>D-…</span> vous est remis.</li><li>Au relais, l’agent lit le code : rien à ressaisir, pièces déjà connues.</li><li>Il vérifie, atteste ou remet ; l’acte est journalisé dans votre compte.</li><li>Vous recevez un SMS de confirmation et pouvez noter l’accueil.</li></ol></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Trouver le relais le plus proche</Overline><p style={{font:'var(--type-body-sm)',marginTop:8,color:'var(--text-muted)'}}>Annuaire géolocalisé des relais par région (à raccorder à la carte du MINAT et du BUNEC). En attendant : 8100.</p><Button size="sm" variant="secondary" iconLeft="map-pin" style={{marginTop:10}}>Relais près de moi</Button></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-jaune-50)'}}><Overline color="var(--cm-jaune-800)">Aucun frais hors barème</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Le coût affiché en ligne est le seul dû. Tout paiement passe par le Trésor (quittance). <a href="../tresor/index.html">Signaler un abus</a></p></div>
      </aside>
    </div>
  </Container>;
}
function RechercheP({go,query}){
  const res=rechercher(query||'');const gs=[];res.forEach(x=>{const y=gs.find(z=>z.g===x.group);if(y)y.items.push(x);else gs.push({g:x.group,items:[x]});});
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Recherche">Résultats pour « {query} »</SectionTitle>
    <RechercheGlobale onSubmit={q=>go('recherche',q)} style={{maxWidth:680}}/>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:14}} aria-live="polite">{res.length} résultat{res.length>1?'s':''} sur tous les sites de l’État</p>
    {res.length===0&&<div style={{marginTop:'var(--space-6)',padding:'var(--space-8)',border:'1px dashed var(--border-strong)',display:'grid',gap:12,justifyItems:'start'}}><p>Aucun résultat. Essayez un mot plus court (« CNI », « visa », « péage »), parcourez les démarches par besoin ou appelez le 8100.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Button variant="secondary" onClick={()=>go('besoins')}>Démarches par besoin</Button><Button variant="tertiary" onClick={()=>go('annuaire')}>Ministères & services</Button></div></div>}
    <div style={{display:'grid',gap:'var(--space-8)',marginTop:'var(--space-8)'}}>{gs.map(gr=><section key={gr.g}><h2 style={{font:'var(--type-h5)',marginBottom:8}}>{gr.g} <span style={{color:'var(--text-muted)',fontFamily:'var(--font-mono)',fontWeight:500}}>{gr.items.length}</span></h2><div style={{display:'grid',gap:2}}>{gr.items.map(x=><Row key={x.label} icon={x.icon} title={x.label} meta={x.hint} right={x.href.includes('/hub/')?'Cameroun numérique':x.href.includes('/tresor/')?'Trésor public':x.href.includes('/musee/')?'Musée numérique':x.href.includes('/sports/')?'Sports':x.href.includes('/presidence/')?'Présidence':'Site de l’État'} onClick={()=>location.href=x.href} style={{background:'var(--surface-card)'}}/>)}</div></section>)}</div>
  </Container>;
}
Object.assign(window,{Accueil,Besoins,Besoin,Annuaire,Institution,Communaute,Relais,RechercheP});
