const {Button,Card,Badge,Stat,Tag,Icon,Table,Tabs,Stepper,Timeline,Switch,Alert,Toast,ToastStack,IconButton}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
/* Espace connecté : rail gauche (contexte + sections), contenu à droite. Même squelette pour citoyen et pro. */
function Espace({title,sub,initials,accent,sections,tab,setTab,switcher,verif,children}){
  return <>
    <div style={{background:'var(--cm-ebene)',color:'#fff',borderTop:'3px solid '+accent}}><Container style={{padding:'var(--space-6) var(--gutter)',display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}>
      <span style={{width:52,height:52,background:accent,color:'var(--cm-ebene)',display:'grid',placeItems:'center',fontFamily:'var(--font-display)',fontWeight:800,fontSize:20}}>{initials}</span>
      <div style={{minWidth:0,flex:'1 1 260px'}}><div style={{font:'var(--type-h5)',color:'#fff'}}>{title}</div><div style={{font:'var(--type-caption)',color:'var(--cm-gris-300)',marginTop:2,display:'flex',gap:10,flexWrap:'wrap'}}><span style={{fontFamily:'var(--font-mono)'}}>{sub}</span>{verif&&<span style={{display:'inline-flex',gap:5,alignItems:'center',color:'var(--cm-vert-300)'}}><Icon name="badge-check" size={12}/>{verif}</span>}</div></div>
      <div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}>{switcher}<span style={{font:'var(--type-caption)',color:'var(--cm-gris-400)'}}>Dernière connexion : aujourd’hui 08:42 · Douala · <a href="#" style={{color:'var(--cm-gris-200)'}}>Historique</a></span></div>
    </Container>
    <Container style={{padding:'0 var(--gutter)'}}><nav aria-label="Mon espace" style={{display:'flex',gap:2,flexWrap:'wrap'}}>{sections.map(s=><button key={s.id} type="button" aria-current={tab===s.id?'page':undefined} onClick={()=>setTab(s.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'inline-flex',gap:8,alignItems:'center',minHeight:44,padding:'10px 14px',whiteSpace:'nowrap',borderBottom:'3px solid '+(tab===s.id?accent:'transparent'),color:tab===s.id?'#fff':'var(--cm-gris-300)',font:'var(--type-label)',fontWeight:tab===s.id?700:500}}><Icon name={s.icon} size={16}/>{s.label}{s.count!=null&&<span style={{font:'var(--type-caption)',fontFamily:'var(--font-mono)',padding:'0 6px',minWidth:18,height:18,display:'inline-grid',placeItems:'center',background:s.urg?'var(--cm-rouge-600)':'rgba(255,255,255,.14)',color:'#fff'}}>{s.count}</span>}</button>)}</nav></Container></div>
    <Container style={{padding:'var(--space-8) var(--gutter) var(--space-16)'}}>{children}</Container>
  </>;
}
const H=({children,action,sub})=><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:16,flexWrap:'wrap',marginBottom:'var(--space-6)'}}><div><h1 style={{font:'var(--type-h3)'}}>{children}</h1>{sub&&<p style={{color:'var(--text-muted)',marginTop:4}}>{sub}</p>}</div>{action}</div>;
const Bloc=({title,action,children,style})=><section style={{background:'var(--surface-card)',border:'var(--hairline)',...style}}>{title&&<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:'12px var(--space-5)',borderBottom:'var(--hairline)'}}><h2 style={{font:'var(--type-h6)'}}>{title}</h2>{action}</div>}{children}</section>;
const Progress=({pct,color='var(--cm-vert-800)'})=><div role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} style={{height:4,background:'var(--cm-gris-100)'}}><div style={{height:'100%',width:pct+'%',background:color}}/></div>;
function Citoyen({go,tab,setTab,setUser}){
  const c=CITOYEN;const [prefs,setPrefs]=React.useState({sms:true,mail:true,push:false,partage:true});const [unlock,setUnlock]=React.useState(0);const [asking,setAsking]=React.useState(false);const [thread,setThread]=React.useState(0);const [reply,setReply]=React.useState('');
  React.useEffect(()=>{if(!unlock)return;const t=setTimeout(()=>setUnlock(0),600000);return()=>clearTimeout(t);},[unlock]);
  const SENSIBLES=[{t:'Dossier médical — synthèse',ref:'MINSANTE · DMP',date:'mis à jour le 3 fév. 2026',type:'Santé'},{t:'Revenus déclarés 2025',ref:'DGI · IRPP',date:'15 mars 2026',type:'Fiscal'},{t:'Gabarit biométrique (empreintes, visage)',ref:'DGSN · chiffré, non exportable',date:'enrôlement du 2 sept. 2026',type:'Identité'},{t:'Situation familiale et ayants droit',ref:'BUNEC · CNPS',date:'à jour',type:'Famille'}];
  const THREADS=[{min:'MINSANTE',sujet:'Couverture santé universelle — pièce attendue',msgs:[{de:'MINSANTE',q:'hier 10:12',t:'Bonjour Élise, votre dossier CSU-2026-002-8815 attend un justificatif de domicile (facture ou attestation de la chefferie). Vous pouvez le déposer depuis votre coffre.'},{de:'moi',q:'hier 18:40',t:'Merci, je dépose l’attestation de la chefferie de Bonapriso demain.'}],lu:false},{min:'DGI',sujet:'Votre quittance IRPP 2025 est disponible',msgs:[{de:'DGI',q:'15 mars',t:'La quittance Q-2026-0193 (184 000 FCFA) est certifiée et rangée dans votre coffre. Aucune action requise.'}],lu:false},{min:'DGSN',sujet:'CNI : production lancée',msgs:[{de:'DGSN',q:'il y a 2 jours',t:'Votre carte CNI-2026-113-4482 est en production. Retrait prévu au commissariat de Douala 1er ; vous recevrez un SMS.'}],lu:true},{min:'MINEDUB',sujet:'Résultats du CEP publiés',msgs:[{de:'MINEDUB',q:'12 juil.',t:'Les résultats du CEP 2026 sont consultables. Le relevé d’Amadou sera versé au coffre famille après validation.'}],lu:true}];
  const sections=[{id:'tdb',icon:'layout-dashboard',label:'Tableau de bord'},{id:'demarches',icon:'file-clock',label:'Mes démarches',count:c.demarches.filter(d=>d.pct<100).length},{id:'documents',icon:'vault',label:'Mes documents',count:c.documents.length},{id:'messagerie',icon:'mail',label:'Messagerie',count:c.notifications.filter(n=>!n.lu).length,urg:true},{id:'echeances',icon:'bell',label:'Échéances & notifications',count:c.echeances.filter(e=>e.urg).length,urg:true},{id:'famille',icon:'users',label:'Famille',count:c.famille.length},{id:'sante',icon:'heart-pulse',label:'Santé'},{id:'prefs',icon:'settings',label:'Préférences & accessibilité'}];
  const switcher=<Button size="sm" variant="inverse" iconLeft="arrow-left-right" onClick={()=>{setUser({nom:PRO.nom,initials:PRO.initials,type:'pro'});go('pro');}}>Contexte : citoyenne · passer à {PRO.nom}</Button>;
  const DemRow=({d})=>{const i=instOf(d.min.split(' ')[0].toLowerCase());return <div style={{padding:'var(--space-4) var(--space-5)',borderBottom:'var(--hairline)',display:'grid',gap:10}}><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'start'}}><div><div style={{font:'var(--type-label)',fontWeight:600}}>{d.t}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:2}}>{d.min} · <span style={{fontFamily:'var(--font-mono)'}}>{d.ref}</span> · mis à jour {d.maj}</div></div><Badge status={d.pct===100?'success':d.alerte?'warning':'info'} size="sm">{d.statut}</Badge></div><Stepper steps={d.etapes} current={d.cur}/>{d.alerte&&<Alert status="warning" size="sm">{d.alerte} <a href="#">Ajouter la pièce</a></Alert>}</div>;};
  return <Espace title={c.nom} sub={c.id} initials={c.initials} accent="var(--cm-vert-500)" verif={c.verif} sections={sections} tab={tab} setTab={setTab} switcher={switcher}>
    {tab==='tdb'&&<><H sub={c.ville} action={<Button iconLeft="plus" onClick={()=>go('besoins')}>Nouvelle démarche</Button>}>Bonjour, Élise</H>
      {c.echeances.filter(e=>e.urg).length>0&&<Alert status="warning" title={c.echeances.filter(e=>e.urg).length+' échéances à traiter'} style={{marginBottom:'var(--space-6)'}}>{c.echeances.filter(e=>e.urg).map(e=>e.t+' ('+e.d+')').join(' · ')} <a href="#" onClick={ev=>{ev.preventDefault();setTab('echeances');}}>Voir</a></Alert>}
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-4)',marginBottom:'var(--space-6)'}}><Stat size="sm" value={c.demarches.filter(d=>d.pct<100).length} label="démarches en cours" accent="vert"/><Stat size="sm" value={c.documents.length} label="documents certifiés" accent="indigo"/><Stat size="sm" value={c.echeances.length} label="échéances" detail={c.echeances.filter(e=>e.urg).length+' urgentes'} accent="laterite"/><Stat size="sm" value={c.famille.length} label="proches rattachés" accent="kola"/></div>
      <div style={{display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-6)',alignItems:'stretch'}}>
        <Bloc title="Démarches en cours" action={<Button size="sm" variant="tertiary" onClick={()=>setTab('demarches')}>Toutes</Button>}>{c.demarches.filter(d=>d.pct<100).map((d,i)=><DemRow key={i} d={d}/>)}</Bloc>
        <div style={{display:'grid',gap:'var(--space-6)'}}><Bloc title="Notifications" action={<Button size="sm" variant="tertiary" onClick={()=>setTab('echeances')}>Tout lire</Button>}>{c.notifications.map((n,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'8px 1fr auto',gap:12,alignItems:'start',padding:'10px var(--space-5)',borderBottom:'var(--hairline)'}}><span style={{width:8,height:8,marginTop:6,background:n.lu?'transparent':'var(--cm-rouge-600)',border:'1px solid '+(n.lu?'var(--cm-gris-300)':'var(--cm-rouge-600)')}}/><span><span style={{font:'var(--type-body-sm)',fontWeight:n.lu?500:700,display:'block'}}>{n.t}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{n.min}</span></span><span style={{font:'var(--type-caption)',color:'var(--text-muted)',whiteSpace:'nowrap'}}>{n.q}</span></div>)}</Bloc>
        <Bloc title="Documents récents" action={<Button size="sm" variant="tertiary" onClick={()=>setTab('documents')}>Coffre</Button>}>{c.documents.slice(0,3).map((d,i)=><Row key={i} icon="file-check" title={d.t} meta={d.ref} right={d.date}/>)}</Bloc></div>
      </div></>}
    {tab==='demarches'&&<><H sub="Toutes vos démarches, quel que soit le ministère. Chaque étape est horodatée." action={<Button iconLeft="plus" onClick={()=>go('besoins')}>Nouvelle démarche</Button>}>Mes démarches</H><Bloc>{c.demarches.map((d,i)=><DemRow key={i} d={d}/>)}</Bloc></>}
    {tab==='documents'&&<><H sub="Un seul coffre : les documents émis par l’État (diplômes, actes, quittances) et, derrière une confirmation supplémentaire, vos données très personnelles. Le coffre ne stocke que des liens certifiés ; chaque consultation est journalisée." action={<Button variant="secondary" iconLeft="upload">Déposer une pièce</Button>}>Mes documents</H>
      {[['Actes et identité',['État civil','Identité']],['Diplômes et attestations',['Éducation']],['Quittances et fiscalité',['Fiscal']],['Santé et transport',['Santé','Transport']]].map(([g,types])=>{const rows=c.documents.filter(d=>types.includes(d.type));return rows.length?<Bloc key={g} title={g} style={{marginBottom:'var(--space-4)'}}><Table columns={[{key:'t',label:'Document',strong:true},{key:'ref',label:'Référence',mono:true},{key:'date',label:'Date / validité',render:(v,r)=><span style={{color:r.alerte?'var(--cm-rouge-600)':'inherit',fontWeight:r.alerte?600:400}}>{v}{r.alerte&&<span style={{display:'block',font:'var(--type-caption)'}}>{r.alerte}</span>}</span>},{key:'verif',label:'État',render:()=><span style={{display:'inline-flex',gap:6,alignItems:'center',color:'var(--cm-vert-800)',font:'var(--type-caption)',fontWeight:600}}><Icon name="badge-check" size={14}/>certifié</span>},{key:'x',label:'',align:'right',render:()=><span style={{display:'inline-flex',gap:4}}><IconButton icon="eye" label="Consulter" variant="tertiary" size="sm"/><IconButton icon="download" label="Télécharger" variant="tertiary" size="sm"/><IconButton icon="share-2" label="Partager un lien à durée limitée" variant="tertiary" size="sm"/></span>}]} rows={rows}/></Bloc>:null;})}
      <Bloc title={<span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Icon name="lock" size={16} color="var(--cm-rouge-600)"/>Données très personnelles</span>} action={unlock?<Button size="sm" variant="tertiary" iconLeft="lock" onClick={()=>setUnlock(0)}>Verrouiller</Button>:<Badge status="error" size="sm">Accès protégé</Badge>} style={{borderTop:'3px solid var(--cm-rouge-600)'}}>
        {!unlock&&!asking&&<div style={{padding:'var(--space-6)',display:'grid',gridTemplateColumns:'44px 1fr',gap:14,alignItems:'start'}}><span style={{width:44,height:44,background:'var(--cm-rouge-50)',display:'grid',placeItems:'center'}}><Icon name="shield-alert" size={22} color="var(--cm-rouge-600)"/></span><div><p>Ces données (santé, revenus, biométrie) exigent une confirmation supplémentaire, même connecté·e. Chaque ouverture est journalisée.</p><ul style={{margin:'8px 0 0',paddingLeft:18,font:'var(--type-body-sm)',color:'var(--text-muted)'}}>{SENSIBLES.map(s=><li key={s.t}>{s.t} <span style={{color:'var(--text-subtle)'}}>· {s.ref}</span></li>)}</ul><Button iconLeft="fingerprint" onClick={()=>setAsking(true)} style={{marginTop:14}}>Confirmer avec ma clé d’accès</Button></div></div>}
        {asking&&<div style={{padding:'var(--space-6)',display:'grid',justifyItems:'center',gap:12,textAlign:'center'}}><span style={{width:56,height:56,borderRadius:'50%',border:'3px solid var(--cm-rouge-600)',borderTopColor:'transparent',display:'grid',placeItems:'center'}}><Icon name="smartphone" size={22} color="var(--cm-rouge-600)"/></span><div style={{font:'var(--type-h6)'}}>Confirmez sur votre téléphone</div><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',maxWidth:'40ch'}}>Code de session <span style={{fontFamily:'var(--font-mono)'}}>VX-18</span>. Le déverrouillage vaut 10 minutes puis se referme seul.</p><div style={{display:'flex',gap:8}}><Button variant="tertiary" onClick={()=>setAsking(false)}>Annuler</Button><Button onClick={()=>{setAsking(false);setUnlock(Date.now());}}>Simuler la confirmation</Button></div></div>}
        {unlock>0&&<><div style={{padding:'10px var(--space-5)',background:'var(--cm-rouge-50)',font:'var(--type-caption)',color:'var(--cm-rouge-700)',display:'flex',gap:8,alignItems:'center'}}><Icon name="unlock" size={14}/>Déverrouillé pour 10 minutes · accès journalisé (aujourd’hui, Douala)</div><Table columns={[{key:'t',label:'Donnée',strong:true},{key:'type',label:'Type',render:v=><Badge status="error" size="sm">{v}</Badge>},{key:'ref',label:'Source',mono:true},{key:'date',label:'Mise à jour'},{key:'x',label:'',align:'right',render:()=><span style={{display:'inline-flex',gap:4}}><IconButton icon="eye" label="Consulter" variant="tertiary" size="sm"/><IconButton icon="history" label="Qui a consulté" variant="tertiary" size="sm"/></span>}]} rows={SENSIBLES}/></>}
      </Bloc></>}
    {tab==='messagerie'&&<><H sub="Toutes les notifications et messages des ministères, dans un seul fil sécurisé. Aucun ministère ne vous écrira ailleurs." action={<Button iconLeft="pen-line">Nouveau message</Button>}>Messagerie</H>
      <div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(0,2fr)',gap:'var(--space-4)',alignItems:'start'}}>
        <Bloc title="Boîte de réception">{THREADS.map((th,i)=><button key={i} type="button" aria-current={thread===i?'true':undefined} onClick={()=>setThread(i)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'8px 1fr auto',gap:12,alignItems:'start',width:'100%',padding:'12px var(--space-5)',borderBottom:'var(--hairline)',borderLeft:'3px solid '+(thread===i?'var(--cm-vert-800)':'transparent'),background:thread===i?'var(--surface-page)':'transparent',textAlign:'left'}}><span style={{width:8,height:8,marginTop:6,background:th.lu?'transparent':'var(--cm-rouge-600)',border:'1px solid '+(th.lu?'var(--cm-gris-300)':'var(--cm-rouge-600)')}} aria-label={th.lu?'':'Non lu'}/><span style={{minWidth:0}}><span style={{font:'var(--type-caption)',color:'var(--text-muted)',display:'block'}}>{th.min}</span><span style={{font:'var(--type-body-sm)',fontWeight:th.lu?500:700,display:'block'}}>{th.sujet}</span></span><span style={{font:'var(--type-caption)',color:'var(--text-muted)',whiteSpace:'nowrap'}}>{th.msgs[th.msgs.length-1].q}</span></button>)}</Bloc>
        <Bloc title={<span><span style={{font:'var(--type-caption)',color:'var(--text-muted)',display:'block',fontWeight:500}}>{THREADS[thread].min}</span>{THREADS[thread].sujet}</span>} action={<Badge status="brand" size="sm">canal officiel vérifié</Badge>}>
          <div style={{padding:'var(--space-5)',display:'grid',gap:12}}>{THREADS[thread].msgs.map((m,j)=><div key={j} style={{display:'grid',gap:4,justifyItems:m.de==='moi'?'end':'start'}}><div style={{maxWidth:'70ch',padding:'12px 14px',background:m.de==='moi'?'var(--surface-brand-soft)':'var(--surface-page)',border:'var(--hairline)',borderLeft:m.de==='moi'?'var(--hairline)':'3px solid var(--cm-vert-800)'}}><p style={{font:'var(--type-body-sm)'}}>{m.t}</p></div><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{m.de==='moi'?'Vous':m.de} · {m.q}</span></div>)}</div>
          <div style={{padding:'var(--space-4) var(--space-5)',borderTop:'var(--hairline)',display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input value={reply} onChange={e=>setReply(e.target.value)} aria-label="Répondre" placeholder="Répondre…" style={{height:44,border:'2px solid var(--border-input)',padding:'0 12px',font:'var(--type-body)',boxSizing:'border-box'}}/><Button iconLeft="send" onClick={()=>setReply('')}>Envoyer</Button></div>
        </Bloc>
      </div></>}
    {tab==='echeances'&&<><H sub="Rappels par SMS et e-mail 30, 7 et 1 jour avant.">Échéances & notifications</H><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:'var(--space-6)',alignItems:'start'}}><Bloc title="Échéances"><Timeline items={c.echeances.map(e=>({title:e.t,description:e.min,when:e.d,status:e.urg?'current':'todo'}))} style={{padding:'var(--space-5)'}}/></Bloc><Bloc title="Notifications">{c.notifications.map((n,i)=><Row key={i} title={n.t} meta={n.min} right={n.q}/>)}</Bloc></div></>}
    {tab==='famille'&&<><H sub="Vos enfants mineurs et ayants droit. Vous agissez pour eux ; ils reprennent la main à leur majorité." action={<Button variant="secondary" iconLeft="user-plus">Rattacher un proche</Button>}>Famille</H><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:'var(--space-4)'}}>{c.famille.map((f,i)=><article key={i} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-5)',display:'grid',gap:8}}><div style={{display:'flex',gap:12,alignItems:'center'}}><span style={{width:40,height:40,background:'var(--surface-brand-soft)',display:'grid',placeItems:'center',fontFamily:'var(--font-display)',fontWeight:800,color:'var(--cm-vert-800)'}}>{f.n.split(' ').map(w=>w[0]).slice(0,2).join('')}</span><div><div style={{font:'var(--type-h6)'}}>{f.n}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{f.lien}</div></div></div><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)'}}>{f.docs}</p><Button size="sm" variant="tertiary" iconRight="arrow-right">Voir ses documents</Button></article>)}</div></>}
    {tab==='sante'&&<><H sub="Données du ministère de la Santé publique. Visibles par vous et, en urgence, par un professionnel habilité avec votre carte CSU.">Santé</H><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:'var(--space-6)',alignItems:'start'}}><Bloc title="Carnet">{c.sante.map(([k,v])=><div key={k} style={{display:'grid',gridTemplateColumns:'140px 1fr',gap:12,padding:'10px var(--space-5)',borderBottom:'var(--hairline)',font:'var(--type-body-sm)'}}><span style={{color:'var(--text-muted)'}}>{k}</span><span style={{fontWeight:600}}>{v}</span></div>)}</Bloc><Bloc title="Vaccinations"><Timeline items={[{title:'Fièvre jaune',when:'3 fév. 2026',status:'done'},{title:'Tétanos — rappel',when:'nov. 2025',status:'done'},{title:'COVID-19 — 3 doses',when:'2022',status:'done'},{title:'Hépatite B — rappel conseillé',when:'2027',status:'todo'}]} style={{padding:'var(--space-5)'}}/></Bloc></div></>}
    {tab==='prefs'&&<><H sub="Ces réglages s’appliquent sur tous les sites de l’État dès que vous êtes connectée.">Préférences & accessibilité</H><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:'var(--space-6)',alignItems:'start'}}><Bloc title="Notifications"><div style={{padding:'var(--space-5)',display:'grid',gap:16}}><Switch checked={prefs.sms} onChange={v=>setPrefs({...prefs,sms:v})} label="SMS" hint="6•• ••• •31"/><Switch checked={prefs.mail} onChange={v=>setPrefs({...prefs,mail:v})} label="E-mail" hint="e.ngobassong@…"/><Switch checked={prefs.push} onChange={v=>setPrefs({...prefs,push:v})} label="Notifications de l’application"/></div></Bloc><Bloc title="Accessibilité synchronisée"><div style={{padding:'var(--space-5)',display:'grid',gap:12,font:'var(--type-body-sm)'}}><p>Vos réglages du panneau Accessibilité (taille, contraste, police, FALC) sont enregistrés dans votre identité et appliqués partout.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Badge>Taille 100 %</Badge><Badge>Contraste normal</Badge><Badge>FALC désactivé</Badge></div><Switch checked={prefs.partage} onChange={v=>setPrefs({...prefs,partage:v})} label="Synchroniser sur tous mes appareils"/><p style={{color:'var(--text-muted)'}}>Langue préférée : français. <a href="#">Passer à l’anglais</a></p></div></Bloc>
      <Bloc title="Sécurité" action={<Button size="sm" variant="tertiary" iconLeft="printer">Codes de secours</Button>} style={{gridColumn:'1 / -1'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:0}}>{[['Samsung A54 — Élise','Clé d’accès · appareil principal','aujourd’hui 08:42 · Douala',true],['Ordinateur — Chrome','Appareil de confiance · 30 jours','hier 19:10 · Douala',false],['Guichet Douala 1er','Accès agent · demande CNI','12 août 2026',false]].map(([n,t,q,main])=><div key={n} style={{padding:'var(--space-4) var(--space-5)',borderBottom:'var(--hairline)',display:'grid',gridTemplateColumns:'1fr auto',gap:8,alignItems:'center'}}><div><div style={{font:'var(--type-label)',fontWeight:600}}>{n}{main&&<Badge status="brand" size="sm" style={{marginLeft:8}}>principal</Badge>}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:2}}>{t} · {q}</div></div>{!main&&<Button size="sm" variant="tertiary">Retirer</Button>}</div>)}</div><div style={{padding:'12px var(--space-5)',font:'var(--type-caption)',color:'var(--text-muted)'}}>Chaque nouvelle connexion vous est notifiée par SMS et ici. <a href="#">Journal complet des accès</a></div></Bloc></div></>}
  </Espace>;
}
function Pro({go,tab,setTab,setUser}){
  const p=PRO;const [toast,setToast]=React.useState(null);
  const sections=[{id:'tdb',icon:'layout-dashboard',label:'Tableau de bord'},{id:'fiscal',icon:'receipt',label:'Fiscalité',count:p.obligations.filter(o=>o.urg).length,urg:true},{id:'salaries',icon:'users',label:'Salariés & CNPS',count:p.effectif},{id:'marches',icon:'gavel',label:'Marchés publics',count:p.marches.filter(m=>m.statut==='Ouvert').length},{id:'licences',icon:'file-badge',label:'Licences & agréments',count:p.licences.length},{id:'delegation',icon:'key-round',label:'Délégation d’accès',count:p.delegations.length},{id:'douanes',icon:'ship',label:'Import / export'}];
  const switcher=<Button size="sm" variant="inverse" iconLeft="arrow-left-right" onClick={()=>{setUser({nom:CITOYEN.nom,initials:CITOYEN.initials,type:'citoyen'});go('citoyen');}}>Contexte : professionnel · passer à Élise Ngo Bassong</Button>;
  const money=v=><span style={{fontFamily:'var(--font-mono)',fontVariantNumeric:'tabular-nums'}}>{v} FCFA</span>;
  return <Espace title={p.nom} sub={'NIU '+p.niu} initials={p.initials} accent="var(--cm-indigo-300)" verif={'Mandataire : '+p.mandataire} sections={sections} tab={tab} setTab={setTab} switcher={switcher}>
    {tab==='tdb'&&<><H sub={p.regime+' · '+p.rccm+' · '+p.siege+' · mandataire : '+p.mandataire} action={<Button iconLeft="file-plus" onClick={()=>setTab('fiscal')}>Déclarer la TVA d’août</Button>}>{p.nom}</H>
      <Alert status="warning" title="1 obligation à échéance le 15 septembre" style={{marginBottom:'var(--space-6)'}}>Déclaration mensuelle de TVA — août 2026 (DGI). Pénalité de 10 % après la date. <a href="#" onClick={e=>{e.preventDefault();setTab('fiscal');}}>Déclarer</a></Alert>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-4)',marginBottom:'var(--space-6)'}}><Stat size="sm" value={p.obligations.length} label="obligations à venir" detail="90 jours" accent="laterite"/><Stat size="sm" value={p.effectif} label="salariés déclarés" detail="CNPS à jour" accent="vert"/><Stat size="sm" value={p.marches.filter(m=>m.statut==='Ouvert').length} label="appels d’offres ciblés" accent="indigo"/><Stat size="sm" value={p.licences.length} label="licences valides" detail="1 renouvellement" accent="kola"/></div>
      <div style={{display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(260px,2fr)',gap:'var(--space-6)',alignItems:'start'}}>
        <Bloc title="Calendrier des obligations" action={<Button size="sm" variant="tertiary" iconLeft="calendar-plus">Exporter (.ics)</Button>}><Timeline items={p.obligations.map(o=>({title:o.t,description:o.min,when:o.d,status:o.urg?'current':'todo'}))} style={{padding:'var(--space-5)'}}/></Bloc>
        <div style={{display:'grid',gap:'var(--space-6)'}}><Bloc title="Dernières quittances" action={<Button size="sm" variant="tertiary" onClick={()=>setTab('fiscal')}>Toutes</Button>}>{p.quittances.slice(0,3).map((q,i)=><Row key={i} icon="receipt" title={q[1]} meta={q[0]} right={money(q[2])}/>)}</Bloc><Bloc title="Appels d’offres ouverts" action={<Button size="sm" variant="tertiary" onClick={()=>setTab('marches')}>Tous</Button>}>{p.marches.filter(m=>m.statut==='Ouvert').map((m,i)=><Row key={i} icon="gavel" title={m.t} meta={m.ref+' · '+m.d} right={m.montant}/>)}</Bloc></div>
      </div></>}
    {tab==='fiscal'&&<><H sub="Direction générale des Impôts. Déclarations, paiements et quittances certifiées." action={<Button iconLeft="file-plus" onClick={()=>setToast('Déclaration TVA août 2026 enregistrée. Quittance disponible après paiement.')}>Nouvelle déclaration</Button>}>Fiscalité</H>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:'var(--space-4)',marginBottom:'var(--space-6)'}}>{[['NIU',p.niu],['Régime',p.regime],['Centre',"CIME Douala Bassa"],['Attestation de conformité fiscale','valide → 31 déc. 2026']].map(([k,v])=><div key={k} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-4)'}}><div style={{font:'var(--type-caption)',color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>{k}</div><div style={{font:'var(--type-label)',fontWeight:600,marginTop:4,fontFamily:k==='NIU'?'var(--font-mono)':'inherit'}}>{v}</div></div>)}</div>
      <Bloc title="Obligations" style={{marginBottom:'var(--space-6)'}}>{p.obligations.filter(o=>o.min==='DGI').map((o,i)=><Row key={i} title={o.t} meta={o.min+' · '+o.d} right={<Badge status={o.urg?'warning':'neutral'} size="sm">{o.statut}</Badge>}/>)}</Bloc>
      <Table caption="Quittances" columns={[{key:'0',label:'Quittance',mono:true},{key:'1',label:'Objet',strong:true},{key:'2',label:'Montant (FCFA)',align:'right',mono:true},{key:'3',label:'Date'},{key:'x',label:'',align:'right',render:()=><IconButton icon="download" label="Télécharger la quittance" variant="tertiary" size="sm"/>}]} rows={p.quittances}/></>}
    {tab==='salaries'&&<><H sub="Déclarations sociales et cotisations à la Caisse nationale de prévoyance sociale." action={<Button variant="secondary" iconLeft="user-plus">Déclarer une embauche</Button>}>Salariés & CNPS</H><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-4)',marginBottom:'var(--space-6)'}}><Stat size="sm" value={p.effectif} label="salariés" accent="vert"/><Stat size="sm" value="100 %" label="immatriculés CNPS" accent="indigo"/><Stat size="sm" value="15 oct." label="prochaine cotisation" detail="3e trimestre" accent="laterite"/></div><Table caption="Salariés déclarés" columns={[{key:'0',label:'Salarié',strong:true},{key:'1',label:'Poste'},{key:'2',label:'Contrat'},{key:'3',label:'CNPS',render:v=><Badge status="success" size="sm">{v}</Badge>}]} rows={p.salaries}/></>}
    {tab==='marches'&&<><H sub="Appels d’offres correspondant à votre secteur (agro-industrie, Littoral). Alertes à chaque publication.">Marchés publics</H><div style={{display:'grid',gap:'var(--space-4)'}}>{p.marches.map((m,i)=><article key={i} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-5)',display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'start'}}><div><div style={{font:'var(--type-h6)'}}>{m.t}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:4}}><span style={{fontFamily:'var(--font-mono)'}}>{m.ref}</span> · {m.d} · {m.montant}</div><div style={{display:'flex',gap:8,marginTop:12}}>{m.statut==='Ouvert'?<><Button size="sm" iconRight="arrow-right">Soumissionner</Button><Button size="sm" variant="tertiary" iconLeft="download">Dossier d’appel d’offres</Button></>:<Button size="sm" variant="tertiary" iconLeft="file-text">Contrat et suivi</Button>}</div></div><Badge status={m.statut==='Ouvert'?'info':'success'}>{m.statut}</Badge></article>)}</div></>}
    {tab==='licences'&&<><H sub="Toutes vos autorisations, quel que soit le ministère émetteur, avec rappel avant expiration.">Licences & agréments</H><Table caption="Autorisations" columns={[{key:'0',label:'Autorisation',strong:true},{key:'1',label:'Ministère',mono:true},{key:'2',label:'Validité',render:v=><Badge status={v.includes('cours')?'warning':'success'} size="sm">{v}</Badge>},{key:'x',label:'',align:'right',render:(_,r)=><Button size="sm" variant="tertiary" iconRight="arrow-right">{r[2].includes('cours')?'Suivre':'Renouveler'}</Button>}]} rows={p.licences}/></>}
    {tab==='delegation'&&<><H sub="Donnez un accès limité à un comptable ou un mandataire. Chaque action est faite en son nom, sous votre responsabilité, et journalisée." action={<Button variant="secondary" iconLeft="key-round">Ajouter un mandat</Button>}>Délégation d’accès</H><div style={{display:'grid',gap:'var(--space-4)'}}>{p.delegations.map((d,i)=><article key={i} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-5)',display:'grid',gridTemplateColumns:'1fr auto',gap:12}}><div><div style={{font:'var(--type-h6)'}}>{d.n}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:2}}>{d.role} · depuis {d.depuis}</div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:10}}>{d.droits.split(', ').map(x=><Badge key={x} size="sm">{x}</Badge>)}</div></div><div style={{display:'grid',gap:6}}><Button size="sm" variant="tertiary">Modifier</Button><Button size="sm" variant="danger">Révoquer</Button></div></article>)}</div></>}
    {tab==='douanes'&&<><H sub="Direction générale des Douanes. Déclarations et suivi des marchandises aux ports de Douala et Kribi.">Import / export</H><Table caption="Déclarations en douane" columns={[{key:'0',label:'Déclaration',mono:true},{key:'1',label:'Marchandise',strong:true},{key:'2',label:'Port'},{key:'3',label:'Statut',render:v=><Badge status={v==='Dédouané'?'success':'info'} size="sm">{v}</Badge>},{key:'4',label:'Date'}]} rows={p.douanes}/></>}
    {toast&&<Alert status="success" title="Enregistré" style={{marginTop:'var(--space-6)'}}>{toast} <a href="#" onClick={e=>{e.preventDefault();setToast(null);}}>Fermer</a></Alert>}
  </Espace>;
}
Object.assign(window,{Citoyen,Pro});
