// Hub « Cameroun numérique » — données. Liste des institutions selon l'organisation du gouvernement en vigueur (à valider sur le décret d'organisation ; voir dossier-perso).
// Démarches : chacune porte le ministère émetteur, le service en ligne existant, le coût et le délai réglementaires (à vérifier au décret ; « — » quand non publié).
const RELAIS_DEF={guichet:{nom:'Guichet Cameroun numérique',icon:'monitor',ou:'Chef-lieu de département',role:'Accompagnement à toute démarche en ligne, enrôlement Identité Cameroun, impression de documents certifiés.'},mairie:{nom:'Mairie / centre d’état civil',icon:'building',ou:'Chaque commune (BUNEC)',role:'Actes d’état civil, attestations, timbres communaux, remise de documents.'},chefferie:{nom:'Chefferie traditionnelle',icon:'crown',ou:'Village, quartier',role:'Témoignage d’identité et de résidence, déclarations tardives, conciliation foncière coutumière, recensement.'},commissariat:{nom:'Commissariat / brigade de gendarmerie',icon:'shield',ou:'Arrondissement',role:'Enrôlement CNI et passeport, plaintes, vérification biométrique de niveau 3.'},sousprefecture:{nom:'Sous-préfecture',icon:'landmark',ou:'Arrondissement',role:'Associations, autorisations, légalisations, protection civile.'},impots:{nom:'Centre des impôts (CDI / CIME)',icon:'receipt',ou:'Département',role:'NIU, attestations, contentieux fiscal, caisse du Trésor.'},tribunal:{nom:'Tribunal de première instance',icon:'scale',ou:'Département',role:'Casier judiciaire, nationalité, jugements supplétifs, aide juridictionnelle.'},hopital:{nom:'Hôpital ou centre de santé',icon:'heart-pulse',ou:'District de santé',role:'Inscription CSU, vaccination, certificats médicaux.'},consulat:{nom:'Ambassade / consulat',icon:'globe',ou:'À l’étranger',role:'Immatriculation, passeports, légalisations, enrôlement Identité Cameroun.'},ecole:{nom:'Établissement scolaire ou universitaire',icon:'graduation-cap',ou:'Secteur',role:'Inscriptions, bourses, retrait de diplômes.'}};
const DEF_RELAIS={mindevel:'mairie',dgsn:'commissariat',minjustice:'tribunal',minsante:'hopital',minfi:'impots',minat:'sousprefecture',minrex:'consulat',minedub:'ecole',minesec:'ecole',minesup:'ecole'};
const D=(t,min,svc,cout,delai,relais)=>({t,min,svc,cout,delai,relais:relais||DEF_RELAIS[min]||'guichet',enLigne:!/relais|guichet|tribunal|chefferie/.test(relais||'')});
const BESOINS=[
 {id:'papiers',nom:'Papiers & identité',en:'Identity & documents',icon:'id-card',d:'Carte nationale d’identité, passeport, actes d’état civil, casier judiciaire, certificat de nationalité.',min:['dgsn','mindevel','minjustice'],demarches:[D('Demander un acte de naissance (copie certifiée)','mindevel','BUNEC — centres d’état civil','Gratuit (timbre communal selon commune)','48 h'),D('Renouveler sa carte nationale d’identité','dgsn','DGSN — pré-enrôlement en ligne','2 800 FCFA','48 h à 15 jours'),D('Obtenir un passeport biométrique','dgsn','DGSN — passeport.dgsn.cm','110 000 FCFA','48 h après enrôlement'),D('Demander un extrait de casier judiciaire (bulletin n° 3)','minjustice','Tribunal de première instance','1 500 FCFA (timbre)','72 h'),D('Obtenir un certificat de nationalité','minjustice','Tribunal de première instance','Timbre fiscal','15 jours'),D('Obtenir une attestation de résidence','mindevel','Chefferie de quartier → mairie','Gratuit','24 h','chefferie'),D('Déclarer tardivement une naissance (jugement supplétif)','minjustice','Chefferie (témoins) → tribunal','Timbre','30 jours','chefferie')]},
 {id:'sante',nom:'Santé',en:'Health',icon:'heart-pulse',d:'Couverture santé universelle, carnet de vaccination, hôpitaux, urgences, médicaments.',min:['minsante'],demarches:[D('S’inscrire à la Couverture santé universelle (phase 1)','minsante','CSU — csu.cm','Gratuit pour les cibles (enfants < 5 ans, femmes enceintes, TB, VIH)','Immédiat'),D('Consulter son carnet de vaccination numérique','minsante','PEV — carnet électronique','Gratuit','Immédiat'),D('Trouver un hôpital ou un centre de santé','minsante','Carte sanitaire','Gratuit','Immédiat'),D('Vérifier l’autorisation d’un médicament','minsante','DPML — liste des AMM','Gratuit','Immédiat'),D('Demander un certificat médical d’aptitude','minsante','Formation sanitaire agréée','Selon tarif','24 h')]},
 {id:'impots',nom:'Impôts & finances',en:'Taxes & finance',icon:'receipt',d:'NIU, déclarations, paiement, quittances, attestation de conformité fiscale.',min:['minfi'],demarches:[D('Obtenir son numéro d’identifiant unique (NIU)','minfi','DGI — impots.cm','Gratuit','Immédiat'),D('Télédéclarer ses impôts (IRPP, TVA, IS)','minfi','DGI — téléprocédures','Gratuit','Immédiat'),D('Payer un impôt et obtenir une quittance','minfi','DGI — paiement mobile / banque','Selon impôt','Immédiat'),D('Demander une attestation de conformité fiscale','minfi','DGI — en ligne','Gratuit','48 h'),D('Payer la taxe foncière','minfi','DGI — téléprocédures','0,1 % de la valeur','Immédiat')]},
 {id:'famille',nom:'Famille & état civil',en:'Family & civil status',icon:'users',d:'Naissance, mariage, décès, livret de famille, pensions, aide sociale.',min:['mindevel','minas','minproff'],demarches:[D('Déclarer une naissance','mindevel','Centre d’état civil (BUNEC)','Gratuit dans les 90 jours','Immédiat'),D('Publier des bans et célébrer un mariage civil','mindevel','Centre d’état civil','Timbre communal','30 jours de publication'),D('Déclarer un décès','mindevel','Centre d’état civil','Gratuit','Immédiat'),D('Demander une carte nationale d’invalidité','minas','Délégation MINAS','Gratuit','30 jours'),D('Demander une aide sociale d’urgence','minas','Centre social','Gratuit','Selon commission')]},
 {id:'education',nom:'Éducation & études',en:'Education',icon:'graduation-cap',d:'Inscription scolaire, examens et concours, bourses, universités, équivalences.',min:['minedub','minesec','minesup'],demarches:[D('Inscrire un enfant à l’école primaire publique','minedub','École publique de secteur','Gratuit (frais APEE selon école)','Rentrée'),D('Consulter les résultats du BEPC, probatoire, baccalauréat','minesec','OBC — obc.cm','Gratuit','Publication'),D('Consulter les résultats du GCE','minesec','GCE Board','Gratuit','Publication'),D('Demander une bourse ou une aide universitaire','minesup','MINESUP — bourses','Gratuit','Campagne annuelle'),D('Faire reconnaître un diplôme étranger','minesup','Commission d’équivalence','Timbre','60 jours')]},
 {id:'travail',nom:'Travail & retraite',en:'Work & pensions',icon:'briefcase',d:'CNPS, contrat de travail, emploi, retraite, fonction publique.',min:['mintss','minfopra','minefop'],demarches:[D('S’immatriculer à la CNPS (salarié ou indépendant)','mintss','e-CNPS — cnps.cm','Gratuit','7 jours'),D('Consulter sa carrière et simuler sa pension','mintss','e-CNPS','Gratuit','Immédiat'),D('Faire viser un contrat de travail étranger','mintss','Délégation du Travail','Gratuit','15 jours'),D('S’inscrire au Fonds national de l’emploi','minefop','FNE — fnecm.org','Gratuit','Immédiat'),D('Consulter les concours de la fonction publique','minfopra','MINFOPRA — concours','Gratuit','Publication')]},
 {id:'logement',nom:'Logement & foncier',en:'Housing & land',icon:'home',d:'Titre foncier, permis de construire, logement social, urbanisme, eau et électricité.',min:['mindcaf','minhdu','minee'],demarches:[D('Demander un titre foncier (immatriculation directe)','mindcaf','Conservation foncière','Droits selon superficie','Enquête + 60 jours'),D('Obtenir un certificat de propriété','mindcaf','Conservation foncière','Timbre','7 jours'),D('Attester l’absence de litige foncier coutumier','mindcaf','Chefferie → commission consultative','Gratuit','15 jours','chefferie'),D('Déposer un permis de construire','minhdu','Commune + délégation MINHDU','1 % du coût des travaux','30 jours'),D('Postuler à un logement social (SIC / MAETUR)','minhdu','SIC — sic.cm','Dossier','Commission'),D('Demander un branchement eau ou électricité','minee','CAMWATER / ENEO','Selon devis','15 jours')]},
 {id:'transport',nom:'Transports & mobilité',en:'Transport',icon:'car',d:'Permis de conduire, carte grise, visite technique, transports, aviation.',min:['mint','mintp'],demarches:[D('Passer le permis de conduire','mint','Auto-école agréée + délégation MINT','Selon catégorie','Session'),D('Immatriculer un véhicule (carte grise)','mint','Délégation MINT','Selon puissance','72 h'),D('Faire la visite technique','mint','Centre agréé','Selon catégorie','Immédiat'),D('Obtenir une licence de transport','mint','Délégation MINT','Selon catégorie','15 jours'),D('Consulter l’état des routes nationales','mintp','MINTP — bulletin routier','Gratuit','Immédiat')]},
 {id:'entreprise',nom:'Entreprise & commerce',en:'Business',icon:'store',d:'Création d’entreprise, registre du commerce, licences, marchés publics, PME.',min:['minpmeesa','mincommerce','minmap','minfi'],demarches:[D('Créer une entreprise en 72 h (CFCE)','minpmeesa','Centre de formalités — guichet unique','41 500 FCFA (SARL) · gratuit (EI)','72 h'),D('Obtenir la carte de contribuable de l’entreprise','minfi','DGI — impots.cm','Gratuit','Immédiat'),D('Obtenir une licence d’import-export','mincommerce','MINCOMMERCE — guichet','15 000 FCFA','7 jours'),D('Consulter et répondre aux appels d’offres','minmap','COLEPS — marchespublics.cm','Gratuit','Selon avis'),D('Déclarer ses salariés à la CNPS','mintss','e-CNPS','Gratuit','Mensuel')]},
 {id:'agriculture',nom:'Agriculture, élevage & environnement',en:'Agriculture & environment',icon:'sprout',d:'Semences, intrants, coopératives, élevage, pêche, forêts, climat.',min:['minader','minepia','minfof','minepded'],demarches:[D('Immatriculer une coopérative (OHADA)','minader','Registre des sociétés coopératives','Gratuit','30 jours'),D('Accéder aux intrants et semences subventionnés','minader','Délégation MINADER','Subventionné','Campagne'),D('Obtenir un certificat sanitaire vétérinaire','minepia','Délégation MINEPIA','Selon acte','48 h'),D('Demander un permis d’exploitation forestière','minfof','MINFOF — direction des forêts','Selon surface','90 jours'),D('Déposer une étude d’impact environnemental','minepded','MINEPDED','Frais d’examen','Comité interministériel')]},
 {id:'culture',nom:'Culture, sport & tourisme',en:'Culture, sport & tourism',icon:'landmark',d:'Musée numérique, patrimoine, licences sportives, e-Visa, événements.',min:['minac','minsep','mintoul'],demarches:[D('Visiter le Musée numérique du Cameroun','minac','musee.gouv.cm','Gratuit','Immédiat'),D('Déclarer une œuvre (droit d’auteur)','minac','SOCAM / SONACAM','Selon société','30 jours'),D('Obtenir une licence sportive fédérale','minsep','Fédération concernée','Selon fédération','Saison'),D('Demander un e-Visa','mintoul','evisacam.cm (MINREX)','50 000 – 100 000 FCFA','72 h'),D('Agréer un établissement touristique','mintoul','MINTOUL — classement','Selon catégorie','60 jours')]},
 {id:'securite',nom:'Sécurité & justice',en:'Security & justice',icon:'shield',d:'Plainte, aide juridictionnelle, tribunaux, police, protection civile.',min:['minjustice','dgsn','minat'],demarches:[D('Déposer une plainte','dgsn','Commissariat / brigade','Gratuit','Immédiat'),D('Demander l’aide juridictionnelle','minjustice','Commission d’aide juridictionnelle','Gratuit','30 jours'),D('Suivre une procédure judiciaire','minjustice','Greffe du tribunal','Gratuit','Immédiat'),D('Déclarer une association','minat','Préfecture','Gratuit','2 mois (récépissé)'),D('Alerter la protection civile','minat','117 / 118','Gratuit','Immédiat')]},
 {id:'numerique',nom:'Numérique & communication',en:'Digital & media',icon:'wifi',d:'Identité Cameroun, signature électronique, presse, télécoms, poste.',min:['minpostel','mincom'],demarches:[D('Activer Identité Cameroun','minpostel','identite.gouv.cm','Gratuit','Immédiat'),D('Obtenir un certificat de signature électronique','minpostel','ANTIC — PKI nationale','Selon niveau','7 jours'),D('Identifier sa carte SIM','minpostel','Opérateur (obligation ART)','Gratuit','Immédiat'),D('Consulter le Journal officiel','mincom','Cameroon Tribune / SOPECAM','Gratuit','Publication'),D('Suivre un colis','minpostel','CAMPOST','Gratuit','Immédiat')]},
 {id:'international',nom:'Camerounais de l’étranger & visiteurs',en:'Diaspora & visitors',icon:'globe',d:'Consulats, e-Visa, retour au pays, investissements de la diaspora.',min:['minrex','mintoul'],demarches:[D('Trouver une ambassade ou un consulat','minrex','diplocam.cm','Gratuit','Immédiat'),D('Demander un e-Visa','minrex','evisacam.cm','50 000 – 100 000 FCFA','72 h'),D('S’immatriculer au consulat','minrex','Consulat','Gratuit','7 jours'),D('Légaliser un document pour l’étranger','minrex','Direction des affaires consulaires','Timbre','48 h'),D('Investir au Cameroun (diaspora)','minrex','API — investincameroon.net','Gratuit','Immédiat')]}
];
const CAT_INST=['Institutions de souveraineté','Économie & finances','Social & santé','Éducation & savoirs','Territoire & infrastructures','Production & environnement','Culture, jeunesse & communication'];
const INSTITUTIONS=[
 {id:'prc',sigle:'PRC',nom:'Présidence de la République',cat:'Institutions de souveraineté',int:'Chef de l’État, garant de la Constitution, nomme le gouvernement, préside le Conseil des ministres.',ext:'Conduit la politique étrangère, ratifie les traités, représente la nation.',poids:5,site:'prc.cm',statut:'livré',lien:'../presidence/index.html'},
 {id:'spm',sigle:'SPM',nom:'Services du Premier ministre',cat:'Institutions de souveraineté',int:'Coordonne l’action gouvernementale, arbitre entre ministères, pilote les réformes.',ext:'Suivi des grands programmes financés par les partenaires.',poids:5,site:'spm.gov.cm',statut:'gabarit commun'},
 {id:'an',sigle:'AN / Sénat',nom:'Assemblée nationale & Sénat',cat:'Institutions de souveraineté',int:'Votent la loi et le budget, contrôlent le gouvernement.',ext:'Diplomatie parlementaire.',poids:4,site:'assnat.cm',statut:'gabarit commun'},
 {id:'minrex',sigle:'MINREX',nom:'Ministère des Relations extérieures',cat:'Institutions de souveraineté',int:'Camerounais de l’étranger, passeports diplomatiques, protocole.',ext:'Ambassades, consulats, ONU, UA, CEMAC, Commonwealth, Francophonie ; e-Visa.',poids:5,site:'diplocam.cm',statut:'gabarit commun'},
 {id:'minat',sigle:'MINAT',nom:'Ministère de l’Administration territoriale',cat:'Institutions de souveraineté',int:'Régions et départements, chefferies, élections, protection civile, associations.',ext:'Coopération transfrontalière.',poids:4,site:'minat.gov.cm',statut:'gabarit commun'},
 {id:'mindef',sigle:'MINDEF',nom:'Ministère de la Défense',cat:'Institutions de souveraineté',int:'Forces armées, gendarmerie, service civique.',ext:'Opérations de paix, coopération militaire, sécurité régionale.',poids:5,site:'mindef.cm',statut:'gabarit commun'},
 {id:'dgsn',sigle:'DGSN',nom:'Délégation générale à la Sûreté nationale',cat:'Institutions de souveraineté',int:'Police, CNI, passeports, sécurité publique.',ext:'Police des frontières, Interpol.',poids:4,site:'dgsn.cm',statut:'gabarit commun'},
 {id:'minjustice',sigle:'MINJUSTICE',nom:'Ministère de la Justice',cat:'Institutions de souveraineté',int:'Tribunaux, casier judiciaire, aide juridictionnelle, droits humains.',ext:'Coopération judiciaire, extradition, CPI.',poids:4,site:'minjustice.gov.cm',statut:'gabarit commun'},
 {id:'mindevel',sigle:'MINDDEVEL',nom:'Ministère de la Décentralisation et du Développement local',cat:'Institutions de souveraineté',int:'Communes, état civil (BUNEC), régions, FEICOM.',ext:'Coopération décentralisée.',poids:4,site:'minddevel.gov.cm',statut:'gabarit commun'},
 {id:'minfi',sigle:'MINFI',nom:'Ministère des Finances',cat:'Économie & finances',int:'Budget, impôts (DGI), douanes, Trésor, paie de l’État.',ext:'FMI, Banque mondiale, dette, zone franc, CEMAC.',poids:5,site:'minfi.gov.cm',statut:'livré',lien:'../tresor/index.html'},
 {id:'minepat',sigle:'MINEPAT',nom:'Ministère de l’Économie, de la Planification et de l’Aménagement du territoire',cat:'Économie & finances',int:'SND30, investissements publics, statistiques (INS).',ext:'Coopération au développement, bailleurs.',poids:4,site:'minepat.gov.cm',statut:'gabarit commun'},
 {id:'minmap',sigle:'MINMAP',nom:'Ministère des Marchés publics',cat:'Économie & finances',int:'Appels d’offres, COLEPS, contrôle des marchés.',ext:'Marchés financés par les partenaires.',poids:3,site:'minmap.cm',statut:'gabarit commun'},
 {id:'mincommerce',sigle:'MINCOMMERCE',nom:'Ministère du Commerce',cat:'Économie & finances',int:'Prix, concurrence, protection du consommateur, métrologie.',ext:'OMC, ZLECAf, accords commerciaux, import-export.',poids:3,site:'mincommerce.gov.cm',statut:'gabarit commun'},
 {id:'minpmeesa',sigle:'MINPMEESA',nom:'Ministère des PME, de l’Économie sociale et de l’Artisanat',cat:'Économie & finances',int:'Création d’entreprise (CFCE), artisanat, coopératives.',ext:'Promotion des PME à l’export.',poids:3,site:'minpmeesa.gov.cm',statut:'gabarit commun'},
 {id:'minmidt',sigle:'MINMIDT',nom:'Ministère des Mines, de l’Industrie et du Développement technologique',cat:'Économie & finances',int:'Permis miniers, normes (ANOR), zones industrielles.',ext:'Investisseurs miniers, transferts de technologie.',poids:3,site:'minmidt.cm',statut:'gabarit commun'},
 {id:'minsante',sigle:'MINSANTE',nom:'Ministère de la Santé publique',cat:'Social & santé',int:'Hôpitaux, Couverture santé universelle, vaccination, médicaments, épidémies.',ext:'OMS, Gavi, coopération sanitaire.',poids:5,site:'minsante.cm',statut:'gabarit commun'},
 {id:'mintss',sigle:'MINTSS',nom:'Ministère du Travail et de la Sécurité sociale',cat:'Social & santé',int:'Code du travail, CNPS, inspection, dialogue social.',ext:'OIT, conventions internationales du travail.',poids:4,site:'mintss.gov.cm',statut:'gabarit commun'},
 {id:'minas',sigle:'MINAS',nom:'Ministère des Affaires sociales',cat:'Social & santé',int:'Personnes handicapées, enfance, personnes âgées, aide sociale.',ext:'Conventions sur le handicap et l’enfance.',poids:3,site:'minas.gov.cm',statut:'gabarit commun'},
 {id:'minproff',sigle:'MINPROFF',nom:'Ministère de la Promotion de la femme et de la Famille',cat:'Social & santé',int:'Égalité, famille, mariages collectifs, lutte contre les violences.',ext:'ONU Femmes, engagements internationaux.',poids:3,site:'minproff.gov.cm',statut:'gabarit commun'},
 {id:'minfopra',sigle:'MINFOPRA',nom:'Ministère de la Fonction publique et de la Réforme administrative',cat:'Social & santé',int:'Concours, carrières des agents publics, SIGIPES.',ext:'Réformes appuyées par les partenaires.',poids:3,site:'minfopra.gov.cm',statut:'gabarit commun'},
 {id:'minedub',sigle:'MINEDUB',nom:'Ministère de l’Éducation de base',cat:'Éducation & savoirs',int:'Maternelle et primaire, CEP, manuels, cantines.',ext:'UNESCO, UNICEF, Partenariat mondial pour l’éducation.',poids:4,site:'minedub.cm',statut:'gabarit commun'},
 {id:'minesec',sigle:'MINESEC',nom:'Ministère des Enseignements secondaires',cat:'Éducation & savoirs',int:'Collèges et lycées, BEPC, probatoire, baccalauréat, GCE.',ext:'Équivalences, examens internationaux.',poids:4,site:'minesec.gov.cm',statut:'gabarit commun'},
 {id:'minesup',sigle:'MINESUP',nom:'Ministère de l’Enseignement supérieur',cat:'Éducation & savoirs',int:'Universités d’État, bourses, LMD, recherche universitaire.',ext:'Mobilité étudiante, coopération universitaire, CAMES.',poids:4,site:'minesup.gov.cm',statut:'gabarit commun'},
 {id:'minefop',sigle:'MINEFOP',nom:'Ministère de l’Emploi et de la Formation professionnelle',cat:'Éducation & savoirs',int:'FNE, centres de formation, certification des compétences.',ext:'Partenariats de formation.',poids:3,site:'minefop.gov.cm',statut:'gabarit commun'},
 {id:'minresi',sigle:'MINRESI',nom:'Ministère de la Recherche scientifique et de l’Innovation',cat:'Éducation & savoirs',int:'Instituts de recherche (IRAD, IMPM, IRGM), innovation.',ext:'Coopération scientifique, publications.',poids:3,site:'minresi.gov.cm',statut:'gabarit commun'},
 {id:'mint',sigle:'MINT',nom:'Ministère des Transports',cat:'Territoire & infrastructures',int:'Permis de conduire, cartes grises, sécurité routière, aviation civile, ports, météo.',ext:'OACI, OMI, corridors CEMAC.',poids:4,site:'mint.gov.cm',statut:'gabarit commun'},
 {id:'mintp',sigle:'MINTP',nom:'Ministère des Travaux publics',cat:'Territoire & infrastructures',int:'Routes, ponts, entretien routier, autoroutes.',ext:'Financements d’infrastructures.',poids:4,site:'mintp.gov.cm',statut:'gabarit commun'},
 {id:'minhdu',sigle:'MINHDU',nom:'Ministère de l’Habitat et du Développement urbain',cat:'Territoire & infrastructures',int:'Permis de construire, logement social, urbanisme, assainissement.',ext:'ONU-Habitat.',poids:3,site:'minhdu.gov.cm',statut:'gabarit commun'},
 {id:'mindcaf',sigle:'MINDCAF',nom:'Ministère des Domaines, du Cadastre et des Affaires foncières',cat:'Territoire & infrastructures',int:'Titres fonciers, cadastre, domaine national.',ext:'—',poids:3,site:'mindcaf.gov.cm',statut:'gabarit commun'},
 {id:'minee',sigle:'MINEE',nom:'Ministère de l’Eau et de l’Énergie',cat:'Territoire & infrastructures',int:'Électricité (ENEO, barrages), eau potable (CAMWATER), hydrocarbures.',ext:'Interconnexions régionales, financements énergétiques.',poids:4,site:'minee.cm',statut:'gabarit commun'},
 {id:'minpostel',sigle:'MINPOSTEL',nom:'Ministère des Postes et Télécommunications',cat:'Territoire & infrastructures',int:'Télécoms, Identité Cameroun, ANTIC, CAMPOST, cybersécurité.',ext:'UIT, câbles sous-marins, coopération numérique.',poids:4,site:'minpostel.gov.cm',statut:'gabarit commun'},
 {id:'minader',sigle:'MINADER',nom:'Ministère de l’Agriculture et du Développement rural',cat:'Production & environnement',int:'Filières cacao-café, coton, vivrier ; coopératives ; intrants.',ext:'FAO, FIDA, exportations agricoles.',poids:4,site:'minader.cm',statut:'gabarit commun'},
 {id:'minepia',sigle:'MINEPIA',nom:'Ministère de l’Élevage, des Pêches et des Industries animales',cat:'Production & environnement',int:'Élevage, pêche, santé animale, abattoirs.',ext:'Normes sanitaires, exportations.',poids:3,site:'minepia.cm',statut:'gabarit commun'},
 {id:'minfof',sigle:'MINFOF',nom:'Ministère des Forêts et de la Faune',cat:'Production & environnement',int:'Permis forestiers, parcs nationaux, lutte contre le braconnage.',ext:'CITES, APV-FLEGT, bassin du Congo.',poids:3,site:'minfof.cm',statut:'gabarit commun'},
 {id:'minepded',sigle:'MINEPDED',nom:'Ministère de l’Environnement, de la Protection de la nature et du Développement durable',cat:'Production & environnement',int:'Études d’impact, déchets, climat, biodiversité.',ext:'Accord de Paris, COP, fonds climat.',poids:3,site:'minepded.gov.cm',statut:'gabarit commun'},
 {id:'minac',sigle:'MINAC',nom:'Ministère des Arts et de la Culture',cat:'Culture, jeunesse & communication',int:'Patrimoine, musées, droits d’auteur, industries culturelles, Musée numérique.',ext:'UNESCO, patrimoine mondial, diplomatie culturelle.',poids:4,site:'minac.gov.cm',statut:'livré',lien:'../musee/index.html'},
 {id:'minsep',sigle:'MINSEP',nom:'Ministère des Sports et de l’Éducation physique',cat:'Culture, jeunesse & communication',int:'Fédérations, stades, sport scolaire, licences.',ext:'CAN, JO, CIO, Lions indomptables.',poids:4,site:'minsep.gov.cm',statut:'livré',lien:'../sports/index.html'},
 {id:'mintoul',sigle:'MINTOUL',nom:'Ministère du Tourisme et des Loisirs',cat:'Culture, jeunesse & communication',int:'Sites, hôtels, agences, loisirs.',ext:'e-Visa touristique, promotion « Visiter le Cameroun ».',poids:3,site:'mintoul.gov.cm',statut:'livré',lien:'../../../ui_kits/tourisme/index.html'},
 {id:'minjec',sigle:'MINJEC',nom:'Ministère de la Jeunesse et de l’Éducation civique',cat:'Culture, jeunesse & communication',int:'Fête de la Jeunesse, PAJER-U, service civique, civisme.',ext:'Programmes jeunesse internationaux.',poids:3,site:'minjec.gov.cm',statut:'gabarit commun'},
 {id:'mincom',sigle:'MINCOM',nom:'Ministère de la Communication',cat:'Culture, jeunesse & communication',int:'Presse, CRTV, Cameroon Tribune, communication gouvernementale.',ext:'Image du pays, accréditations.',poids:3,site:'mincom.gov.cm',statut:'gabarit commun'}
];
// Compte citoyen — données de démonstration
const CITOYEN={nom:'Ngo Bassong Élise',initials:'EB',id:'CM-1987-0412-7731',ville:'Douala, Littoral',verif:'Identité vérifiée · niveau 2 (vérifié)',
 demarches:[{t:'Renouvellement de la carte nationale d’identité',min:'DGSN',ref:'CNI-2026-113-4482',statut:'En production',pct:70,maj:'il y a 2 jours',etapes:['Demande déposée','Empreintes prises','Production','Retrait au centre'],cur:3},{t:'Déclaration de revenus 2025',min:'MINFI — DGI',ref:'IRPP-2025-55-0193',statut:'Quittance disponible',pct:100,maj:'15 mars 2026',etapes:['Déclaration','Paiement','Quittance'],cur:3},{t:'Inscription à la Couverture santé universelle',min:'MINSANTE',ref:'CSU-2026-002-8815',statut:'Pièce attendue',pct:40,maj:'hier',etapes:['Demande','Pièces','Validation','Carte CSU'],cur:2,alerte:'Ajoutez un justificatif de domicile avant le 30 septembre.'}],
 documents:[{t:'Acte de naissance',ref:'BUNEC 1987/0412',date:'12 avr. 1987',type:'État civil',verif:true},{t:'Carte nationale d’identité',ref:'118 344 771',date:'expire le 4 nov. 2026',type:'Identité',verif:true,alerte:'Expire dans 45 jours'},{t:'Quittance IRPP 2025',ref:'Q-2026-0193',date:'15 mars 2026',type:'Fiscal',verif:true},{t:'Carnet de vaccination',ref:'MINSANTE',date:'mis à jour le 3 fév. 2026',type:'Santé',verif:true},{t:'Permis de conduire B',ref:'LT-2019-77120',date:'valide',type:'Transport',verif:true},{t:'Diplôme — Licence de droit',ref:'Université de Douala, 2009',date:'certifié',type:'Éducation',verif:true}],
 echeances:[{d:'30 sept. 2026',t:'Justificatif de domicile — CSU',min:'MINSANTE',urg:true},{d:'4 nov. 2026',t:'Expiration de la CNI',min:'DGSN',urg:true},{d:'15 mars 2027',t:'Déclaration de revenus 2026',min:'DGI'},{d:'juin 2027',t:'Rappel vaccinal — Amadou (6 ans)',min:'MINSANTE'}],
 famille:[{n:'Amadou Bassong',lien:'Enfant · 6 ans',docs:'Acte de naissance, carnet de vaccination, inscription CM1'},{n:'Sarah Bassong',lien:'Enfant · 2 ans',docs:'Acte de naissance, carnet de vaccination'},{n:'Marthe Ngo Bassong',lien:'Mère · 68 ans · ayant droit',docs:'Pension CNPS, carte CSU'}],
 sante:[['Groupe sanguin','O+'],['Médecin traitant','Dr Tchoumi, Hôpital Laquintinie'],['Dernier vaccin','Fièvre jaune · 3 fév. 2026'],['Couverture','CSU — en cours d’inscription']],
 notifications:[{t:'Votre quittance IRPP 2025 est disponible',min:'DGI',q:'15 mars',lu:false},{t:'Pièce manquante pour la CSU',min:'MINSANTE',q:'hier',lu:false},{t:'CNI : production lancée',min:'DGSN',q:'il y a 2 jours',lu:true},{t:'Résultats du CEP publiés',min:'MINEDUB',q:'12 juil.',lu:true}]};
const PRO={nom:'Sawa Agro-Industries SARL',initials:'SA',niu:'M012345678901Z',rccm:'RC/DLA/2014/B/1287',regime:'Réel simplifié',siege:'Zone industrielle de Bassa, Douala',effectif:24,mandataire:'Ngo Bassong Élise — gérante',
 obligations:[{t:'Déclaration mensuelle TVA — août 2026',min:'DGI',d:'15 sept. 2026',statut:'À déclarer',urg:true},{t:'Cotisations CNPS — 3e trimestre',min:'CNPS',d:'15 oct. 2026',statut:'À venir'},{t:'Acompte IS — 3e trimestre',min:'DGI',d:'15 oct. 2026',statut:'À venir'},{t:'Renouvellement agrément phytosanitaire',min:'MINADER',d:'31 déc. 2026',statut:'À venir'}],
 quittances:[['Q-2026-08-4471','TVA juillet 2026','1 842 500','15 août 2026'],['Q-2026-07-3390','TVA juin 2026','1 610 000','15 juil. 2026'],['Q-2026-07-0218','Acompte IS T2','2 250 000','15 juil. 2026'],['Q-2026-04-1105','Patente 2026','385 000','28 fév. 2026']],
 salaries:[['Mbella Joseph','Chef de production','CDI','à jour'],['Fotso Clarisse','Comptable','CDI','à jour'],['Abdoulaye Sali','Logistique','CDD','à jour'],['+ 21 salariés','','','à jour']],
 marches:[{t:'Fourniture de semences améliorées — MINADER',ref:'AONO 014/2026',d:'clôture 28 sept. 2026',statut:'Ouvert',montant:'120 M FCFA'},{t:'Restauration scolaire — Commune de Douala 3e',ref:'AONO 087/2026',d:'clôture 10 oct. 2026',statut:'Ouvert',montant:'45 M FCFA'},{t:'Intrants agricoles — Région du Littoral',ref:'AONO 003/2026',d:'attribué le 2 mai 2026',statut:'Attribué à Sawa Agro',montant:'62 M FCFA'}],
 licences:[['Agrément phytosanitaire','MINADER','valide → 31 déc. 2026'],['Licence import-export','MINCOMMERCE','valide → 2028'],['Certificat de conformité ANOR','MINMIDT','valide → mars 2027'],['Autorisation environnementale','MINEPDED','renouvellement en cours']],
 delegations:[{n:'Fotso Clarisse','role':'Comptable interne',droits:'Fiscalité (déclarer, payer), CNPS (déclarer)',depuis:'jan. 2024'},{n:'Cabinet Nkeng & Associés','role':'Expert-comptable',droits:'Fiscalité (déclarer), lecture des quittances',depuis:'mars 2026'}],
 douanes:[['DI-2026-DLA-77120','Import — engrais NPK, 40 t','Kribi','Dédouané','12 août 2026'],['DE-2026-DLA-00981','Export — cacao, 60 t','Douala','En transit','en cours'],['DI-2026-DLA-65502','Import — pièces machines','Douala','Dédouané','3 juil. 2026']]};
const VOTES=[{title:'Barre gouvernementale commune en haut de tous les sites',description:'Un seul bandeau ébène avec « Tous les sites », la recherche, l’accessibilité et Identité Cameroun.',category:'Navigation',votesFor:1284,votesAgainst:96,status:'adopté',author:'Équipe Cameroun numérique'},{title:'Version facile à lire (FALC) sur chaque démarche',description:'Un bouton dans le panneau d’accessibilité affiche une version courte, un message par paragraphe.',category:'Accessibilité',votesFor:942,votesAgainst:41,status:'ouvert',closesAt:'clôture le 30 sept.'},{title:'Musée numérique : ajouter une salle « Mémoires »',description:'Textes validés par un comité d’historiens, accès explicite, sources primaires.',category:'Contenu',votesFor:611,votesAgainst:238,status:'ouvert',closesAt:'clôture le 15 oct.'},{title:'Mode sombre par défaut la nuit',description:'Basculer automatiquement le contraste renforcé entre 19 h et 6 h.',category:'Apparence',votesFor:305,votesAgainst:412,status:'ouvert',closesAt:'clôture le 15 oct.'}];
Object.assign(window,{BESOINS,CAT_INST,INSTITUTIONS,CITOYEN,PRO,VOTES,RELAIS_DEF});
