const {Button,Card,Badge,Stat,Tag,Icon,Table,Breadcrumb,Accordion,Tabs,Stepper,Timeline,Field,Input,Select,Checkbox,Switch,Alert,Dialog,Toast,ToastStack}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
/* Identité Cameroun : identité numérique dédiée, 3 niveaux (déclaratif, vérifié, biométrique). */
const NIVEAUX=[['1','Déclaratif','E-mail ou téléphone vérifié','Consulter, s’informer, voter dans la communauté'],['2','Vérifié','CNI ou passeport + selfie vidéo','Démarches, documents, paiements'],['3','Biométrique','Empreintes au guichet ou via la CNI biométrique','Actes d’état civil, signature électronique qualifiée, mandats']];
function Identite({go}){
  return <>
    <section style={{background:'var(--cm-ebene)',color:'#fff',position:'relative',isolation:'isolate'}}><div aria-hidden="true" style={{position:'absolute',inset:0,background:'var(--motif-ndop)',opacity:.35,overflow:'hidden',zIndex:-1}}/>
      <Container style={{position:'relative',padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'center'}}>
        <div><Overline color="var(--cm-jaune-500)">Identité Cameroun</Overline><div aria-hidden="true" style={{width:48,height:1,background:OR,margin:'14px 0 0'}}/><h1 style={{font:'var(--type-display)',color:'#fff',fontSize:'clamp(2.25rem,5vw,3.5rem)',marginTop:14,letterSpacing:'var(--tracking-tight)'}}>Une identité numérique. Tous les sites de l’État.</h1><p style={{font:'var(--type-lead)',color:'var(--cm-gris-200)',maxWidth:'52ch',marginTop:14}}>Vous vous connectez une fois. Vos documents, vos démarches, vos échéances et vos réglages d’accessibilité vous suivent d’un ministère à l’autre, sans ressaisie.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:24}}><Button variant="inverse" iconLeft="fingerprint" onClick={()=>go('connexion')}>Me connecter</Button><Button variant="inverse" iconLeft="map-pin" onClick={()=>go('premiere')}>Première connexion : au relais</Button><Button variant="tertiary" style={{color:'#fff'}} iconRight="arrow-down" onClick={()=>{const el=document.getElementById('id-comptes');if(el)window.scrollTo({top:el.getBoundingClientRect().top+window.scrollY-90});}}>Les deux types de compte</Button></div></div>
        <div style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.2)',borderTop:'2px solid '+OR,padding:'var(--space-6)'}}><Overline color="var(--cm-jaune-500)">Carte d’identité numérique</Overline><div style={{marginTop:16,padding:'var(--space-5)',background:'linear-gradient(135deg,#0B1B33,#16325C)',border:'1px solid '+OR,display:'grid',gap:14,aspectRatio:'1.586',boxSizing:'border-box'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontFamily:'var(--font-display)',fontWeight:700,letterSpacing:'0.1em',textTransform:'uppercase',fontSize:12}}>République du Cameroun</span><Star size={16}/></div><div style={{display:'grid',gridTemplateColumns:'56px 1fr',gap:14,alignItems:'center'}}><span style={{width:56,height:56,background:'var(--cm-vert-500)',color:'var(--cm-ebene)',display:'grid',placeItems:'center',fontFamily:'var(--font-display)',fontWeight:800,fontSize:20}}>EB</span><div><div style={{font:'var(--type-h6)',color:'#fff'}}>NGO BASSONG Élise</div><div style={{fontFamily:'var(--font-mono)',fontSize:12,color:'var(--cm-gris-300)',marginTop:2}}>{CITOYEN.id}</div></div></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',font:'var(--type-caption)',color:'var(--cm-gris-300)'}}><span>Niveau 2 · vérifié · 2 appareils de confiance</span><span style={{display:'inline-flex',gap:3}}>{[1,2,3].map(n=><span key={n} style={{width:18,height:4,background:n<=2?OR:'rgba(255,255,255,.2)'}}/>)}</span></div></div></div>
      </Container></section>
    <Container style={{padding:'var(--space-16) var(--gutter)'}}>
      <SectionTitle overline="Comment ça marche" num={1}>Trois niveaux, selon ce que vous faites</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)'}}>{NIVEAUX.map(([n,t,c,u])=><article key={n} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-5)',display:'grid',gap:8}}><div style={{display:'flex',gap:10,alignItems:'center'}}><span style={{width:32,height:32,display:'grid',placeItems:'center',background:'var(--cm-ebene)',color:'var(--cm-jaune-500)',fontFamily:'var(--font-display)',fontWeight:800}}>{n}</span><h3 style={{font:'var(--type-h5)'}}>{t}</h3></div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>Preuve</div><p style={{font:'var(--type-body-sm)'}}>{c}</p><div style={{font:'var(--type-caption)',color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>Permet</div><p style={{font:'var(--type-body-sm)'}}>{u}</p></article>)}</div>
      <Ornement style={{margin:'var(--space-16) 0'}}/>
      <SectionTitle overline="Deux contextes" num={2} id="id-comptes">Un compte, deux contextes</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:'var(--space-6)'}}>
        <article style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)',padding:'var(--space-6)',display:'grid',gap:14}}><div style={{display:'flex',gap:12,alignItems:'center'}}><span style={{width:44,height:44,background:'var(--surface-brand-soft)',display:'grid',placeItems:'center'}}><Icon name="user" size={22} color="var(--cm-vert-800)"/></span><h3 style={{font:'var(--type-h4)'}}>Compte citoyen</h3></div><p style={{color:'var(--text-muted)'}}>Pour vous et votre famille. Toutes les démarches personnelles, quel que soit le ministère, dans une vue unique.</p><ul style={{margin:0,paddingLeft:18,lineHeight:'var(--leading-relaxed)',font:'var(--type-body-sm)'}}><li>Tableau de bord unifié (tous ministères)</li><li>Mes documents — coffre numérique certifié</li><li>Mes démarches en cours et leur suivi</li><li>Notifications et échéances</li><li>Famille : enfants, ayants droit</li><li>Santé : carnet, vaccins, couverture</li><li>Préférences d’accessibilité synchronisées</li></ul><Button iconRight="arrow-right" onClick={()=>go('connexion','citoyen')}>Ouvrir un compte citoyen</Button></article>
        <article style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-indigo-600)',padding:'var(--space-6)',display:'grid',gap:14}}><div style={{display:'flex',gap:12,alignItems:'center'}}><span style={{width:44,height:44,background:'var(--cm-indigo-50)',display:'grid',placeItems:'center'}}><Icon name="building-2" size={22} color="var(--cm-indigo-700)"/></span><h3 style={{font:'var(--type-h4)'}}>Compte professionnel</h3></div><p style={{color:'var(--text-muted)'}}>Pour votre entreprise, association ou exploitation. Rattaché à votre identité de citoyen ; vous passez de l’un à l’autre sans vous reconnecter.</p><ul style={{margin:0,paddingLeft:18,lineHeight:'var(--leading-relaxed)',font:'var(--type-body-sm)'}}><li>Fiscalité : NIU, déclarations, quittances</li><li>Salariés et CNPS</li><li>Marchés publics et appels d’offres</li><li>Licences, agréments, permis</li><li>Délégation d’accès : comptable, mandataire</li><li>Import / export : douanes</li></ul><Button variant="secondary" iconRight="arrow-right" onClick={()=>go('connexion','pro')}>Rattacher une entreprise</Button></article>
      </div>
      <Ornement style={{margin:'var(--space-16) 0'}}/>
      <SectionTitle overline="Sécurité par défaut" num={3}>Plus sûr et plus simple à la fois</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:'var(--space-4)',marginBottom:'var(--space-10)'}}>{[['key-round','Aucun mot de passe','Clés d’accès (FIDO2) liées à votre téléphone : empreinte ou visage. Rien à retenir, rien à voler par hameçonnage.'],['smartphone','Appareils de confiance','Vous voyez la liste de vos appareils et retirez l’un d’eux en un geste. Toute nouvelle connexion est notifiée.'],['scan-line','Code de session visible','Le même code court s’affiche sur l’ordinateur et le téléphone : vous confirmez ce que vous voyez, jamais une demande inconnue.'],['life-buoy','Récupération sans blocage','Téléphone perdu : 8 codes de secours imprimables, ou reprise au guichet avec la CNI en 10 minutes.'],['eye','Journal des accès','Chaque consultation de vos données par vous, un mandataire ou un agent est horodatée et consultable.'],['shield-check','Niveau selon l’acte','Consulter demande le niveau 1 ; payer, le niveau 2 ; signer un acte d’état civil, le niveau 3 biométrique.']].map(([ic,t,d])=><article key={t} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-5)',display:'grid',gridTemplateColumns:'36px 1fr',gap:12,alignItems:'start'}}><span style={{width:36,height:36,background:'var(--cm-ebene)',display:'grid',placeItems:'center'}}><Icon name={ic} size={18} color="var(--cm-jaune-500)"/></span><span><span style={{font:'var(--type-h6)',display:'block'}}>{t}</span><span style={{font:'var(--type-body-sm)',color:'var(--text-muted)',display:'block',marginTop:4}}>{d}</span></span></article>)}</div>
      <SectionTitle overline="Confiance" num={4}>Données et recours</SectionTitle>
      <Accordion items={[{id:'d',title:'Quelles données sont conservées ?',content:<p>Identité (nom, date de naissance, numéro CM), moyens de contact, préférences. Les documents restent chez le ministère émetteur ; le coffre n’en garde qu’une empreinte et un lien certifié. Vous voyez qui a consulté quoi, quand.</p>},{id:'p',title:'Qui peut accéder à mon compte ?',content:<p>Vous seul, et les personnes que vous mandatez explicitement (compte professionnel). Chaque accès d’un agent est journalisé et visible dans « Historique des accès ». Cadre : loi n° 2010/012 sur la cybersécurité et projet de loi sur la protection des données personnelles.</p>},{id:'s',title:'Comment me connecter en sécurité ?',content:<p>Par clé d’accès sur votre téléphone (empreinte ou visage). Le code SMS n’est qu’un dépannage. Le niveau 3 exige une vérification biométrique au guichet. Perte du téléphone : codes de secours ou guichet avec la CNI.</p>},{id:'a',title:'Et si je n’ai pas Internet ou de smartphone ?',content:<p>Les guichets Cameroun numérique de chaque chef-lieu et le 8100 permettent d’effectuer les mêmes démarches ; l’agent agit en votre nom, sous votre identité, et l’opération apparaît dans votre historique.</p>}]}/>
    </Container>
  </>;
}
/* Connexion : sans mot de passe. 1) identifiant (téléphone, e-mail ou numéro CM) 2) confirmation sur l'appareil de confiance (clé d'accès / empreinte, sinon code SMS) 3) contexte. Chaque connexion est notifiée et journalisée. */
function Connexion({go,setUser,type}){
  const [step,setStep]=React.useState(1);const [ctx,setCtx]=React.useState(type||'citoyen');const [id,setId]=React.useState('');const [mode,setMode]=React.useState('cle');const [code,setCode]=React.useState('');const [waiting,setWaiting]=React.useState(false);
  React.useEffect(()=>{if(step===2&&mode==='cle'){setWaiting(true);const t=setTimeout(()=>{setWaiting(false);setStep(3);},2200);return()=>clearTimeout(t);}},[step,mode]);
  const finish=()=>{setUser(ctx==='pro'?{nom:PRO.nom,initials:PRO.initials,type:'pro'}:{nom:CITOYEN.nom,initials:CITOYEN.initials,type:'citoyen'});go(ctx==='pro'?'pro':'citoyen');};
  const Opt=({v,icon,t,s})=><button type="button" role="radio" aria-checked={ctx===v} onClick={()=>setCtx(v)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'24px 1fr 20px',gap:12,alignItems:'center',padding:'var(--space-4)',border:'2px solid '+(ctx===v?'var(--cm-vert-800)':'var(--border-default)'),background:ctx===v?'var(--surface-brand-soft)':'transparent',textAlign:'left'}}><Icon name={icon} size={22} color={ctx===v?'var(--cm-vert-800)':'var(--text-muted)'}/><span><span style={{font:'var(--type-h6)',display:'block'}}>{t}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{s}</span></span>{ctx===v&&<Icon name="check" size={18} color="var(--cm-vert-800)"/>}</button>;
  return <Container style={{padding:'var(--space-12) var(--gutter) var(--space-20)',maxWidth:760}}>
    <div style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-ebene)'}}>
      <div style={{padding:'var(--space-6) var(--space-6) 0',display:'flex',gap:12,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><div style={{display:'flex',gap:12,alignItems:'center'}}><span style={{width:40,height:40,background:'var(--cm-ebene)',display:'grid',placeItems:'center'}}><Star size={18}/></span><div><h1 style={{font:'var(--type-h4)'}}>Identité Cameroun</h1><div style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>Connexion sans mot de passe · identite.gouv.cm</div></div></div><span style={{display:'inline-flex',gap:6,alignItems:'center',font:'var(--type-caption)',color:'var(--cm-vert-800)',fontWeight:600}}><Icon name="shield-check" size={14}/>Site officiel vérifié</span></div>
      <div style={{padding:'var(--space-6)'}}><Stepper steps={[{label:'Qui êtes-vous ?',hint:'téléphone, e-mail ou n° CM'},{label:'Confirmez',hint:'sur votre appareil'},{label:'Contexte',hint:'citoyen ou professionnel'}]} current={step}/></div>
      <div style={{padding:'0 var(--space-6) var(--space-6)',display:'grid',gap:'var(--space-5)'}}>
        {step===1&&<><Field label="Téléphone, e-mail ou numéro Identité Cameroun" hint="Un seul identifiant suffit ; aucun mot de passe à retenir." required htmlFor="id"><Input id="id" size="lg" value={id} onChange={e=>setId(e.target.value)} iconLeft="fingerprint" placeholder="6•• ••• ••• ou CM-…" autoComplete="username webauthn"/></Field><div style={{display:'flex',gap:12,justifyContent:'space-between',alignItems:'center',flexWrap:'wrap'}}><a href="#" onClick={e=>{e.preventDefault();go('premiere');}} style={{font:'var(--type-body-sm)'}}>Première connexion ? Pré-inscription et relais</a><Button size="lg" iconRight="arrow-right" onClick={()=>setStep(2)}>Continuer</Button></div></>}
        {step===2&&<>
          <div role="radiogroup" aria-label="Méthode de confirmation" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{[['cle','smartphone','Clé d’accès','Empreinte ou visage sur votre téléphone de confiance'],['sms','message-square','Code SMS','Au 6•• ••• •31 — moins sûr, en dépannage']].map(([v,ic,t,h])=><button key={v} type="button" role="radio" aria-checked={mode===v} onClick={()=>setMode(v)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gap:6,padding:'var(--space-4)',border:'2px solid '+(mode===v?'var(--cm-vert-800)':'var(--border-default)'),background:mode===v?'var(--surface-brand-soft)':'transparent',textAlign:'left'}}><Icon name={ic} size={20} color={mode===v?'var(--cm-vert-800)':'var(--text-muted)'}/><span style={{font:'var(--type-label)',fontWeight:700}}>{t}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{h}</span></button>)}</div>
          {mode==='cle'&&<div style={{padding:'var(--space-6)',border:'1px dashed var(--border-strong)',display:'grid',justifyItems:'center',gap:12,textAlign:'center'}}><span style={{width:56,height:56,borderRadius:'50%',border:'3px solid var(--cm-vert-800)',borderTopColor:'transparent',animation:waiting?'cmspin 1s linear infinite':'none',display:'grid',placeItems:'center'}}><Icon name="smartphone" size={22} color="var(--cm-vert-800)"/></span><div style={{font:'var(--type-h6)'}}>Confirmez sur votre téléphone</div><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',maxWidth:'40ch'}}>Une notification a été envoyée à <b>Samsung A54 — Élise</b>. Déverrouillez avec votre empreinte. Rien à recopier.</p><div style={{font:'var(--type-caption)',color:'var(--text-subtle)'}}>Code de session <span style={{fontFamily:'var(--font-mono)'}}>KR-72</span> — vérifiez qu’il s’affiche aussi sur le téléphone.</div><Button size="sm" variant="tertiary" onClick={()=>{setWaiting(false);setMode('sms');}}>Annuler · utiliser un code SMS</Button></div>}
          {mode==='sms'&&<><Field label="Code reçu par SMS" hint="Valable 5 minutes. L’État ne vous demandera jamais ce code par téléphone." required htmlFor="code"><Input id="code" size="lg" value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" placeholder="••••••" style={{fontFamily:'var(--font-mono)',letterSpacing:'0.3em'}}/></Field><div style={{display:'flex',gap:12,justifyContent:'space-between',flexWrap:'wrap'}}><Button variant="tertiary" onClick={()=>setStep(1)}>Retour</Button><Button size="lg" iconRight="arrow-right" onClick={()=>setStep(3)}>Vérifier</Button></div></>}
          <Checkbox label="Faire de cet appareil un appareil de confiance (30 jours)" hint="Vous serez averti·e à chaque nouvelle connexion, ici et par SMS."/>
        </>}
        {step===3&&<><p style={{color:'var(--text-muted)'}}>Bonjour <b style={{color:'var(--text-heading)'}}>Élise</b>. Dans quel contexte agissez-vous ? Vous changerez à tout moment depuis la barre gouvernementale, sans vous reconnecter.</p><div role="radiogroup" aria-label="Contexte" style={{display:'grid',gap:8}}><Opt v="citoyen" icon="user" t="Citoyenne" s={'Élise Ngo Bassong · '+CITOYEN.id+' · niveau 2 vérifié'}/><Opt v="pro" icon="building-2" t="Professionnel" s={PRO.nom+' · NIU '+PRO.niu+' · gérante'}/></div><div style={{display:'flex',gap:12,justifyContent:'space-between',flexWrap:'wrap'}}><Button variant="tertiary" onClick={()=>setStep(1)}>Ce n’est pas moi</Button><Button size="lg" iconRight="arrow-right" onClick={finish}>Ouvrir mon espace</Button></div></>}
      </div>
      <div style={{padding:'var(--space-4) var(--space-6)',borderTop:'var(--hairline)',font:'var(--type-caption)',color:'var(--text-muted)',display:'flex',gap:16,flexWrap:'wrap'}}><span style={{display:'inline-flex',gap:6,alignItems:'center'}}><Icon name="lock" size={12}/>Chiffré de bout en bout</span><a href="#">Téléphone perdu ?</a><a href="#">Guichets et 8100</a><a href="#">Signaler une fraude</a></div>
    </div>
    <style>{'@keyframes cmspin{to{transform:rotate(360deg)}}'}</style>
  </Container>;
}
/* Première connexion : pré-inscription en ligne, puis un passage physique unique au relais (mairie, commissariat, guichet, consulat) pour la vérification biométrique et la remise de la clé. */
const STANDARDS=[['NIST SP 800-63-4','Niveaux d’assurance d’identité (IAL) et d’authentification (AAL) : notre niveau 3 = IAL3 / AAL3.'],['ISO/IEC 29115 · eIDAS 2.0','Cadre d’assurance interopérable avec l’Union européenne et la CEDEAO (portefeuille d’identité).'],['FIDO2 / WebAuthn','Clés d’accès résistantes à l’hameçonnage ; aucun secret partagé côté serveur.'],['NIST FIPS 203 / 204 (post-quantique)','Chiffrement ML-KEM et signatures ML-DSA en mode hybride : les actes signés aujourd’hui resteront vérifiables après l’ère quantique.'],['Registre d’intégrité distribué','Chaque acte (délivrance, consultation, mandat) produit une empreinte horodatée ancrée dans un registre permissionné réparti entre institutions (Trésor, BUNEC, DGSN, ANTIC). Aucune donnée personnelle n’y est écrite : seulement des preuves.'],['ICAO 9303 · ISO/IEC 19794','Biométrie et documents de voyage : compatibilité avec la CNI et le passeport biométriques.'],['Loi n° 2010/012 · protection des données','Consentement, minimisation, droit d’accès et journal des accès pour le citoyen.']];
function PremiereConnexion({go}){
  const [step,setStep]=React.useState(1);
  const ETAPES=[{label:'Pré-inscription en ligne',hint:'5 min · téléphone'},{label:'Rendez-vous au relais',hint:'mairie, commissariat, guichet, consulat'},{label:'Vérification biométrique',hint:'10 min sur place'},{label:'Remise de la clé',hint:'activation sur votre téléphone'}];
  const contenu={1:<><p>Depuis n’importe quel téléphone : nom, date de naissance, numéro de CNI ou d’acte de naissance, numéro de téléphone. Vous recevez un <b>code de pré-inscription</b> <span style={{fontFamily:'var(--font-mono)'}}>P-4K7M-22</span> et la liste des relais proches avec leurs créneaux.</p><Alert status="info" size="sm" title="Sans smartphone ?">La pré-inscription se fait aussi par SMS au 8100 ou directement au relais.</Alert></>,
    2:<><p>Vous choisissez le relais : <b>mairie</b> (état civil connu), <b>commissariat ou brigade</b> (CNI, passeport), <b>guichet Cameroun numérique</b>, <b>consulat</b> à l’étranger. En zone rurale, la <b>chefferie</b> peut attester votre identité et votre résidence avant le passage à la mairie.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:8}}>{['mairie','commissariat','guichet','consulat','chefferie'].map(k=><button key={k} type="button" onClick={()=>go('relais',k)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'20px 1fr',gap:10,alignItems:'center',padding:'10px 12px',border:'var(--hairline)',background:'var(--surface-card)',font:'var(--type-body-sm)',fontWeight:600}}><Icon name={RELAIS_DEF[k].icon} size={16} color="var(--cm-vert-800)"/>{RELAIS_DEF[k].nom}</button>)}</div></>,
    3:<><p>L’agent lit votre code, vérifie la pièce d’identité et prend <b>empreintes et photo</b> (normes ICAO). Le dossier est comparé au fichier national de la DGSN et au BUNEC. Vous signez le consentement sur écran ; une copie vous est envoyée.</p><ul style={{margin:0,paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)'}}><li>Aucune photocopie, aucun frais : le passage est gratuit.</li><li>Personne à mobilité réduite : visite à domicile sur demande au 8100.</li><li>L’agent ne voit jamais votre clé ; il n’active que la remise.</li></ul></>,
    4:<><p>Sur place, votre téléphone crée la <b>clé d’accès</b> (empreinte ou visage) ; la partie publique est signée par l’État avec un certificat hybride post-quantique. Vous repartez avec vos <b>8 codes de secours</b> imprimés et l’identité active au niveau 3.</p><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)'}}>Pas de smartphone : une <b>carte Identité Cameroun</b> sans contact (même puce que la CNI) fait office de clé au guichet et sur les bornes.</p><Button iconRight="arrow-right" onClick={()=>go('connexion')}>J’ai déjà ma clé : me connecter</Button></>};
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Identité Cameroun" num={1}>Première connexion : un seul passage physique</SectionTitle>
    <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>La confiance se construit une fois, en personne. Ensuite, tout se fait depuis votre téléphone ; vous ne revenez au relais qu’en cas de perte.</p>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-8)',marginTop:'var(--space-8)',alignItems:'start'}}>
      <div style={{background:'var(--surface-card)',border:'var(--hairline)'}}>
        <div style={{padding:'var(--space-6)',borderBottom:'var(--hairline)'}}><Stepper steps={ETAPES} current={step}/></div>
        <div style={{padding:'var(--space-6)',display:'grid',gap:16,minHeight:220}}><h2 style={{font:'var(--type-h4)'}}>{step}. {ETAPES[step-1].label}</h2>{contenu[step]}</div>
        <div style={{padding:'var(--space-4) var(--space-6)',borderTop:'var(--hairline)',display:'flex',justifyContent:'space-between',gap:12}}><Button variant="tertiary" iconLeft="arrow-left" disabled={step===1} onClick={()=>setStep(step-1)}>Précédent</Button><Button variant={step===4?'secondary':'primary'} iconRight="arrow-right" disabled={step===4} onClick={()=>setStep(step+1)}>Suivant</Button></div>
      </div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-ebene)',color:'#fff',borderTop:'2px solid '+OR}}><Overline color="var(--cm-jaune-500)">Ce que vous apportez</Overline><ul style={{margin:'10px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)',color:'var(--cm-gris-200)'}}><li>CNI, passeport ou acte de naissance</li><li>Votre téléphone (ou rien : carte sans contact)</li><li>Le code de pré-inscription, ou votre numéro de téléphone</li></ul></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Durée et coût</Overline><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:10}}><Stat size="sm" value="10 min" label="sur place" accent="vert"/><Stat size="sm" value="0 FCFA" label="gratuit" accent="kola"/></div></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Mineurs et personnes protégées</Overline><p style={{font:'var(--type-body-sm)',marginTop:8,color:'var(--text-muted)'}}>Rattachés au compte d’un parent ou tuteur (niveau 3 exigé) ; ils reprennent la main à 18 ans avec un passage au relais.</p></div>
      </aside>
    </div>
    <Ornement style={{margin:'var(--space-16) 0'}}/>
    <SectionTitle overline="Normes" num={2}>Sécurité aux standards internationaux, et au-delà</SectionTitle>
    <div style={{display:'grid',gap:2}}>{STANDARDS.map(([n,d])=><div key={n} style={{display:'grid',gridTemplateColumns:'minmax(180px,260px) 1fr',gap:16,padding:'14px var(--space-5)',background:'var(--surface-card)',borderBottom:'var(--hairline)'}}><div style={{font:'var(--type-label)',fontWeight:700,fontFamily:'var(--font-mono)',fontSize:13}}>{n}</div><div style={{font:'var(--type-body-sm)'}}>{d}</div></div>)}</div>
    <div style={{marginTop:'var(--space-6)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)'}}>{[['Ce que le citoyen voit','Un geste : déverrouiller son téléphone. Un code court identique des deux côtés. Une notification à chaque accès.'],['Ce que l’État garantit','Preuves d’intégrité ancrées et réparties, cryptographie hybride post-quantique, aucune donnée personnelle dans le registre, audit indépendant annuel publié.'],['Ce qui reste hors ligne','La biométrie brute ne quitte jamais le relais ; seul un gabarit chiffré est conservé, révocable à votre demande.']].map(([t,d])=><div key={t} style={{padding:'var(--space-5)',border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)',background:'var(--surface-card)'}}><div style={{font:'var(--type-h6)'}}>{t}</div><p style={{font:'var(--type-body-sm)',marginTop:8,color:'var(--text-muted)'}}>{d}</p></div>)}</div>
  </Container>;
}
Object.assign(window,{Identite,Connexion,PremiereConnexion,NIVEAUX,STANDARDS});
