const {Button,Badge,Stat,Tag,Icon,Table,Breadcrumb,Accordion,Timeline,Field,Input,Select,Textarea,Alert,SearchBar}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
const SITE={id:'presidence',get nom(){return tr('Présidence de la République','Presidency of the Republic');},get tagline(){return tr('Palais de l’Unité — Yaoundé','Unity Palace — Yaoundé');},get nav(){return [{value:'accueil',label:tr('Accueil','Home')},{value:'institution',label:tr('L’institution','The institution')},{value:'actes',label:tr('Actes & communiqués','Acts & releases')},{value:'services',label:tr('Écrire, visiter, distinctions','Write, visit, honours')}];},get footer(){return tr('Site officiel de la Présidence de la République du Cameroun. Textes, communiqués et actes du Chef de l’État ; distinctions nationales ; courrier au Palais de l’Unité.','Official site of the Presidency of the Republic of Cameroon. Texts, releases and acts of the Head of State; national honours; mail to the Unity Palace.');},activeOf:p=>p};
const ACTES=[{d:'18 sept. 2026',type:'Décret',n:'2026/412',t:'Portant nomination de responsables au ministère de la Santé publique',th:'Nominations'},{d:'12 sept. 2026',type:'Communiqué',n:'',t:'Audience accordée à l’ambassadeur du Japon',th:'Diplomatie'},{d:'5 sept. 2026',type:'Décret',n:'2026/398',t:'Portant ratification de l’accord de financement du corridor Douala–N’Djamena',th:'Économie'},{d:'20 mai 2026',type:'Discours',n:'',t:'Message à la Nation à l’occasion de la fête nationale',th:'Fête nationale'},{d:'10 fév. 2026',type:'Discours',n:'',t:'Message à la jeunesse (11 février)',th:'Jeunesse'},{d:'31 déc. 2025',type:'Discours',n:'',t:'Message de fin d’année à la Nation',th:'Nation'},{d:'15 déc. 2025',type:'Décret',n:'2025/611',t:'Portant promotion dans les ordres nationaux',th:'Distinctions'},{d:'2 déc. 2025',type:'Décret',n:'2025/588',t:'Portant convocation du corps électoral (élections régionales)',th:'Institutions'}];
const INSTIT=[['Constitution du 18 janvier 1996','Loi n° 96/06 révisée par la loi n° 2008/001 : État unitaire décentralisé ; le Président de la République est élu pour sept ans au suffrage universel direct.'],['Le Président de la République','Chef de l’État, chef des armées, garant de l’indépendance nationale, de l’intégrité du territoire et du respect de la Constitution (art. 5). Il nomme le Premier ministre et, sur proposition de celui-ci, les membres du gouvernement.'],['Les services de la Présidence','Secrétariat général, Cabinet civil, État-major particulier, Direction du Protocole d’État, Contrôle supérieur de l’État, Délégation générale à la Sûreté nationale (rattachée).'],['Le Palais de l’Unité','Siège de la Présidence à Etoudi (Yaoundé), inauguré en 1982 ; lieu des audiences, des conseils ministériels et des cérémonies de prestation de serment.'],['Institutions liées','Premier ministre et gouvernement · Assemblée nationale et Sénat · Conseil constitutionnel · Cour suprême · Conseil économique et social · Conseil supérieur de la magistrature.']];
const ORDRES=[['Ordre de la Valeur','1957','Grand-croix, grand officier, commandeur, officier, chevalier','Services éminents rendus à la Nation'],['Ordre du Mérite camerounais','1972','Commandeur, officier, chevalier','Mérites distingués dans une activité publique ou privée'],['Médaille de la Vaillance','','Or, argent, bronze','Actes de courage'],['Médaille des Forces armées','','—','Services militaires']];
function Accueil({go}){
  return <>
    <Hero overline={tr('République du Cameroun · Présidence','Republic of Cameroon · Presidency')} title={tr('Le Palais de l’Unité, au service de la Nation','The Unity Palace, at the service of the Nation')} lead={tr('Textes, actes et communiqués du Chef de l’État ; l’institution et ses missions ; distinctions nationales ; courrier et visites.','Texts, acts and releases of the Head of State; the institution and its missions; national honours; mail and visits.')} actions={<><Button variant="inverse" iconRight="arrow-right" onClick={()=>go('actes')}>Derniers actes et communiqués</Button><Button variant="tertiary" style={{color:'#fff'}} iconRight="arrow-right" onClick={()=>go('institution')}>L’institution</Button></>}
      aside={<><Overline color="var(--cm-jaune-500)">Dernier message à la Nation</Overline><div style={{font:'var(--type-h5)',color:'#fff'}}>Message à la Nation — fête nationale du 20 mai 2026</div><p style={{font:'var(--type-body-sm)',color:'var(--cm-gris-300)'}}>Texte intégral en français et en anglais, version audio et facile à lire.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Button size="sm" variant="inverse" iconLeft="file-text" onClick={()=>go('actes')}>Lire</Button><Button size="sm" variant="tertiary" style={{color:'#fff'}} iconLeft="headphones">Écouter</Button></div></>}/>
    <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',borderTop:'2px solid '+OR}}><Container style={{padding:'var(--space-8) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-6)'}}><Stat size="sm" value="1996" label="Constitution en vigueur" detail="révisée en 2008" accent="vert"/><Stat size="sm" value="7 ans" label="mandat présidentiel" detail="suffrage universel direct" accent="kola"/><Stat size="sm" value={ACTES.filter(a=>a.type==='Décret').length} label="décrets publiés" detail="90 derniers jours" accent="indigo"/><Stat size="sm" value="2" label="ordres nationaux" detail="Valeur · Mérite" accent="laterite"/></Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'start'}}>
      <div><SectionTitle overline="Actualité officielle" num={1} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('actes')}>Tous les actes</Button>}>Actes et communiqués récents</SectionTitle><div style={{display:'grid',gap:2}}>{ACTES.slice(0,5).map((a,i)=><Row key={i} title={a.t} meta={a.type+(a.n?' n° '+a.n:'')+' · '+a.th} right={a.d} onClick={()=>go('actes',a.type)} style={{background:'var(--surface-card)'}}/>)}</div></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Agenda public</Overline><Timeline style={{marginTop:10}} items={[{title:'Conseil ministériel',when:'25 sept.',status:'todo'},{title:'Audience — présidente de la Commission de l’UA',when:'28 sept.',status:'todo'},{title:'Réunification — commémoration',when:'1er oct.',status:'todo'}]}/></div><div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Services</Overline><div style={{display:'grid',gap:2,marginTop:8}}>{[['mail','Écrire au Chef de l’État'],['award','Proposer une distinction'],['landmark','Visiter le Palais de l’Unité']].map(([ic,t])=><Row key={t} icon={ic} title={t} onClick={()=>go('services')} style={{padding:'8px 0'}}/>)}</div></div></aside>
    </Container></section>
    <section style={{background:'var(--surface-card)',borderTop:'var(--hairline)'}}><Container style={{padding:'var(--space-16) var(--gutter)'}}><SectionTitle overline="Institution" num={2} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('institution')}>En savoir plus</Button>}>La Présidence en cinq repères</SectionTitle><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)'}}>{INSTIT.map(([t,d],i)=><article key={t} style={{padding:'var(--space-5)',border:'var(--hairline)',borderTop:'4px solid '+['var(--cm-vert-800)','var(--cm-rouge-600)','var(--cm-jaune-600)','var(--cm-indigo-600)','var(--cm-kola-600)'][i],background:'var(--surface-page)'}}><h3 style={{font:'var(--type-h6)'}}>{t}</h3><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:8}}>{d}</p></article>)}</div></Container></section>
  </>;
}
function Institution(){
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="L’institution" num={1}>La Présidence de la République</SectionTitle>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}>
      <div><Photo ratio="16/7" placeholder="Palais de l’Unité — photographie officielle à fournir (Cabinet civil)"/><div style={{display:'grid',gap:2,marginTop:'var(--space-8)'}}>{INSTIT.map(([t,d])=><div key={t} style={{display:'grid',gridTemplateColumns:'minmax(160px,220px) 1fr',gap:16,padding:'14px 0',borderBottom:'var(--hairline)'}}><div style={{font:'var(--type-label)',fontWeight:700}}>{t}</div><div style={{font:'var(--type-body-sm)'}}>{d}</div></div>)}</div>
        <Ornement style={{margin:'var(--space-12) 0'}}/><SectionTitle overline="Chef de l’État" num={2}>Le Président de la République</SectionTitle><div style={{display:'grid',gridTemplateColumns:'160px 1fr',gap:'var(--space-6)',alignItems:'start'}}><Photo ratio="4/5" placeholder="Portrait officiel à fournir"/><div><h3 style={{font:'var(--type-h4)'}}>Paul Biya</h3><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:4}}>Président de la République depuis le 6 novembre 1982</p><p style={{marginTop:12}}>Né le 13 février 1933 à Mvomeka’a (Sud). Diplômé de l’Institut d’études politiques de Paris et de l’Institut des hautes études d’outre-mer. Secrétaire général de la Présidence (1968), Premier ministre (1975), il succède à Ahmadou Ahidjo le 6 novembre 1982. Auteur de <i>Pour le libéralisme communautaire</i> (1987).</p><p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:8}}>Source : biographie officielle, Présidence de la République.</p></div></div></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-ebene)',color:'#fff',borderTop:'2px solid '+OR}}><Overline color="var(--cm-jaune-500)">Textes fondamentaux</Overline><div style={{display:'grid',gap:2,marginTop:8}}>{['Constitution (1996, rév. 2008) — FR / EN','Décret d’organisation de la Présidence','Décret d’organisation du gouvernement','Loi sur les ordres nationaux'].map(t=><a key={t} href="#" style={{display:'flex',justifyContent:'space-between',gap:8,padding:'10px 0',borderBottom:'1px solid var(--cm-gris-800)',color:'#fff',textDecoration:'none',font:'var(--type-body-sm)'}}>{t}<Icon name="download" size={14}/></a>)}</div></div><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Symboles</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Drapeau, armoiries, hymne et devise sont présentés au <a href={LINKS.musee}>Musée numérique du Cameroun</a>.</p></div></aside>
    </div>
  </Container>;
}
function Actes({go,filtre}){
  const [t,setT]=React.useState(filtre||'Tous');const [q,setQ]=React.useState('');
  const list=ACTES.filter(a=>(t==='Tous'||a.type===t)&&(!q||(a.t+' '+a.th+' '+a.n).toLowerCase().includes(q.toLowerCase())));
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Journal officiel de la Présidence" num={1} action={<Button variant="secondary" iconLeft="rss">S’abonner</Button>}>Actes, décrets, discours, communiqués</SectionTitle>
    <SearchBar value={q} onChange={setQ} onSubmit={()=>{}} placeholder="Rechercher un décret, un thème, une date" label="Rechercher" style={{maxWidth:520}}/>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:12}}>{['Tous','Décret','Communiqué','Discours'].map(x=><Tag key={x} selected={t===x} onClick={()=>setT(x)}>{x}{x!=='Tous'&&<span style={{color:'var(--text-subtle)',marginLeft:6}}>{ACTES.filter(a=>a.type===x).length}</span>}</Tag>)}</div>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:14}} aria-live="polite">{list.length} document{list.length>1?'s':''}</p>
    <Table style={{marginTop:12}} caption="Actes publiés" columns={[{key:'d',label:'Date',mono:true},{key:'type',label:'Type',render:(v,r)=><Badge status={v==='Décret'?'brand':v==='Discours'?'info':'neutral'} size="sm">{v}{r.n?' '+r.n:''}</Badge>},{key:'t',label:'Objet',strong:true},{key:'th',label:'Thème'},{key:'x',label:'',align:'right',render:()=><span style={{display:'inline-flex',gap:4}}><Button size="sm" variant="tertiary" iconLeft="file-text">FR</Button><Button size="sm" variant="tertiary" iconLeft="file-text">EN</Button></span>}]} rows={list}/>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:16,maxWidth:'70ch'}}>Les textes font foi dans leur version publiée au Journal officiel (SOPECAM). Chaque document porte une empreinte d’intégrité vérifiable.</p>
  </Container>;
}
function Services(){
  const [tab,setTab]=React.useState('ecrire');
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Services" num={1}>Écrire, visiter, distinctions</SectionTitle>
    <div role="tablist" style={{display:'inline-flex',border:'1px solid var(--border-default)',background:'var(--surface-card)',marginBottom:'var(--space-8)',flexWrap:'wrap'}}>{[['ecrire','Écrire au Chef de l’État'],['distinctions','Ordres nationaux'],['visiter','Visiter le Palais']].map(([v,l])=><button key={v} type="button" role="tab" aria-selected={tab===v} onClick={()=>setTab(v)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',minHeight:44,padding:'0 16px',font:'var(--type-label)',fontWeight:600,background:tab===v?'var(--cm-vert-800)':'transparent',color:tab===v?'#fff':'var(--text-body)'}}>{l}</button>)}</div>
    {tab==='ecrire'&&<div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}><div style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-6)',display:'grid',gap:'var(--space-5)'}}><Alert status="info" size="sm" title="Courrier officiel">Le courrier est enregistré par le Cabinet civil et reçoit un numéro de suivi sous 48 h. Il est transmis au service compétent ; une réponse est apportée sous 60 jours.</Alert><Field label="Objet" required htmlFor="obj"><Select id="obj" options={['Requête','Doléance','Félicitations et vœux','Proposition','Demande d’audience','Autre']}/></Field><Field label="Votre message" required htmlFor="msg" hint="Identité pré-remplie depuis Identité Cameroun."><Textarea id="msg" rows={6} placeholder="Monsieur le Président de la République, …"/></Field><div style={{display:'flex',justifyContent:'flex-end'}}><Button iconRight="send">Envoyer le courrier</Button></div></div><aside style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Par voie postale</Overline><p style={{font:'var(--type-body-sm)',marginTop:8,lineHeight:'var(--leading-relaxed)'}}>Cabinet civil de la Présidence de la République<br/>Palais de l’Unité, Etoudi<br/>B.P. 100 Yaoundé — Cameroun</p></aside></div>}
    {tab==='distinctions'&&<><Table caption="Ordres et médailles nationaux" columns={[{key:'0',label:'Ordre',strong:true},{key:'1',label:'Création',mono:true},{key:'2',label:'Grades'},{key:'3',label:'Récompense'}]} rows={ORDRES}/><div style={{marginTop:'var(--space-8)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)'}}>{[['Proposer une personne','Les propositions émanent des ministères, des collectivités et des corps constitués ; un formulaire de saisine est réservé aux ordonnateurs.'],['Vérifier une décoration','Chaque décret de promotion est publié ; recherchez un nom dans les actes.'],['Calendrier','Promotions à l’occasion du 20 mai et du 1er janvier.']].map(([t,d])=><div key={t} style={{padding:'var(--space-5)',border:'var(--hairline)',background:'var(--surface-card)'}}><h3 style={{font:'var(--type-h6)'}}>{t}</h3><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:8}}>{d}</p></div>)}</div></>}
    {tab==='visiter'&&<div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}><div><Photo ratio="16/7" placeholder="Palais de l’Unité — vue extérieure à fournir"/><Accordion style={{marginTop:'var(--space-6)'}} items={[{id:'g',title:'Visites de groupes scolaires et universitaires',content:<p>Sur demande écrite de l’établissement, trois mois à l’avance ; groupes de 20 à 40 ; parcours d’une heure (salle des audiences, galerie des portraits, jardins).</p>},{id:'j',title:'Journées portes ouvertes',content:<p>Le 20 mai et lors des commémorations de la Réunification, inscription en ligne avec Identité Cameroun.</p>},{id:'p',title:'Presse et protocole',content:<p>Accréditations auprès de la Direction du Protocole d’État et de la Cellule de communication.</p>}]}/></div><aside style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Demande de visite</Overline><div style={{display:'grid',gap:12,marginTop:10}}><Field label="Établissement ou organisation" htmlFor="org"><Input id="org"/></Field><Field label="Effectif" htmlFor="n"><Input id="n" inputMode="numeric"/></Field><Field label="Période souhaitée" htmlFor="per"><Input id="per" type="month"/></Field><Button iconRight="send">Envoyer la demande</Button></div></aside></div>}
  </Container>;
}
Object.assign(window,{SITE,Accueil,Institution,Actes,Services});
