const {Button,Card,Badge,Stat,SearchBar,Tag,Icon}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
function Accueil({go,falc}){
  const [q,setQ]=React.useState('');
  const ess=FRISE.filter(e=>e.niv===1);
  const now=new Date();const jour=FRISE.find(e=>e.an>0&&(e.an+e.t.length)%FRISE.length===now.getDate()%FRISE.length)||FRISE[20];
  return <>
    <section style={{background:'var(--cm-ebene)',color:'#fff',position:'relative',isolation:'isolate'}}>
      <div aria-hidden="true" style={{position:'absolute',inset:0,background:'url('+IMG.palais+') center/cover',opacity:.3,zIndex:-2}}/>
      <div aria-hidden="true" style={{position:'absolute',inset:0,background:'linear-gradient(90deg,rgba(21,17,14,.96) 0%,rgba(21,17,14,.78) 55%,rgba(21,17,14,.4))',zIndex:-1}}/>
      <Container style={{position:'relative',padding:'var(--space-20) var(--gutter) var(--space-16)'}}>
        <div style={{maxWidth:780}}>
          <Overline color="var(--cm-jaune-500)">Musée numérique du Cameroun · Digital Museum of Cameroon</Overline><div aria-hidden="true" style={{width:48,height:1,background:OR,margin:'14px 0 0'}}/>
          <h1 style={{font:'var(--type-display)',color:'#fff',fontSize:'clamp(2.5rem,6vw,4.25rem)',marginTop:12,letterSpacing:'var(--tracking-tight)'}}>{falc?tr('L’histoire du Cameroun, racontée simplement.','Cameroon’s history, told simply.'):tr('Une histoire, deux cent cinquante voix.','One history, two hundred and fifty voices.')}</h1>
          <p style={{font:'var(--type-lead)',color:'var(--cm-gris-200)',maxWidth:'54ch',marginTop:16}}>{falc?'Ici, vous découvrez le passé du pays. Les dates, les personnes, les lieux. Chaque texte est court. Chaque information vient d’un livre ou d’une archive.':'Des abris de Shum Laka aux stades de la CAN 2022, le récit du pays à partir des écrits, des archives et des documentaires. Chaque repère cite sa source ; chaque page se lit en dix minutes ou en une heure.'}</p>
          <blockquote style={{margin:'28px 0 0',paddingLeft:16,borderLeft:'2px solid '+OR,maxWidth:'46ch'}}><p style={{fontFamily:'var(--font-display)',fontWeight:500,fontSize:'var(--text-lg)',color:'var(--cm-papier)',fontStyle:'italic',lineHeight:1.4}}>« Ô Cameroun, berceau de nos ancêtres, va debout et jaloux de ta liberté. »</p><footer style={{font:'var(--type-caption)',color:'var(--cm-gris-300)',marginTop:6,letterSpacing:'0.06em',textTransform:'uppercase'}}>Hymne national · Foulassi, 1928</footer></blockquote><RechercheGlobale placeholder="ex. réunification, Njoya, Nyos, makossa, Bakassi" label="Rechercher dans le musée et sur les sites de l’État" onSubmit={q=>go('frise',null,null,q)} style={{marginTop:32,maxWidth:640}}/>
          <div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:16,alignItems:'center'}}><span style={{font:'var(--type-body-sm)',color:'var(--cm-gris-300)'}}>Entrées :</span>{NAVF().slice(1).map(n=><Tag key={n.value} size="sm" onClick={()=>go(n.value)} style={{background:'transparent',color:'#fff',borderColor:'var(--cm-gris-500)'}}>{n.label}</Tag>)}</div>
        </div>
        <div style={{position:'absolute',right:24,bottom:12,font:'var(--type-caption)',color:'var(--cm-gris-300)',fontWeight:500}}>© {CREDIT.palais} — Palais des rois Bamoun, Foumban</div>
      </Container>
    </section>
    <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',borderTop:'2px solid '+OR}}><Container style={{padding:'var(--space-8) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-6)'}}>
      <Stat size="sm" value={FRISE.length} label="repères datés" detail="de −30 000 à 2025" accent="kola"/><Stat size="sm" value={PERSONNAGES.length} label="personnages" accent="laterite"/><Stat size="sm" value={MONUMENTS.length} label="monuments & lieux" accent="indigo"/><Stat size="sm" value="10" label="régions" detail="4 aires culturelles" accent="vert"/><Stat size="sm" value={CULTURE.glossaire.length} label="mots du glossaire" accent="neutre"/><Stat size="sm" value={SOURCES.length} label="sources citées" accent="neutre"/>
    </Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)'}}>
      <SectionTitle overline="Six époques" num={1} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('frise')}>Ouvrir la frise complète</Button>}>Parcourir par époque</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))',gap:'var(--space-4)'}}>{EPOQUES.map(e=>{const n=FRISE.filter(x=>x.ep===e.id).length;return <button key={e.id} type="button" onClick={()=>go('frise',e.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateRows:'auto auto 1fr auto',gap:8,padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid '+e.color,textAlign:'left',minHeight:180}}><div style={{font:'var(--type-mono)',fontSize:12,color:'var(--text-muted)',fontVariantNumeric:'tabular-nums'}}>{fmtAn(e.de)} → {e.a}</div><div style={{font:'var(--type-h5)',color:'var(--text-heading)'}}>{e.nom}<span style={{display:'block',font:'var(--type-caption)',fontWeight:500,color:'var(--text-subtle)',marginTop:2}}>{e.en}</span></div><div style={{font:'var(--type-body-sm)',color:'var(--text-muted)'}}>{e.resume}</div><div style={{font:'var(--type-caption)',color:e.color,fontWeight:600,display:'flex',alignItems:'center',gap:6}}>{n} repères <Icon name="arrow-right" size={14}/></div></button>;})}</div>
    </Container></section>
    <section style={{background:'var(--surface-card)',borderTop:'var(--hairline)',borderBottom:'var(--hairline)'}}><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-12)',alignItems:'start'}}>
      <div><SectionTitle overline="L’essentiel en dix minutes" num={2}>{ess.length} repères pour comprendre le pays</SectionTitle>
      <ol style={{margin:0,padding:0,listStyle:'none',display:'grid',gap:2}}>{ess.map((e,i)=>{const ep=epOf(e.ep);return <li key={i}><button type="button" onClick={()=>go('frise',e.ep,e.an+e.t)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'12px 88px 1fr auto',gap:14,width:'100%',padding:'10px 12px',borderBottom:'var(--hairline)',alignItems:'center',textAlign:'left'}}><Marker type={e.type} nat={e.nat} color={ep.color}/><span style={{font:'var(--type-mono)',fontWeight:500,color:ep.color,fontVariantNumeric:'tabular-nums'}}>{fmtAn(e.an)}</span><span style={{font:'var(--type-label)',fontWeight:600,color:'var(--text-heading)'}}>{e.t}</span><Icon name="chevron-right" size={16} color="var(--text-subtle)"/></button></li>;})}</ol></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}>
        <div style={{border:'var(--hairline)',borderTop:'4px solid var(--cm-jaune-500)',padding:'var(--space-5)',background:'var(--surface-page)'}}><Overline>Le repère du jour</Overline><div style={{font:'var(--type-mono)',color:epOf(jour.ep).color,marginTop:10}}>{fmtAn(jour.an)}</div><h3 style={{font:'var(--type-h5)',marginTop:4}}>{jour.t}</h3><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:8}}>{jour.d}</p><Button size="sm" variant="tertiary" iconRight="arrow-right" onClick={()=>go('frise',jour.ep,jour.an+jour.t)} style={{marginTop:8}}>Lire dans la frise</Button></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Comment lire le musée</Overline><ul style={{margin:'10px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)'}}><li><b>Essentiel</b> : {ess.length} repères, dix minutes.</li><li><b>Approfondi</b> : {FRISE.filter(e=>e.niv<=2).length} repères, une heure.</li><li><b>Complet</b> : {FRISE.length} repères, toutes les sources.</li></ul></div>
      </aside>
    </Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:'var(--space-12)'}}>
      <div><SectionTitle overline="Personnages" num={3}>Celles et ceux qui ont fait le pays</SectionTitle><div style={{display:'grid',gap:2}}>{PERSONNAGES.filter(p=>['manga-bell','njoya','um-nyobe','ahidjo','foncha','dibango','mbango','beti'].includes(p.id)).map(p=><button key={p.id} type="button" onClick={()=>go('personnage',p.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'48px 1fr auto',gap:14,padding:'10px 0',borderBottom:'var(--hairline)',alignItems:'center',textAlign:'left'}}><Portrait p={p} ratio="1/1" style={{width:48}}/><span><span style={{font:'var(--type-label)',fontWeight:600,color:'var(--text-heading)',display:'block'}}>{p.nom}</span><span style={{font:'var(--type-caption)',fontWeight:500,color:'var(--text-muted)'}}>{p.role} · {p.dates}</span></span><Icon name="chevron-right" size={16} color="var(--text-subtle)"/></button>)}</div><div style={{marginTop:16}}><Button variant="secondary" iconRight="arrow-right" onClick={()=>go('personnages')}>Les {PERSONNAGES.length} personnages</Button></div></div>
      <div><SectionTitle overline="Monuments & lieux" num={4}>Pierres, terre et mémoire</SectionTitle><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'var(--space-3)'}}>{MONUMENTS.filter(m=>srcOf(m)).slice(0,4).map(m=><button key={m.id} type="button" onClick={()=>go('monument',m.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'block',textAlign:'left',border:'var(--hairline)',background:'var(--surface-card)'}}><Photo src={srcOf(m,700)} credit={creditOf(m)} ratio="4/3" title={m.nom}/><div style={{padding:'10px 12px',font:'var(--type-caption)',color:'var(--text-muted)',display:'flex',justifyContent:'space-between',gap:8}}><span>{m.lieu}</span><span style={{fontFamily:'var(--font-mono)'}}>{m.an}</span></div></button>)}</div><div style={{marginTop:16}}><Button variant="secondary" iconRight="arrow-right" onClick={()=>go('monuments')}>Les {MONUMENTS.length} monuments et lieux</Button></div></div>
    </Container></section>
    <section style={{background:'var(--motif-ndop)',color:'#fff'}}><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-8)',alignItems:'start'}}>
      <div><Overline color="var(--cm-jaune-500)" num={5}>Régions & peuples</Overline><h2 style={{font:'var(--type-h2)',color:'#fff',marginTop:8}}>Dix régions, quatre aires culturelles, une nation</h2><p style={{color:'var(--cm-indigo-100)',marginTop:12,maxWidth:'48ch'}}>Côte sawa, forêt fang-beti, hauts plateaux des Grassfields, Grand Nord soudano-sahélien : la carte des peuples, des langues, des fêtes et des chefs-lieux.</p><div style={{marginTop:20}}><Button variant="inverse" iconLeft="map" onClick={()=>go('regions')}>Ouvrir la carte</Button></div></div>
      <div style={{display:'grid',gap:8}}>{AIRES.map(a=><button key={a.id} type="button" onClick={()=>go('regions',a.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'12px 1fr',gap:12,alignItems:'start',padding:'12px 14px',background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.22)',textAlign:'left'}}><span style={{width:12,height:12,background:a.color,marginTop:4,border:'2px solid #fff',boxSizing:'border-box'}}/><span><span style={{font:'var(--type-label)',fontWeight:600,color:'#fff',display:'block'}}>{a.nom}</span><span style={{font:'var(--type-caption)',fontWeight:500,color:'var(--cm-indigo-100)'}}>{a.peuples}</span></span></button>)}</div>
    </Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:'var(--space-12)'}}>
      <div><SectionTitle overline="Culture vivante" num={6}>Musiques, cuisine, lettres</SectionTitle><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{CULTURE.musiques.slice(0,5).map(m=><Tag key={m[0]} onClick={()=>go('culture','musiques')}>{m[0]}</Tag>)}{CULTURE.cuisine.slice(0,4).map(m=><Tag key={m[0]} onClick={()=>go('culture','cuisine')}>{m[0]}</Tag>)}</div><div style={{marginTop:16}}><Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('culture')}>Culture vivante et glossaire</Button></div></div>
      <div><SectionTitle overline="Symboles & valeurs" num={7}>Ce qui nous rassemble</SectionTitle><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{VALEURS.map(v=><Tag key={v.id} onClick={()=>go('symboles',v.id)}>{v.nom}</Tag>)}</div><p style={{color:'var(--text-muted)',marginTop:16,maxWidth:'50ch',font:'var(--type-body-sm)'}}>Drapeau, armoiries, hymne, devise, langues, ordres nationaux ; les six valeurs qui traversent le récit.</p><div style={{marginTop:16}}><Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('symboles')}>Symboles et valeurs</Button></div></div>
      <div><SectionTitle overline="Célébrations" num={8}>Le calendrier de la nation</SectionTitle><div style={{border:'var(--hairline)',background:'var(--surface-card)'}}>{FETES.slice(0,7).map(([d,t],i)=><div key={i} style={{display:'grid',gridTemplateColumns:'120px 1fr',gap:12,padding:'10px 14px',borderBottom:i<6?'var(--hairline)':0,font:'var(--type-body-sm)'}}><span style={{font:'var(--type-mono)',fontSize:13,color:'var(--accent-laterite)'}}>{d}</span><span>{t}</span></div>)}</div></div>
    </Container></section>
  </>;
}
Object.assign(window,{Accueil});
