// Fiches : personnages, monuments, régions, peuples, culture, symboles, valeurs, célébrations, glossaire, sources.
const EPOQUES=[
 {id:'origines',nom:'Origines & royaumes',en:'Origins & kingdoms',de:-30000,a:1883,color:'#6B3F2A',resume:'Peuplements anciens, civilisation Sao, expansion bantoue, royaumes, sultanats et chefferies.'},
 {id:'allemand',nom:'Kamerun allemand',en:'German Kamerun',de:1884,a:1915,color:'#544A42',resume:'Traité germano-duala, protectorat, résistances, plantations et chemin de fer.'},
 {id:'mandats',nom:'Mandats & tutelles',en:'Mandates & trusteeship',de:1916,a:1959,color:'#254A85',resume:'Partage franco-britannique, mandats de la SDN puis tutelles de l’ONU, montée du nationalisme.'},
 {id:'independance',nom:'Indépendance & réunification',en:'Independence & reunification',de:1960,a:1971,color:'#0F6448',resume:'1er janvier 1960, plébiscite de 1961, République fédérale, premières institutions.'},
 {id:'unitaire',nom:'État unitaire',en:'Unitary state',de:1972,a:1989,color:'#A8452B',resume:'République unie, makossa, pétrole, passation de 1982, catastrophe de Nyos.'},
 {id:'contemporain',nom:'Cameroun contemporain',en:'Contemporary Cameroon',de:1990,a:2026,color:'#CE1126',resume:'Multipartisme, exploits sportifs, Bakassi, patrimoine mondial, numérique.'}
];
const THEMES=['Politique','Culture','Économie','Religion','Sport','Science & nature','Société'];
const REGIONS_F=['National','Littoral','Centre','Ouest','Nord-Ouest','Sud-Ouest','Sud','Est','Adamaoua','Nord','Extrême-Nord','International'];
const PERSONNAGES=[
 {id:'nchare',nom:'Nchare Yen',dates:'XIVe siècle',role:'Fondateur du royaume Bamoun',ep:'origines',reg:'Ouest',cat:'Souverains',bio:'Prince tikar parti de Rifum avec ses frères, il soumet dix-huit chefferies de la plaine du Noun et fonde Foumban vers 1394. Il institue le Nguon, assemblée où le roi rend compte à son peuple.',fait:'Sa dynastie compte 21 souverains sans interruption.',src:['Claude Tardits, Le Royaume bamoum (1980)']},
 {id:'adama',nom:'Modibo Adama',dates:'v. 1786 – 1847',role:'Fondateur de l’émirat de l’Adamaoua',ep:'origines',reg:'Nord',cat:'Souverains',bio:'Lettré peul formé au Bornou, investi par Ousman dan Fodio en 1806, il fonde Yola et étend l’émirat du Bénoué à la Sanaga. La région de l’Adamaoua porte son nom.',fait:'Les lamidats de Ngaoundéré, Garoua, Maroua et Rey Bouba descendent de son organisation.',src:['Eldridge Mohammadou, Les lamidats du Diamaré et du Mayo-Louti (1988)']},
 {id:'saker',nom:'Alfred Saker',dates:'1814 – 1880',role:'Missionnaire, fondateur de Victoria',ep:'origines',reg:'Sud-Ouest',cat:'Bâtisseurs',bio:'Baptiste anglais arrivé en 1845, il traduit la Bible en duala, imprime les premiers livres du pays et fonde Victoria (Limbe) en 1858 pour des affranchis chassés de Fernando Po.',fait:'Le collège Saker de Limbe perpétue son nom.',src:['Emily Saker, Alfred Saker, Missionary to Africa (1908)']},
 {id:'manga-bell',photo:'Rudolf_Manga.jpg',photoCredit:'Wikimedia Commons · domaine public',nom:'Rudolf Duala Manga Bell',dates:'1873 – 1914',role:'Roi des Duala Bell, résistant',ep:'allemand',reg:'Littoral',cat:'Résistants',bio:'Formé en Allemagne (Aalen, Bonn), il devient roi en 1908. Il s’oppose par la voie légale à l’expropriation des Duala du plateau Joss (1910–1913), saisit le Reichstag, puis est condamné pour haute trahison et pendu le 8 août 1914. Sa « Pagode » de Bonanjo est un lieu de mémoire.',fait:'Héros national ; sa mémoire est honorée chaque 8 août à Douala.',src:['Joël Kouam, Rudolf Duala Manga Bell (2014)','Documentaire « La Pagode » (CRTV)']},
 {id:'samba',nom:'Martin-Paul Samba',dates:'v. 1875 – 1914',role:'Officier, résistant',ep:'allemand',reg:'Sud',cat:'Résistants',bio:'Bulu formé à l’école militaire de Prusse (Mebenga m’Ebono), il sert l’administration allemande puis prépare une insurrection en pays bulu ; fusillé à Ebolowa le 8 août 1914.',fait:'Un lycée et la place centrale d’Ebolowa portent son nom.',src:['Archives nationales du Cameroun']},
 {id:'kuva',nom:'Kuva Likenye',dates:'? – 1894',role:'Chef bakweri de Buea',ep:'allemand',reg:'Sud-Ouest',cat:'Résistants',bio:'Il repousse l’expédition Gravenreuth en décembre 1891 (Gravenreuth y meurt), avant que Buea ne soit prise en 1894.',fait:'Figure de la résistance bakweri, célébrée à Buea.',src:['Edwin Ardener, Kingdom on Mount Cameroon (1996)']},
 {id:'njoya',photo:'Ibrahim_Njoya_02.jpg',photoCredit:'V. J. Ngoh, History of Cameroon since 1800 · domaine public',nom:'Sultan Ibrahim Njoya',dates:'v. 1860 – 1933',role:'17e roi des Bamoun, inventeur',ep:'mandats',reg:'Ouest',cat:'Souverains',bio:'Roi dès 1886, il crée l’écriture shümom (1896–1910), une langue de cour, des cartes de son royaume, un moulin à maïs, et fait bâtir le palais royal (1917). Il se convertit à l’islam puis compose une religion syncrétique. Déposé par la France en 1931, il meurt en exil à Yaoundé.',fait:'Le palais de Foumban abrite le musée royal ; le shümom est enseigné à l’école du palais.',src:['Claude Tardits, Le Royaume bamoum (1980)','Musée des Rois Bamoun, Foumban']},
 {id:'atangana',nom:'Charles Atangana',dates:'v. 1880 – 1943',role:'Chef supérieur des Ewondo et Bene',ep:'mandats',reg:'Centre',cat:'Bâtisseurs',bio:'Interprète puis chef supérieur nommé par les Allemands (1914), il suit l’administration en exil en Espagne, revient en 1920 et développe Yaoundé : cacao, routes, écoles, palais d’Efoulan.',fait:'Le quartier Efoulan et l’avenue Charles-Atangana portent son nom.',src:['Frederick Quinn, Charles Atangana of Yaoundé (1980)']},
 {id:'um-nyobe',photo:'Ruben_Um_Nyobe.jpg',photoCredit:'Wikimedia Commons · CC0',nom:'Ruben Um Nyobè',dates:'1913 – 1958',role:'Secrétaire général de l’UPC',ep:'mandats',reg:'Centre',cat:'Nationalistes',bio:'Instituteur puis greffier, il fonde l’UPC en 1948 et porte à trois reprises la revendication d’indépendance et de réunification à la tribune de l’ONU (1952–1954). Tué le 13 septembre 1958 près de Boumnyebel.',fait:'Réhabilité héros national par la loi du 16 décembre 1991.',src:['Achille Mbembe (éd.), Le problème national kamerunais (1984)','Documentaire « Autopsie d’une indépendance » (2008)']},
 {id:'mbida',nom:'André-Marie Mbida',dates:'1917 – 1980',role:'Premier chef de gouvernement',ep:'mandats',reg:'Centre',cat:'Nationalistes',bio:'Séminariste puis député, il forme le 15 mai 1957 le premier gouvernement camerounais (Démocrates camerounais) ; renversé en février 1958, il s’exile à Conakry puis revient en 1960.',fait:'Le lycée d’Efok et une avenue de Yaoundé portent son nom.',src:['Louis-Paul Ngongo, Histoire des institutions et des faits sociaux du Cameroun (1987)']},
 {id:'ahidjo',photo:'Ahmadou_Ahidjo.jpg',photoCredit:'Reagan Library · domaine public',nom:'Ahmadou Ahidjo',dates:'1924 – 1989',role:'Premier président de la République',ep:'independance',reg:'Nord',cat:'Chefs d’État',bio:'Né à Garoua, télégraphiste, député, Premier ministre en 1958, il conduit le pays à l’indépendance et à la réunification, bâtit l’État unitaire (1972) et démissionne le 4 novembre 1982.',fait:'Le stade omnisports de Yaoundé porte son nom.',src:['Philippe Gaillard, Ahmadou Ahidjo, patriote et despote (1994)']},
 {id:'foncha',nom:'John Ngu Foncha',dates:'1916 – 1999',role:'Premier ministre du Southern Cameroons, vice-président',ep:'independance',reg:'Nord-Ouest',cat:'Nationalistes',bio:'Instituteur de Bamenda, fondateur du KNDP (1955), il mène la campagne pour la réunification et co-signe les accords de Foumban (1961). Vice-président de la République fédérale (1961–1970).',fait:'Artisan du bilinguisme officiel.',src:['Victor Julius Ngoh, History of Cameroon since 1800 (1996)']},
 {id:'endeley',nom:'Emmanuel Mbella Lifafe Endeley',dates:'1916 – 1988',role:'Premier chef de gouvernement du Southern Cameroons',ep:'mandats',reg:'Sud-Ouest',cat:'Nationalistes',bio:'Médecin de Buea, fondateur du KNC, il obtient l’autonomie du Southern Cameroons (1954) et dirige son gouvernement jusqu’en 1959.',fait:'Figure de l’autonomie du Cameroun méridional.',src:['V. J. Ngoh, Southern Cameroons 1922–1961 (2001)']},
 {id:'muna',nom:'Solomon Tandeng Muna',dates:'1912 – 2002',role:'Premier ministre du Cameroun occidental, président de l’Assemblée',ep:'independance',reg:'Nord-Ouest',cat:'Nationalistes',bio:'Ministre au Nigeria puis au Southern Cameroons, Premier ministre de l’État fédéré (1968–1972), vice-président (1970–1972), président de l’Assemblée nationale (1973–1988).',fait:'Père de la juriste Bernard Muna et de la militante Ama Tutu Muna.',src:['Archives de l’Assemblée nationale']},
 {id:'biya',nom:'Paul Biya',dates:'né en 1933',role:'Président de la République depuis 1982',ep:'unitaire',reg:'Sud',cat:'Chefs d’État',bio:'Né à Mvomeka’a, formé à Paris (Sciences Po, IHEOM), secrétaire général de la présidence puis Premier ministre (1975), il succède à Ahidjo le 6 novembre 1982. Sous ses mandats : nom de République du Cameroun (1984), lois sur les libertés (1990), constitution de 1996, règlement de Bakassi.',fait:'Auteur de Pour le libéralisme communautaire (1987).',src:['Présidence de la République, biographie officielle']},
 {id:'mveng',nom:'Engelbert Mveng',dates:'1930 – 1995',role:'Historien, jésuite, artiste',ep:'unitaire',reg:'Centre',cat:'Lettres & savoirs',bio:'Auteur de l’Histoire du Cameroun (1963), il conçoit le Monument de la Réunification, peint la chapelle du Hekima College à Nairobi et fonde l’Association des historiens africains.',fait:'Son œuvre relie art sacré et symboles africains.',src:['E. Mveng, Histoire du Cameroun (1963, rééd. 1984)']},
 {id:'dibango',nom:'Manu Dibango',dates:'1933 – 2020',role:'Saxophoniste, compositeur',ep:'unitaire',reg:'Littoral',cat:'Arts',bio:'Né à Douala, il fait connaître le makossa au monde avec Soul Makossa (1972), collabore avec Fela, Herbie Hancock, Sinéad O’Connor et devient artiste UNESCO pour la paix (2004).',fait:'Grand-croix de l’ordre de la Valeur.',src:['Manu Dibango, Trois kilos de café (1989)']},
 {id:'bebey',nom:'Francis Bebey',dates:'1929 – 2001',role:'Musicien, écrivain, journaliste',ep:'unitaire',reg:'Littoral',cat:'Arts',bio:'Pionnier de la sanza et de la guitare africaine, auteur du Fils d’Agatha Moudio (Grand prix littéraire d’Afrique noire 1968), responsable des programmes musicaux à l’UNESCO.',fait:'Plus de trente albums.',src:['F. Bebey, Musique de l’Afrique (1969)']},
 {id:'nzie',nom:'Anne-Marie Nzié',dates:'1932 – 2016',role:'Chanteuse, « voix d’or du Cameroun »',ep:'independance',reg:'Centre',cat:'Arts',bio:'Pionnière du bikutsi enregistré dès les années 1950 ; « Liberté » (1985) devient un hymne populaire repris dans tout le pays.',fait:'Première grande voix féminine de la musique camerounaise.',src:['Ministère des Arts et de la Culture, hommage national 2016']},
 {id:'beti',nom:'Mongo Beti',dates:'1932 – 2001',role:'Écrivain',ep:'contemporain',reg:'Centre',cat:'Lettres & savoirs',bio:'Alexandre Biyidi Awala, auteur de Ville cruelle (1954), Le Pauvre Christ de Bomba (1956), Mission terminée (1957). Professeur en France, il rentre en 1994 et ouvre à Yaoundé la Librairie des Peuples noirs.',fait:'L’une des voix majeures de la littérature africaine francophone.',src:['Mongo Beti, Œuvres']},
 {id:'oyono',nom:'Ferdinand Oyono',dates:'1929 – 2010',role:'Écrivain, diplomate, ministre',ep:'independance',reg:'Sud',cat:'Lettres & savoirs',bio:'Une vie de boy et Le Vieux Nègre et la Médaille (1956) comptent parmi les classiques du roman africain. Ambassadeur, puis ministre des Relations extérieures et de la Culture.',fait:'Traduit en plus de vingt langues.',src:['F. Oyono, Une vie de boy (1956)']},
 {id:'liking',nom:'Werewere Liking',dates:'née en 1950',role:'Dramaturge, plasticienne',ep:'contemporain',reg:'Littoral',cat:'Arts',bio:'Née à Bondé (Bassa), fondatrice du village Ki-Yi M’Bock à Abidjan (1985) ; théâtre-rituel, romans (Elle sera de jaspe et de corail), prix Noma 2005.',fait:'Figure du renouveau des arts de la scène africains.',src:['W. Liking, La Mémoire amputée (2004)']},
 {id:'beyala',nom:'Calixthe Beyala',dates:'née en 1961',role:'Romancière',ep:'contemporain',reg:'Littoral',cat:'Lettres & savoirs',bio:'Née à Douala, auteure de C’est le soleil qui m’a brûlée (1987), Les Honneurs perdus (Grand prix du roman de l’Académie française 1996).',fait:'Vingt romans traduits dans le monde.',src:['C. Beyala, Œuvres']},
 {id:'milla',nom:'Roger Milla',dates:'né en 1952',role:'Footballeur',ep:'contemporain',reg:'Littoral',cat:'Sport',bio:'Albert Roger Mooh Miller, Ballon d’or africain 1976 et 1990, quatre buts à Italie 90 à 38 ans ; en 1994, plus vieux buteur de l’histoire de la Coupe du monde (42 ans).',fait:'Ambassadeur itinérant de la République.',src:['FIFA, archives Coupe du monde']},
 {id:'nkono',nom:'Thomas N’Kono',dates:'né en 1956',role:'Gardien de but',ep:'unitaire',reg:'Centre',cat:'Sport',bio:'Ballon d’or africain 1979 et 1982, héros d’Espagne 82, gardien de l’Espanyol Barcelone ; il inspire Gianluigi Buffon.',fait:'Entraîneur des gardiens des Lions.',src:['CAF, palmarès']},
 {id:'etoo',nom:'Samuel Eto’o',dates:'né en 1981',role:'Footballeur, président de la FECAFOOT',ep:'contemporain',reg:'Centre',cat:'Sport',bio:'Champion olympique 2000, quadruple Ballon d’or africain, vainqueur de la Ligue des champions avec Barcelone (2006, 2009) et l’Inter (2010) ; meilleur buteur de l’histoire de la CAN.',fait:'Président de la FECAFOOT depuis 2021.',src:['FECAFOOT']},
 {id:'mbango',nom:'Françoise Mbango Etone',dates:'née en 1976',role:'Athlète, triple saut',ep:'contemporain',reg:'Centre',cat:'Sport',bio:'Championne olympique à Athènes 2004 et Pékin 2008, première Camerounaise médaillée d’or olympique ; vice-championne du monde 2001 et 2003.',fait:'Record olympique 15,39 m (2008).',src:['World Athletics']},
 {id:'sumegne',nom:'Joseph-Francis Sumégné',dates:'né en 1951',role:'Sculpteur',ep:'contemporain',reg:'Littoral',cat:'Arts',bio:'Autodidacte de Bandjoun, il réalise La Nouvelle Liberté (1996) et des œuvres monumentales en matériaux de récupération exposées de Dakar à Paris.',fait:'Pionnier de l’art urbain camerounais.',src:['doual’art, archives']},
 {id:'fonlon',nom:'Bernard Nsokika Fonlon',dates:'1924 – 1986',role:'Universitaire, ministre, père du bilinguisme',ep:'independance',reg:'Nord-Ouest',cat:'Lettres & savoirs',bio:'Docteur de Dublin, ministre des Transports et de la Santé, fondateur de la revue Abbia (1963), il théorise le bilinguisme officiel et traduit l’hymne en anglais.',fait:'La Fonlon-Nichols Award récompense la liberté d’expression en Afrique.',src:['B. Fonlon, The Task of Today (1966)']},
 {id:'ekotto',nom:'Marthe Ekemeyong Moumié',dates:'1931 – 2009',role:'Militante nationaliste',ep:'mandats',reg:'Centre',cat:'Nationalistes',bio:'Épouse de Félix Moumié, militante de l’UDEFEC (Union démocratique des femmes camerounaises), emprisonnée puis exilée ; auteure de Victime du colonialisme français (2006).',fait:'Voix des femmes dans le mouvement nationaliste.',src:['M. Moumié, Victime du colonialisme français (2006)']}
];
const MONUMENTS=[
 {id:'foumban',photo:'Bamun_sultan_palace.jpg',photoCredit:'Wikimedia Commons · CC BY-SA 2.5',nom:'Palais des rois Bamoun',lieu:'Foumban, Ouest',an:'1917',ll:[5.727,10.90],type:'Palais',d:'Édifié par le sultan Njoya sur le modèle du palais du gouverneur de Buea ; briques de terre cuite, trois niveaux, musée royal (trône perlé, masques, écriture shümom). Un nouveau musée en forme d’araignée, de serpent bicéphale et de double cloche a ouvert en 2023.',acces:'Centre de Foumban ; ouvert tous les jours 9 h – 17 h ; droit d’entrée 2 000 FCFA (à confirmer).',src:'Musée des Rois Bamoun'},
 {id:'reunification',photo:'Monument_de_la_réunification_Yaoundé_01.JPG',photoCredit:'Wikimedia Commons · CC BY-SA 3.0',nom:'Monument de la Réunification',lieu:'Yaoundé, Centre',an:'1974',ll:[3.857,11.512],type:'Monument',d:'Spirale de béton de deux serpents enlacés (Engelbert Mveng, Gédéon Mpando) ; à sa base, une statue de vieillard portant cinq enfants, allégorie de la nation. Rénové en 2010 pour le cinquantenaire.',acces:'Quartier du Lac, face au ministère des Relations extérieures ; parc ouvert en journée.',src:'MINAC'},
 {id:'pagode',nom:'La Pagode de Manga Bell',lieu:'Douala-Bonanjo, Littoral',an:'1905',ll:[4.045,9.693],type:'Palais',d:'Résidence des rois Bell, achevée en 1905 pour Auguste Manga Ndumbe ; toit en pagode. Lieu de mémoire de Rudolf Duala Manga Bell, classée au patrimoine national.',acces:'Bonanjo, près de la place du Gouvernement ; visite extérieure libre.',src:'Communauté urbaine de Douala'},
 {id:'liberte',photo:'Statue_de_la_nouvelle_liberte_Douala.jpg',photoCredit:'Wikimedia Commons · CC BY-SA',nom:'La Nouvelle Liberté',lieu:'Douala-Deido, Littoral',an:'1996',ll:[4.071,9.715],type:'Sculpture',d:'Sculpture monumentale de 12 m de Joseph-Francis Sumégné, assemblée de pièces de récupération ; commande de doual’art, devenue emblème de la ville.',acces:'Rond-point Deido, visible en permanence.',src:'doual’art'},
 {id:'bafut',nom:'Palais du Fon de Bafut',lieu:'Bafut, Nord-Ouest',an:'XVe s. – 1910',ll:[6.09,10.10],type:'Palais',d:'Ensemble de plus de 50 bâtiments autour de l’Achum, sanctuaire au toit de chaume reconstruit après 1910 ; musée du palais (2006) ; liste indicative du patrimoine mondial.',acces:'20 km de Bamenda ; visite guidée, 2 000 FCFA (à confirmer).',src:'UNESCO, liste indicative'},
 {id:'bandjoun',nom:'Chefferie de Bandjoun',lieu:'Bandjoun, Ouest',an:'XVIIe s. – 2005',ll:[5.37,10.41],type:'Palais',d:'Grande case à palabres aux piliers sculptés (reconstruite après l’incendie de 2005), musée de la Route des Chefferies (2005), trésor royal.',acces:'Route N4 Bafoussam–Yaoundé ; musée ouvert du mardi au dimanche.',src:'Route des Chefferies'},
 {id:'bimbia',nom:'Site de Bimbia',lieu:'Limbe, Sud-Ouest',an:'XVIIIe – XIXe s.',ll:[3.98,9.26],type:'Lieu de mémoire',d:'Ancien comptoir de traite négrière ; vestiges de chaînes, de citernes et de bâtiments. Liste indicative du patrimoine mondial (2018), lieu de mémoire de la diaspora (visites du Ghana Year of Return).',acces:'Village de Dikolo, 15 km de Limbe ; guide communautaire obligatoire.',src:'MINAC / UNESCO'},
 {id:'wouri',nom:'Pont sur le Wouri',lieu:'Douala, Littoral',an:'1955 · 2017',ll:[4.06,9.68],type:'Ouvrage',d:'Premier pont (1 800 m, rail-route) inauguré en 1955 ; second pont ouvert entre 2014 et 2017 ; l’ensemble relie Douala à Bonabéri et à la route de l’Ouest.',acces:'Accès routier et piéton.',src:'MINTP'},
 {id:'cathedrale',nom:'Cathédrale Notre-Dame-des-Victoires',lieu:'Yaoundé, Centre',an:'1955',ll:[3.866,11.519],type:'Édifice religieux',d:'Cathédrale de l’archidiocèse de Yaoundé, plan triangulaire moderne ; lieu des grandes célébrations nationales.',acces:'Centre-ville, avenue Kennedy ; ouverte tous les jours.',src:'Archidiocèse de Yaoundé'},
 {id:'mosquee',nom:'Grande mosquée de Foumban',lieu:'Foumban, Ouest',an:'1920 · 2016',ll:[5.729,10.899],type:'Édifice religieux',d:'Édifiée face au palais royal à l’initiative du sultan Njoya, reconstruite et agrandie en 2016.',acces:'Place du palais ; visite extérieure.',src:'Sultanat Bamoun'},
 {id:'musgum',nom:'Cases-obus musgum',lieu:'Pouss, Extrême-Nord',an:'tradition vivante',ll:[10.85,15.05],type:'Architecture',d:'Habitations en terre en forme d’obus, jusqu’à 9 m, aux arêtes servant d’échafaudage ; qualifiées par André Gide de « poterie humaine » (1926). Programme de sauvegarde depuis 1995.',acces:'Pouss, 100 km de Maroua ; cases-modèles visitables.',src:'Programme de sauvegarde MINAC'},
 {id:'rey-bouba',nom:'Palais du lamido de Rey Bouba',lieu:'Rey Bouba, Nord',an:'XIXe s.',ll:[8.67,14.18],type:'Palais',d:'Vaste enceinte de terre du lamidat fondé vers 1804, architecture soudano-sahélienne ; liste indicative du patrimoine mondial.',acces:'Sur autorisation du lamidat.',src:'Liste indicative UNESCO'},
 {id:'schloss',nom:'Schloss de Buea',lieu:'Buea, Sud-Ouest',an:'1901 – 1909',ll:[4.155,9.24],type:'Palais',d:'Résidence du gouverneur von Puttkamer au pied du mont Cameroun, modèle du palais de Foumban ; aujourd’hui résidence officielle du Premier ministre.',acces:'Visite extérieure ; intérieur sur autorisation.',src:'Services du Premier ministre'},
 {id:'musee-national',nom:'Musée national du Cameroun',lieu:'Yaoundé, Centre',an:'1930 · 2015',ll:[3.862,11.517],type:'Musée',d:'Ancien palais présidentiel (résidence du commissaire de la République, 1930) rénové et ouvert en 2015 : neuf salles, collections des dix régions, art contemporain.',acces:'Quartier du Lac ; mardi–dimanche 9 h – 18 h ; 2 000 FCFA (à confirmer).',src:'MINAC'},
 {id:'stade-ahidjo',photo:'Stade_Ahmadou_Ahidjo,_Mfandena,_Yaoundé.jpg',photoCredit:'Pare Didier · CC BY-SA 4.0',nom:'Stade omnisports Ahmadou-Ahidjo',lieu:'Yaoundé, Centre',an:'1972',ll:[3.880,11.510],type:'Ouvrage',d:'Construit pour la CAN 1972, rénové pour 2022 (42 500 places) ; théâtre des grandes rencontres des Lions et des fêtes nationales.',acces:'Mfandena ; visites lors des événements.',src:'MINSEP'},
 {id:'mefou',img:'nature',nom:'Sanctuaire des primates de la Mefou',lieu:'Mefou, Centre',an:'1999',ll:[3.63,11.60],type:'Site naturel',d:'Gorilles, chimpanzés et mandrills recueillis, gérés par Ape Action Africa ; 1 044 ha de forêt à 45 minutes de Yaoundé.',acces:'Route d’Ebolowa ; tous les jours 9 h – 17 h.',src:'Ape Action Africa'},
 {id:'lobe',nom:'Chutes de la Lobé',lieu:'Kribi, Sud',an:'site naturel',ll:[2.877,9.895],img:'kribi',type:'Site naturel',d:'Les seules chutes d’Afrique se jetant directement dans l’océan ; site sacré des Batanga et des Bagyéli ; liste indicative du patrimoine mondial.',acces:'8 km au sud de Kribi.',src:'MINTOUR'},
 {id:'mont-cameroun',img:'paysage',nom:'Mont Cameroun (Fako)',lieu:'Buea, Sud-Ouest',an:'volcan actif',ll:[4.203,9.170],img:'paysage',type:'Site naturel',d:'4 095 m, toit de l’Afrique de l’Ouest et centrale, volcan actif (dernière éruption 2012) ; « Chariot des dieux » d’Hannon le Carthaginois ; course de l’espoir chaque février.',acces:'Ascension 2–3 jours avec guide agréé depuis Buea.',src:'Parc national du Mont Cameroun'},
 {id:'nyos',nom:'Lac Nyos',lieu:'Wum, Nord-Ouest',an:'1986',ll:[6.44,10.30],type:'Lieu de mémoire',d:'Lac de cratère de la ligne volcanique du Cameroun ; catastrophe du 21 août 1986 ; colonnes de dégazage depuis 2001 ; stèle commémorative.',acces:'Piste depuis Wum ; accès réglementé.',src:'Ministère de la Recherche scientifique (IRGM)'},
 {id:'waza',img:'paysage',nom:'Parc national de Waza',lieu:'Waza, Extrême-Nord',an:'1934 · 1968',ll:[11.3,14.65],type:'Site naturel',d:'Réserve de biosphère UNESCO (1979), 170 000 ha de savane : éléphants, girafes, lions, antilopes ; camp de Waza.',acces:'120 km au nord de Maroua ; ouvert de novembre à mai.',src:'MINFOF'},
 {id:'korup',img:'nature',nom:'Parc national de Korup',lieu:'Mundemba, Sud-Ouest',an:'1986',ll:[5.1,8.85],type:'Site naturel',d:'L’une des plus anciennes forêts tropicales d’Afrique (60 millions d’années), 1 260 km² ; pont suspendu sur la Mana ; plus de 400 espèces d’arbres.',acces:'Mundemba, 8 h de Douala ; guides du parc.',src:'MINFOF'},
 {id:'dja',img:'nature',nom:'Réserve de faune du Dja',lieu:'Somalomo, Sud / Est',an:'1950 · 1987',ll:[3.2,12.9],type:'Site naturel',d:'Patrimoine mondial UNESCO : 5 260 km² de forêt ceinturée par la boucle du Dja ; gorilles, éléphants de forêt, communautés Baka.',acces:'Somalomo ou Lomié ; expéditions avec écogardes.',src:'UNESCO'}
];
const REGIONS=[
 {id:'adamaoua',nom:'Adamaoua',chef:'Ngaoundéré',pop:'1,2 M',ll:[7.32,13.58],d:'Château d’eau du Cameroun (plateau à 1 100 m), élevage bovin peul, lamidat de Ngaoundéré, chutes de Tello, lac Tison ; terminus du Transcamerounais.',langues:'fulfulde, mbum, gbaya',fete:'Fantasia du lamidat'},
 {id:'centre',nom:'Centre',chef:'Yaoundé',pop:'4,2 M',ll:[3.85,11.50],d:'Capitale politique sur sept collines, Musée national, Monument de la Réunification, cacao du Mbam et de la Lékié ; peuples Ewondo, Eton, Bassa, Bafia.',langues:'ewondo, eton, bassa, bafia',fete:'Fête nationale du 20 mai'},
 {id:'est',nom:'Est',chef:'Bertoua',pop:'0,9 M',ll:[4.58,13.68],d:'Plus vaste région (109 000 km²), forêt du Dja et de Lobéké, bois, or et cobalt ; peuples Gbaya, Maka, Kako, Baka.',langues:'gbaya, maka, kako, baka',fete:'Rites Baka du Jengi'},
 {id:'extreme-nord',nom:'Extrême-Nord',chef:'Maroua',pop:'4,6 M',ll:[10.59,14.32],d:'Région la plus peuplée : monts Mandara, pics de Rhumsiki, parc de Waza, plaine du Logone ; cuir et tissage de Maroua ; peuples Kirdi, Kotoko, Musgum, Arabes Choa, Peuls.',langues:'fulfulde, mafa, tupuri, kotoko, arabe choa',fete:'Fête du coton, fantasias'},
 {id:'littoral',nom:'Littoral',chef:'Douala',pop:'3,7 M',ll:[4.05,9.70],d:'Capitale économique et port historique, Pagode, Nouvelle Liberté, ponts du Wouri, Edéa et son barrage, Nkongsamba ; berceau du makossa.',langues:'duala, bassa, bakoko, mbo',fete:'Ngondo (décembre)'},
 {id:'nord',nom:'Nord',chef:'Garoua',pop:'2,7 M',ll:[9.30,13.40],d:'Vallée de la Bénoué, port fluvial de Garoua, parcs de la Bénoué, du Faro et de Bouba Ndjida ; lamidat de Rey Bouba ; coton et arachide.',langues:'fulfulde, mundang, dii',fete:'Fêtes des lamidats'},
 {id:'nord-ouest',nom:'Nord-Ouest',chef:'Bamenda',pop:'2,0 M',ll:[5.96,10.15],d:'Hauts plateaux anglophones, Ring Road, palais de Bafut et de Nso (Kumbo), lac Nyos, café arabica et thé de Ndu ; artisanat de Bali et Bamessing.',langues:'anglais pidgin, lamnso’, kom, bafut',fete:'Fêtes annuelles des Fons (Lela, Ngonnso)'},
 {id:'ouest',nom:'Ouest',chef:'Bafoussam',pop:'2,1 M',ll:[5.478,10.418],d:'Pays bamiléké et bamoun : chefferies de Bandjoun, Baham, Bafang ; palais de Foumban ; Dschang et son musée des Civilisations ; café, maraîchage, tontines.',langues:'ghomala’, medumba, fe’fe’, yemba, shüpamem',fete:'Nguon (Foumban), Medumba (Bangangté)'},
 {id:'sud',nom:'Sud',chef:'Ebolowa',pop:'0,8 M',ll:[2.9,11.15],d:'Forêt et côte : Kribi, chutes de la Lobé, Campo-Ma’an, port en eau profonde, réserve du Dja ; peuples Bulu, Fang, Ntumu, Batanga, Bagyéli.',langues:'bulu, fang, batanga',fete:'Fête du Nyeng (Kribi)'},
 {id:'sud-ouest',nom:'Sud-Ouest',chef:'Buea',pop:'1,6 M',ll:[4.155,9.24],d:'Région anglophone du mont Cameroun : Buea, Limbe et ses plages volcaniques, Korup, Bakassi, plantations de la CDC ; peuples Bakweri, Bayangi, Oroko, Isubu.',langues:'anglais pidgin, mokpwe, kenyang',fete:'Course de l’espoir du mont Cameroun (février)'}
];
const AIRES=[
 {id:'sawa',nom:'Aire côtière — Sawa',peuples:'Duala, Bakweri, Bakoko, Batanga, Bassa (côte), Malimba, Isubu',ll:[4.05,9.7],color:'#1B3A6B',d:'Peuples de l’estuaire et du littoral, premiers en contact avec l’Europe ; pirogues de course, Ngondo (assemblée traditionnelle et fête de l’eau, décembre), makossa, tenue sanja et kaba ngondo.',langues:'duala, mokpwe, bakoko, bassa',regions:['littoral','sud-ouest']},
 {id:'fang-beti',nom:'Aire forestière — Fang-Beti & Bassa',peuples:'Ewondo, Bulu, Eton, Bene, Fang, Bassa, Baka & Bagyéli',ll:[3.5,11.8],color:'#0F6448',d:'Forêt équatoriale ; épopée du mvet, bikutsi, société du cacao ; peuples Baka et Bagyéli, gardiens de la forêt ; rites d’initiation (Sso).',langues:'ewondo, bulu, bassa, baka',regions:['centre','sud','est']},
 {id:'grassfields',nom:'Hauts plateaux — Grassfields',peuples:'Bamiléké, Bamoun, Tikar, Nso, Kom, Bafut, Widikum, Bali',ll:[5.6,10.4],color:'#A8452B',d:'Chefferies et royaumes structurés, art royal (perles, bronze, bois), tontines, Nguon, tissus ndop et toghu, danses des masques (Kuosi).',langues:'ghomala’, medumba, fe’fe’, shüpamem, lamnso’',regions:['ouest','nord-ouest']},
 {id:'soudano',nom:'Aire soudano-sahélienne — Grand Nord',peuples:'Peuls (Fulbe), Kirdi (Mafa, Kapsiki, Mofu…), Tupuri, Musgum, Kotoko, Arabes Choa, Gbaya, Mbum, Dii',ll:[9.5,13.8],color:'#5E4600',d:'Lamidats peuls, montagnards des Mandara, pêcheurs du Logone ; fantasia, architecture de terre, cuir et tissage ; gourna tupuri.',langues:'fulfulde, kanuri, mafa, tupuri, arabe choa',regions:['adamaoua','nord','extreme-nord']}
];
const CULTURE={
 musiques:[['Makossa','Littoral',"Né à Douala des rythmes ambasse bey et de la rumba ; Manu Dibango, Ekambi Brillant, Ben Decca, Petit-Pays."],['Bikutsi','Centre',"Rythme ewondo en 6/8 porté par les femmes ; Anne-Marie Nzié, Les Têtes Brûlées, K-Tino, Lady Ponce."],['Assiko','Littoral / Centre',"Danse bassa à la guitare et à la bouteille ; Jean Bikoko « Aladin »."],['Mangambeu & Bend-skin','Ouest',"Rythmes bamiléké ; André-Marie Tala, Kouchoum Mbada."],['Njang & Bottle dance','Nord-Ouest',"Danses des Grassfields anglophones."],['Gourna & Fantasia','Grand Nord',"Danse tupuri des fêtes de récolte ; parades équestres peules."],['Afro-jazz & world','International',"Francis Bebey, Richard Bona, Blick Bassy, Charlotte Dipanda, Sally Nyolo."]],
 cuisine:[['Ndolè','Littoral',"Feuilles amères, pâte d’arachide, crevettes ou viande ; plat national."],['Eru','Sud-Ouest',"Feuilles d’eru et waterleaf, huile de palme, avec water fufu."],['Poulet DG','Douala',"Poulet, plantains mûrs, légumes ; « directeur général »."],['Koki','Ouest / Centre',"Gâteau de haricots à l’huile de palme cuit en feuilles."],['Mbongo tchobi','Littoral',"Sauce noire bassa aux épices brûlées, poisson."],['Nkui & Taro sauce jaune','Ouest',"Plats bamiléké des cérémonies."],['Achu','Nord-Ouest',"Taro pilé et sauce jaune."],['Folléré, kilichi, kossam','Grand Nord',"Sauce d’oseille, viande séchée, lait caillé peul."]],
 lettres:[['Roman','Mongo Beti, Ferdinand Oyono, Calixthe Beyala, Léonora Miano (Femina 2013), Patrice Nganang, Hemley Boum, Djaïli Amadou Amal (Goncourt des lycéens 2020)'],['Théâtre','Guillaume Oyônô Mbia (Trois prétendants… un mari), Werewere Liking'],['Pensée','Achille Mbembe, Fabien Eboussi Boulaga, Jean-Marc Ela, Marcien Towa'],['Cinéma','Jean-Pierre Dikongué-Pipa (Muna Moto, 1975), Daniel Kamwa (Pousse-Pousse), Jean-Pierre Bekolo (Quartier Mozart), Rosine Mbakam'],['Arts plastiques','Pascale Marthine Tayou, Barthélémy Toguo, Bili Bidjocka, Joseph-Francis Sumégné, doual’art (SUD triennale)']],
 glossaire:[['Ngondo','Assemblée traditionnelle du peuple sawa et fête annuelle de l’eau à Douala (décembre).'],['Nguon','Rituel bamoun de reddition des comptes du sultan, tous les deux ans ; UNESCO 2023.'],['Ndop','Tissu de coton teint à l’indigo par réserve, insigne des notables des Grassfields.'],['Toghu','Velours noir brodé de fils colorés, tenue de cérémonie du Nord-Ouest, portée par la délégation olympique.'],['Tontine (njangi)','Association d’épargne rotative, pilier de l’économie populaire.'],['Lamido','Souverain peul d’un lamidat du Grand Nord.'],['Fon','Souverain d’une chefferie des Grassfields anglophones.'],['Mvet','Harpe-cithare et épopée orale des Fang-Beti.'],['Kaba ngondo','Robe ample des femmes sawa, devenue vêtement national.'],['Mpodol','« Celui qui porte la parole », surnom de Ruben Um Nyobè.'],['Shümom','Écriture inventée par le sultan Njoya (1896–1910).'],['Kirdi','« Païen » en kanuri ; désigne les peuples non islamisés des monts Mandara.']]
};
const SYMBOLES=[
 {id:'drapeau',nom:'Drapeau national',d:'Trois bandes verticales égales, vert, rouge, jaune, et une étoile d’or à cinq branches au centre de la bande rouge. Adopté le 29 octobre 1957 ; deux étoiles dans la bande verte de 1961 à 1975 (États fédérés) ; étoile unique depuis le 20 mai 1975. Vert : la forêt du Sud et l’espérance ; jaune : la savane du Nord et le soleil ; rouge : l’unité et la souveraineté. Proportions 2 : 3.'},
 {id:'armoiries',nom:'Armoiries de la République',d:'Description officielle (loi de 1972, révisée 1984) : un écu tiercé en pal aux couleurs nationales, chargé au centre de la carte du Cameroun en bleu ; brochant, la balance de la justice surmontée du glaive ; en chef, l’étoile d’or. L’écu est posé sur deux faisceaux de licteur croisés. Au-dessus : « République du Cameroun » et, en dessous, la devise en français et en anglais. Le Musée n’en publie pas de reproduction : seul le fichier officiel fourni par les services de l’État est autorisé.'},
 {id:'hymne',nom:'Hymne national',d:'« Ô Cameroun, berceau de nos ancêtres » / « O Cameroon, Thou Cradle of our Fathers ». Musique de René Djam Afame, paroles de Samuel Minkio Bamba et Moïse Nyatte Nko’o (Foulassi, 1928) ; adopté en 1957 ; paroles françaises révisées en 1978 ; version anglaise de Bernard Nsokika Fonlon. Premier vers : « Ô Cameroun berceau de nos ancêtres, / Va debout et jaloux de ta liberté ».'},
 {id:'devise',nom:'Devise',d:'Paix – Travail – Patrie / Peace – Work – Fatherland. Inscrite à l’article 1er de la Constitution ; figure sur les armoiries, les documents officiels et le fronton des administrations.'},
 {id:'langues',nom:'Langues officielles',d:'Français et anglais, à égalité (Constitution de 1996, art. 1er-3). Près de 250 langues nationales, promues par la loi de 2019 ; le Cameroun est l’un des pays les plus multilingues du monde.'},
 {id:'sceau',nom:'Sceau et ordres nationaux',d:'Le sceau de l’État reproduit les armoiries. Ordres : ordre de la Valeur (1957, cinq grades, ruban vert-rouge-jaune), ordre du Mérite camerounais (1972). La fête nationale est l’occasion des promotions.'},
 {id:'lion',nom:'Le Lion',d:'Emblème sportif national : Lions indomptables (football masculin), Lionnes indomptables ; surnom né en 1972. Le lion figure aussi dans l’iconographie de plusieurs institutions.'}
];
const VALEURS=[
 {id:'paix',nom:'Paix',d:'Premier mot de la devise. Règlement pacifique du différend de Bakassi (2002–2008), médiations régionales, accueil de centaines de milliers de réfugiés des pays voisins.'},
 {id:'travail',nom:'Travail',d:'Économie diversifiée (agriculture, bois, pétrole, services) ; tontines et associations d’entraide ; place de l’école : taux de scolarisation primaire parmi les plus élevés d’Afrique centrale.'},
 {id:'patrie',nom:'Patrie',d:'Une nation née de la réunification de deux héritages ; fêtes du 20 mai et du 11 février ; héros nationaux reconnus par la loi de 1991.'},
 {id:'unite',nom:'Unité dans la diversité',d:'« Afrique en miniature » : quatre aires culturelles, 250 langues, deux langues officielles ; christianisme, islam et religions traditionnelles cohabitent.'},
 {id:'hospitalite',nom:'Hospitalité',d:'Culture de l’accueil et de la table partagée : ndolè, eru, koki, poulet DG, folléré ; la « famille élargie » comme filet de sécurité.'},
 {id:'resilience',nom:'Résilience',d:'Reconstruction après Nyos, dégazage du lac ; adaptation des communautés au climat ; solidarité des diasporas.'}
];
const FETES=[['1er janvier','Fête de l’Indépendance (1960)'],['11 février','Fête de la Jeunesse (plébiscite de 1961)'],['20 mai','Fête nationale (référendum de 1972)'],['1er octobre','Réunification (1961) — commémoration'],['8 août','Mémoire de Rudolf Duala Manga Bell (Douala)'],['décembre','Ngondo (Sawa, Douala)'],['tous les deux ans','Nguon (Bamoun, Foumban) — UNESCO 2023'],['mai','Festival Medumba (Bangangté)'],['février','Course de l’espoir du mont Cameroun (Buea)'],['fin d’année','Fantasias et fêtes des lamidats (Grand Nord)'],['fêtes religieuses','Noël, Pâques, Ascension, Assomption ; Ramadan, Tabaski, Mawlid (jours fériés)']];
const SOURCES=[['Livre','Engelbert Mveng, Histoire du Cameroun, Présence africaine, 1963 (rééd. CEPER 1984)'],['Livre','Victor Julius Ngoh, History of Cameroon since 1800, Presbook, 1996'],['Livre','Achille Mbembe, La naissance du maquis dans le Sud-Cameroun, Karthala, 1996'],['Livre','Claude Tardits, Le Royaume bamoum, Armand Colin, 1980'],['Livre','Thomas Deltombe, Manuel Domergue, Jacob Tatsitsa, Kamerun !, La Découverte, 2011'],['Livre','Daniel Abwa, Cameroun : histoire d’un nationalisme, CLÉ, 2010'],['Livre','Jean-Pierre Warnier, Échanges, développement et hiérarchies dans le Bamenda pré-colonial, 1985'],['Livre','Eldridge Mohammadou, Les lamidats du Diamaré et du Mayo-Louti, 1988'],['Documentaire','Autopsie d’une indépendance, Gaëlle Le Roy & Valérie Osouf, 2008'],['Documentaire','Cameroun, autopsie d’une indépendance ; Le Cameroun, l’Afrique en miniature (CRTV / TV5Monde)'],['Archive','Archives nationales du Cameroun, Yaoundé ; Bundesarchiv (R 1001, Kamerun) ; Archives nationales d’outre-mer, Aix-en-Provence'],['Archive','Nations unies, Conseil de tutelle, pétitions et rapports de missions (1949–1959)'],['Institution','UNESCO — Centre du patrimoine mondial ; Liste du patrimoine immatériel'],['Institution','Musée national du Cameroun, Yaoundé ; Musée des Rois Bamoun, Foumban ; Route des Chefferies, Bandjoun'],['Institution','Institut national de la statistique (recensement 2005, projections 2024)']];
Object.assign(window,{EPOQUES,THEMES,REGIONS_F,PERSONNAGES,MONUMENTS,REGIONS,AIRES,CULTURE,SYMBOLES,VALEURS,FETES,SOURCES});
