const {Button,Tag,Badge,Icon,Tooltip}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
/* Filtres progressifs, 3 niveaux : 1) époque — onglets larges ; 2) profondeur + recherche ; 3) « Affiner » replié : facettes avec compteurs. */
const FACETTES=[{k:'th',l:'Thème',opts:THEMES},{k:'ctx',l:'Contexte',opts:[['int','Vie intérieure'],['ext','Relations extérieures']]},{k:'type',l:'Type',opts:['événement','personnage','monument','traité']},{k:'nat',l:'Nature',opts:['fondateur','heureux','tragique']},{k:'reg',l:'Région',opts:REGIONS_F},{k:'src',l:'Source',opts:['livre','documentaire','archive']}];
const NIV=[[1,'Essentiel','les repères à connaître — dix minutes'],[2,'Approfondi','pour comprendre les enchaînements — une heure'],[3,'Complet','tous les repères documentés']];
const groupKey=an=>an<0?'Avant notre ère':an<1000?'Ier – Xe siècle':an<1800?['XI','XII','XIII','XIV','XV','XVI','XVII','XVIII'][Math.floor(an/100)-10]+'ᵉ siècle':an<1900?'XIXᵉ siècle':(Math.floor(an/10)*10)+'s';
function Frise({go,epoque,item,query,falc}){
  const [ep,setEp]=React.useState(epoque||'toutes');const [niv,setNiv]=React.useState(epoque||query?3:1);const [fac,setFac]=React.useState({});const [affiner,setAffiner]=React.useState(false);const [q,setQ]=React.useState(query||'');const [openF,setOpenF]=React.useState(null);const [openItem,setOpenItem]=React.useState(item||null);
  React.useEffect(()=>{if(item){const el=document.getElementById('rep-'+encodeURIComponent(item));if(el){const y=el.getBoundingClientRect().top+window.scrollY-140;window.scrollTo({top:y});}}},[]);
  const base=FRISE.filter(e=>(ep==='toutes'||e.ep===ep)&&e.niv<=niv&&(!q||(e.t+' '+e.d).toLowerCase().includes(q.toLowerCase())));
  const match=(e,skip)=>FACETTES.every(F=>F.k===skip||!fac[F.k]||fac[F.k].length===0||fac[F.k].includes(e[F.k]));
  const list=base.filter(e=>match(e));
  const count=(k,v)=>base.filter(e=>match(e,k)&&e[k]===v).length;
  const nActive=Object.values(fac).reduce((s,a)=>s+(a?a.length:0),0);
  const toggle=(k,v)=>setFac(s=>{const cur=s[k]||[];return{...s,[k]:cur.includes(v)?cur.filter(x=>x!==v):[...cur,v]};});
  const groups=[];list.forEach(e=>{const key=groupKey(e.an);const g=groups.find(x=>x.key===key);if(g)g.items.push(e);else groups.push({key,items:[e]});});
  const chip=(on,extra)=>({all:'unset',boxSizing:'border-box',cursor:'pointer',display:'inline-flex',alignItems:'center',gap:6,minHeight:36,padding:'0 12px',font:'var(--type-caption)',fontWeight:600,border:'1px solid '+(on?'var(--cm-vert-800)':'var(--border-default)'),background:on?'var(--surface-brand-soft)':'var(--surface-card)',color:on?'var(--cm-vert-900)':'var(--text-body)',...extra});
  const M='var(--marker-size)';
  return <>
    <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)'}}><Container style={{padding:'var(--space-8) var(--gutter) 0'}}>
      <Overline num={1}>Frise chronologique</Overline>
      <h1 style={{font:'var(--type-h2)',marginTop:6}}>{falc?'Les grandes dates du Cameroun':'De Shum Laka à aujourd’hui'}</h1>
      <div role="tablist" aria-label="Époque" style={{display:'flex',gap:4,marginTop:'var(--space-6)',flexWrap:'wrap'}}>
        {[{id:'toutes',nom:'Toutes les époques',de:-30000,a:2026,color:'var(--cm-ebene)'},...EPOQUES].map(e=>{const on=ep===e.id;const n=FRISE.filter(x=>(e.id==='toutes'||x.ep===e.id)&&x.niv<=niv).length;return <button key={e.id} role="tab" aria-selected={on} type="button" onClick={()=>{setEp(e.id);setOpenItem(null);}} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',flex:'1 1 110px',minWidth:0,display:'grid',gap:4,padding:'12px 12px 14px',borderTop:'4px solid '+(on?e.color:'var(--border-default)'),background:on?'var(--surface-page)':'transparent',borderBottom:'3px solid '+(on?e.color:'transparent'),color:on?'var(--text-heading)':'var(--text-muted)',textAlign:'left'}}><span style={{font:'var(--type-label)',fontWeight:700,fontSize:14}}>{e.nom}</span><span style={{font:'var(--type-caption)',fontWeight:500,fontVariantNumeric:'tabular-nums'}}>{e.id==='toutes'?n+' repères':fmtAn(e.de)+' → '+e.a+' · '+n}</span></button>;})}
      </div>
    </Container></section>
    <div style={{position:'sticky',top:0,zIndex:20,background:'var(--surface-page)',borderBottom:'var(--hairline)',boxShadow:'var(--shadow-xs)'}}><Container style={{padding:'12px var(--gutter)',display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}>
      <div role="radiogroup" aria-label="Profondeur" style={{display:'inline-flex',border:'1px solid var(--border-default)',background:'var(--surface-card)'}}>{NIV.map(([v,l,h])=><Tooltip key={v} content={h}><button type="button" role="radio" aria-checked={niv===v} onClick={()=>setNiv(v)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',height:36,padding:'0 14px',font:'var(--type-caption)',fontWeight:600,background:niv===v?'var(--cm-vert-800)':'transparent',color:niv===v?'#fff':'var(--text-body)'}}>{l}</button></Tooltip>)}</div>
      <div style={{display:'flex',alignItems:'center',height:36,border:'1px solid var(--border-default)',background:'var(--surface-card)',flex:'1 1 200px',maxWidth:340}}><Icon name="search" size={16} color="var(--text-subtle)" style={{marginLeft:10}}/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="Rechercher un repère" placeholder="Rechercher un repère" style={{all:'unset',flex:1,padding:'0 10px',font:'var(--type-body-sm)',color:'var(--text-body)'}}/>{q&&<button type="button" aria-label="Effacer la recherche" onClick={()=>setQ('')} style={{all:'unset',cursor:'pointer',width:36,height:36,display:'inline-flex',alignItems:'center',justifyContent:'center'}}><Icon name="x" size={14}/></button>}</div>
      <button type="button" aria-expanded={affiner} onClick={()=>setAffiner(!affiner)} style={chip(affiner||nActive>0)}><Icon name="sliders-horizontal" size={14}/>Affiner{nActive>0&&<span style={{background:'var(--cm-vert-800)',color:'#fff',minWidth:18,height:18,borderRadius:9,display:'inline-flex',alignItems:'center',justifyContent:'center',fontSize:11,padding:'0 5px'}}>{nActive}</span>}</button>
      <span style={{marginLeft:'auto',font:'var(--type-caption)',color:'var(--text-muted)',fontVariantNumeric:'tabular-nums'}} aria-live="polite"><b style={{color:'var(--text-heading)'}}>{list.length}</b> repère{list.length>1?'s':''} · {groups.length} période{groups.length>1?'s':''}</span>
      {nActive>0&&<div style={{flexBasis:'100%',display:'flex',gap:6,flexWrap:'wrap',alignItems:'center'}}>{FACETTES.flatMap(F=>(fac[F.k]||[]).map(v=>{const lab=Array.isArray(F.opts[0])?(F.opts.find(o=>o[0]===v)||[v,v])[1]:v;return <Tag key={F.k+v} size="sm" onRemove={()=>toggle(F.k,v)}>{F.l} : {lab}</Tag>;}))}<Button size="sm" variant="tertiary" onClick={()=>setFac({})}>Tout effacer</Button></div>}
      {affiner&&<div style={{flexBasis:'100%',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:8,paddingTop:8}}>{FACETTES.map(F=>{const o=openF===F.k;const sel=(fac[F.k]||[]).length;return <div key={F.k} style={{position:'relative'}}><button type="button" aria-expanded={o} onClick={()=>setOpenF(o?null:F.k)} style={chip(sel>0,{width:'100%',justifyContent:'space-between'})}>{F.l}{sel>0?' · '+sel:''}<Icon name={o?'chevron-up':'chevron-down'} size={14}/></button>
        {o&&<ul role="group" aria-label={F.l} style={{position:'absolute',top:'100%',left:0,zIndex:30,margin:'4px 0 0',padding:6,listStyle:'none',minWidth:230,background:'var(--surface-card)',border:'1px solid var(--border-default)',boxShadow:'var(--shadow-md)',display:'grid',gap:2}}>{F.opts.map(opt=>{const [v,lab]=Array.isArray(opt)?opt:[opt,opt];const n=count(F.k,v);const on=(fac[F.k]||[]).includes(v);return <li key={v}><label style={{display:'grid',gridTemplateColumns:'18px 1fr auto',alignItems:'center',gap:10,padding:'8px 10px',cursor:n||on?'pointer':'not-allowed',opacity:n||on?1:.45,font:'var(--type-body-sm)'}}><input type="checkbox" checked={on} disabled={!n&&!on} onChange={()=>toggle(F.k,v)} style={{width:18,height:18,margin:0,accentColor:'var(--cm-vert-800)'}}/><span style={{textTransform:'capitalize'}}>{lab}</span><span style={{font:'var(--type-mono)',fontSize:12,color:'var(--text-subtle)',fontVariantNumeric:'tabular-nums'}}>{n}</span></label></li>;})}</ul>}</div>;})}</div>}
    </Container></div>
    <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
      {list.length===0&&<div style={{padding:'var(--space-10)',textAlign:'center',color:'var(--text-muted)',border:'1px dashed var(--border-strong)'}}><Icon name="search-x" size={28}/><p style={{marginTop:8}}>Aucun repère ne correspond à ces critères.</p><Button variant="secondary" size="sm" onClick={()=>{setFac({});setQ('');setNiv(3);setEp('toutes');}} style={{marginTop:12}}>Réinitialiser les filtres</Button></div>}
      {groups.map(g=><section key={g.key} aria-label={g.key} style={{display:'grid',gridTemplateColumns:'minmax(100px,150px) 1fr',gap:'var(--space-6)',marginBottom:'var(--space-8)'}}>
        <h2 style={{font:'var(--type-h5)',color:'var(--text-muted)',position:'sticky',top:76,alignSelf:'start',fontFamily:'var(--font-display)',fontStretch:'85%',paddingTop:2}}>{g.key}</h2>
        {/* grille : colonne marqueur (ligne 2 px centrée) + contenu ; le marqueur est centré sur la ligne par construction */}
        <ol style={{margin:0,padding:0,listStyle:'none'}}>{g.items.map((e,i)=>{const key=e.an+e.t;const open=openItem===key;const c=epOf(e.ep).color;const last=i===g.items.length-1;return <li key={key} id={'rep-'+encodeURIComponent(key)} style={{display:'grid',gridTemplateColumns:M+' 1fr',columnGap:'var(--space-5)'}}>
          <div aria-hidden="true" style={{display:'grid',gridTemplateRows:'14px auto 1fr',justifyItems:'center'}}><span style={{width:'var(--marker-line)',background:'var(--border-default)',height:'100%'}}/><Marker type={e.type} nat={e.nat} color={c}/><span style={{width:'var(--marker-line)',background:last?'transparent':'var(--border-default)',height:'100%'}}/></div>
          <div style={{paddingBottom:'var(--space-5)',minWidth:0}}>
            <button type="button" aria-expanded={open} onClick={()=>setOpenItem(open?null:key)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'block',width:'100%',textAlign:'left',padding:'6px 0'}}>
              <div style={{display:'grid',gridTemplateColumns:'88px 1fr auto',gap:12,alignItems:'baseline'}}><span style={{font:'var(--type-mono)',fontWeight:500,color:c,fontVariantNumeric:'tabular-nums'}}>{fmtAn(e.an)}</span><span style={{font:'var(--type-h6)',color:'var(--text-heading)'}}>{e.t}</span><Icon name={open?'chevron-up':'chevron-down'} size={16} color="var(--text-subtle)"/></div>
              {!open&&!falc&&<div style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:4,paddingLeft:100,display:'-webkit-box',WebkitLineClamp:1,WebkitBoxOrient:'vertical',overflow:'hidden'}}>{e.d}</div>}
            </button>
            {open&&<div style={{marginTop:6,padding:'var(--space-4) var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderLeft:'4px solid '+c}}>
              <p style={{font:falc?'var(--type-lead)':'var(--type-body)',maxWidth:'var(--measure)'}}>{e.d}</p>
              <div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:12}}><Badge status="brand" size="sm">{epOf(e.ep).nom}</Badge><Badge size="sm">{e.th}</Badge><Badge size="sm">{e.ctx==='int'?'Vie intérieure':'Relations extérieures'}</Badge><Badge size="sm">{e.reg}</Badge><Badge status={e.nat==='tragique'?'error':e.nat==='heureux'?'success':'info'} size="sm">{e.nat}</Badge>{e.src&&<Badge status="warning" size="sm">source : {e.src}</Badge>}</div>
              <div style={{display:'flex',gap:8,marginTop:12,flexWrap:'wrap'}}>{e.type==='personnage'&&<Button size="sm" variant="secondary" iconRight="arrow-right" onClick={()=>go('personnages')}>Voir les personnages</Button>}{e.type==='monument'&&<Button size="sm" variant="secondary" iconRight="arrow-right" onClick={()=>go('monuments')}>Voir les monuments</Button>}<Button size="sm" variant="tertiary" iconLeft="book-open" onClick={()=>go('symboles','sources')}>Sources</Button><Button size="sm" variant="tertiary" iconLeft="flag">Signaler une erreur</Button><Button size="sm" variant="tertiary" iconLeft="link">Copier le lien</Button></div>
            </div>}
          </div>
        </li>;})}</ol>
      </section>)}
      <div style={{display:'flex',gap:20,flexWrap:'wrap',alignItems:'center',font:'var(--type-caption)',color:'var(--text-muted)',borderTop:'var(--hairline)',paddingTop:16}}><span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Marker type="événement" color="var(--cm-vert-700)"/>événement</span><span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Marker type="personnage" color="var(--cm-vert-700)"/>personnage</span><span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Marker type="traité" color="var(--cm-vert-700)"/>traité, loi</span><span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Marker type="monument" color="var(--cm-vert-700)"/>monument</span><span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Marker type="événement" nat="tragique" color="var(--cm-vert-700)"/>contour seul : épisode tragique</span><span style={{marginLeft:'auto'}}>Couleur = époque</span></div>
    </Container>
  </>;
}
Object.assign(window,{Frise});
