const __NS=window.SystMeDeDesignDeLTatDuCameroun_f51bf6||{};const {Header,Footer}=__NS;
const GovBar=__NS.GovBar||(()=>null);const AccessPanel=__NS.AccessPanel||(()=>null);const applyA11y=__NS.applyA11y||(()=>{});const readA11y=__NS.readA11y||(()=>({falc:false}));
const SITES=window.SITES_RESEAU||[];
const IMG={kribi:'https://images.unsplash.com/photo-1637244018403-785e7fa8707a?w=1600&q=75&fit=crop',paysage:'https://images.unsplash.com/photo-1615463668140-d294c94ec8ef?w=1200&q=75&fit=crop',nature:'https://images.unsplash.com/photo-1696541665406-a2517f84f934?w=1200&q=75&fit=crop',foumban:'https://images.unsplash.com/photo-1659947234294-b217aaeb25f8?w=1200&q=75&fit=crop',palais:'https://images.unsplash.com/photo-1659947234286-213fd15f0bcc?w=1200&q=75&fit=crop',art:'https://images.unsplash.com/photo-1659947234279-92bc8f2cd2fe?w=1200&q=75&fit=crop',douala:'https://images.unsplash.com/photo-1636385918427-7aa474ffa8ae?w=1200&q=75&fit=crop'};
const CREDIT={kribi:'Edouard Tamba / Unsplash',paysage:'Edouard Tamba / Unsplash',nature:'Christian Aime Nanga / Unsplash',foumban:'Ariel Nathan Ada Mbita / Unsplash',palais:'Ariel Nathan Ada Mbita / Unsplash',art:'Ariel Nathan Ada Mbita / Unsplash',douala:'Youssouf Nchetkou Ndam / Unsplash'};
const FRISE=[...(window.FRISE_1||[]),...(window.FRISE_2||[])].sort((a,b)=>a.an-b.an);
/* Images : Unsplash (IMG) ou Wikimedia Commons via Special:FilePath (fichier exact, licence affichée). */
const commons=(file,w=900)=>'https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(file)+'?width='+w;
const srcOf=(o,w)=>o.photo?commons(o.photo,w):o.img?IMG[o.img]:null;
const creditOf=o=>o.photo?o.photoCredit:o.img?CREDIT[o.img]:null;
const OR='#B98A00';/* or bronze : filets de finition */
/* Cartouche : portrait absent → monogramme sur ébène et motif ndop, filet or. Formel, jamais un visage inventé. */
const Cartouche=({nom,ratio='4/5',label='Portrait d’archives à fournir',style})=>{const ini=String(nom).split(/[\s-]+/).filter(w=>/^[A-ZÉÈÀÔ]/.test(w)).map(w=>w[0]).slice(0,3).join('');return <figure aria-label={label} style={{margin:0,position:'relative',aspectRatio:ratio,background:'var(--motif-ndop)',overflow:'hidden',display:'grid',placeItems:'center',...style}}><span aria-hidden="true" style={{position:'absolute',inset:6,border:'1px solid '+OR,opacity:.7}}/><span style={{fontFamily:'var(--font-display)',fontWeight:800,fontSize:'clamp(20px,30%,64px)',letterSpacing:'0.04em',color:'var(--cm-papier)',lineHeight:1}}>{ini}</span><figcaption style={{position:'absolute',left:0,right:0,bottom:0,padding:'6px 8px',font:'var(--type-caption)',fontWeight:500,color:'var(--cm-indigo-100)',textAlign:'center',background:'rgba(11,27,51,.55)'}}>{label}</figcaption></figure>;};
/* Portrait : photo si disponible, cartouche sinon */
const Portrait=({p,ratio='4/5',style})=>{const src=srcOf(p,700);return src?<Photo src={src} credit={creditOf(p)} ratio={ratio} style={style}/>:<Cartouche nom={p.nom} ratio={ratio} style={style}/>;};
/* Séparateur de section : filet or centré avec losange, à la manière d’un ornement typographique */
const Toghu=({style})=><div aria-hidden="true" style={{display:'grid',gridTemplateColumns:'1fr auto 1fr',alignItems:'center',gap:16,...style}}><span style={{height:1,background:'linear-gradient(90deg,transparent,'+OR+')'}}/><svg viewBox="0 0 100 100" width="12" height="12" aria-hidden="true"><polygon fill={OR} points="50,5 61.8,38.2 96.6,38.2 68.4,58.8 79.4,92 50,71.4 20.6,92 31.6,58.8 3.4,38.2 38.2,38.2"/></svg><span style={{height:1,background:'linear-gradient(90deg,'+OR+',transparent)'}}/></div>;
const ROMAN=['I','II','III','IV','V','VI','VII','VIII','IX','X'];
const NAVF=()=>[{value:'accueil',label:tr('Accueil','Home')},{value:'frise',label:tr('Frise','Timeline')},{value:'personnages',label:tr('Personnages','People')},{value:'monuments',label:tr('Monuments & lieux','Monuments & places')},{value:'regions',label:tr('Régions & peuples','Regions & peoples')},{value:'culture',label:tr('Culture vivante','Living culture')},{value:'symboles',label:tr('Symboles & valeurs','Symbols & values')}];
function Shell({page,go,falc,setFalc,children}){
  const [lang,setLang]=useLang();
  const [a11y,setA11y]=React.useState(false);
  React.useEffect(()=>{const p=readA11y();applyA11y(p);setFalc(!!p.falc);},[]);
  const active={personnage:'personnages',monument:'monuments',region:'regions'}[page]||page;
  const fp=footerProps({site:tr('Musée numérique du Cameroun','Digital Museum of Cameroon'),lang,desc:tr("Raconter l’histoire du Cameroun à partir des écrits, des archives et des documentaires. Un site du ministère des Arts et de la Culture. Chaque repère cite sa source ; chaque erreur peut être signalée.","Telling Cameroon’s history from writings, archives and documentaries. A site of the Ministry of Arts and Culture. Every milestone cites its source; every error can be reported.")});
  return <div style={{minHeight:'100vh',display:'flex',flexDirection:'column',background:'var(--surface-page)'}}>
    <a href="#main" style={{position:'absolute',left:-9999,top:8,zIndex:2000,background:'var(--a11y-skip-bg)',padding:'8px 12px',font:'var(--type-label)',color:'var(--a11y-skip-text)'}} onFocus={e=>{e.target.style.left='8px';}} onBlur={e=>{e.target.style.left='-9999px';}}>Aller au contenu</a>
    <GovBar ministry="musee" hubHref="../hub/index.html" sites={SITES} onSiteChange={id=>{const s=SITES.find(x=>x.id===id);if(s&&s.href)location.href=s.href;}} suggest={window.rechercher} onSearch={q=>location.href='../hub/index.html#recherche/'+encodeURIComponent(q)} onAccessibility={()=>setA11y(true)} lang={lang} onLangChange={setLang} onLogin={()=>{}}/>
    <Header compact showLogin={false} serviceName={tr('Musée numérique du Cameroun','Digital Museum of Cameroon')} tagline={tr('Ministère des Arts et de la Culture','Ministry of Arts and Culture')} nav={NAVF()} active={typeof activeNav!=='undefined'?activeNav:active} onNavigate={v=>go(v)}/>
    {falc&&<div role="status" style={{background:'var(--cm-jaune-100)',borderBottom:'1px solid var(--cm-jaune-300)',font:'var(--type-body-sm)',padding:'8px var(--gutter)',textAlign:'center'}}>Version <b>facile à lire</b> activée : textes courts, un message par paragraphe.</div>}
    <main id="main" style={{flex:1}}>{children}</main>
    <Footer {...fp}/>
    <AccessPanel open={a11y} onClose={()=>setA11y(false)} onChange={p=>setFalc(!!p.falc)}/>
  </div>;
}
const Container=({children,style})=><div style={{maxWidth:'var(--container-lg)',margin:'0 auto',padding:'0 var(--gutter)',boxSizing:'border-box',width:'100%',...style}}>{children}</div>;
const Overline=({children,color='var(--accent-laterite)',num,style})=><div style={{font:'var(--type-overline)',letterSpacing:'var(--tracking-caps)',textTransform:'uppercase',color,display:'flex',alignItems:'center',gap:10,flexWrap:'wrap',...style}}>{num!=null&&<span style={{fontFamily:'var(--font-display)',fontWeight:700,color:OR}}>{ROMAN[num-1]||num}</span>}{num!=null&&<span aria-hidden="true" style={{width:20,height:1,background:OR}}/>}<span>{children}</span></div>;
const SectionTitle=({children,overline,action,id,level=2,num,top})=><div id={id} style={{marginBottom:'var(--space-6)',marginTop:top?'var(--space-20)':0,display:'flex',alignItems:'flex-end',justifyContent:'space-between',gap:16,flexWrap:'wrap',scrollMarginTop:100}}><div>{overline&&<Overline num={num} style={{marginBottom:6}}>{overline}</Overline>}{level===1?<h1 style={{font:'var(--type-h2)'}}>{children}</h1>:<h2 style={{font:'var(--type-h3)'}}>{children}</h2>}<div aria-hidden="true" style={{height:'var(--rule-title)',width:'var(--rule-title-w)',background:'var(--brand-band)',marginTop:10}}/></div>{action}</div>;
const Photo=({src,credit,title,ratio='3/2',placeholder='Image à fournir (archives, MINAC)',alt,style,children})=><figure role="img" aria-label={alt||title||(src?(credit?'Photographie — '+credit:'Photographie'):placeholder)} style={{margin:0,position:'relative',aspectRatio:ratio,background:src?'var(--cm-gris-200) url('+src+') center/cover':'var(--motif-laterite)',overflow:'hidden',border:src?0:'1px solid var(--border-default)',...style}}>{src&&<div aria-hidden="true" style={{position:'absolute',inset:0,background:'var(--photo-protect)'}}/>}{!src&&<div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'center',padding:16}}>{placeholder}</div>}{credit&&<figcaption style={{position:'absolute',right:8,top:8,color:'#fff',font:'var(--type-caption)',fontWeight:500,background:'rgba(21,17,14,.6)',padding:'2px 6px'}}>© {credit}</figcaption>}{title&&<div style={{position:'absolute',left:16,bottom:14,color:'#fff',font:'var(--type-h5)'}}>{title}</div>}{children}</figure>;
const fmtAn=a=>a<0?Math.abs(a).toLocaleString('fr-FR').replace(/[\u202f\u00a0]/g,' ')+' av. J.-C.':String(a);
const epOf=id=>EPOQUES.find(x=>x.id===id)||EPOQUES[0];
/* Marqueur de frise : boîte fixe 12 px, formes centrées, sans transform décalant l'alignement */
const Marker=({type,nat,color,size=12})=>{const s={width:size,height:size,flex:'none',boxSizing:'border-box',display:'block'};const tragic=nat==='tragique';const fill=tragic?'var(--surface-card)':color;
  if(type==='personnage')return <span aria-hidden="true" style={{...s,position:'relative'}}><span style={{position:'absolute',inset:size*0.15,background:fill,border:'2px solid '+color,transform:'rotate(45deg)',boxSizing:'border-box'}}/></span>;
  if(type==='traité')return <span aria-hidden="true" style={{...s,borderRadius:'50%',background:fill,border:'2px solid '+color}}/>;
  if(type==='monument')return <span aria-hidden="true" style={{...s,background:fill,border:'2px solid '+color,clipPath:'polygon(50% 0,100% 100%,0 100%)'}}/>;
  return <span aria-hidden="true" style={{...s,background:fill,border:'2px solid '+color}}/>;};
Object.assign(window,{Shell,Container,Overline,SectionTitle,Photo,IMG,CREDIT,SITES,FRISE,fmtAn,epOf,Marker,NAVF,commons,srcOf,creditOf,Cartouche,Portrait,Toghu,OR,ROMAN});
