const {Button,Badge,Tag,Icon,Table,Alert}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
/* Cartes symboles : chaque visuel est construit (drapeau = géométrie officielle ; devise = typographie ; hymne = partition-texte ; armoiries = fiche héraldique, jamais un dessin). */
const Flag=({h=200})=><div role="img" aria-label="Drapeau du Cameroun : trois bandes verticales vert, rouge et jaune ; étoile d’or au centre de la bande rouge" style={{width:h*1.5,height:h,display:'grid',gridTemplateColumns:'1fr 1fr 1fr',boxShadow:'var(--shadow-sm)',border:'1px solid var(--border-default)'}}><div style={{background:'#007A5E'}}/><div style={{background:'#CE1126',display:'grid',placeItems:'center'}}><svg viewBox="0 0 100 100" width={h*0.38} height={h*0.38} aria-hidden="true"><polygon fill="#FCD116" points="50,5 61.8,38.2 96.6,38.2 68.4,58.8 79.4,92 50,71.4 20.6,92 31.6,58.8 3.4,38.2 38.2,38.2"/></svg></div><div style={{background:'#FCD116'}}/></div>;
function Symboles({go,focus,falc}){
  React.useEffect(()=>{if(focus){const el=document.getElementById('sym-'+focus);if(el)window.scrollTo({top:el.getBoundingClientRect().top+window.scrollY-90});}},[focus]);
  const S=id=>SYMBOLES.find(s=>s.id===id);
  const Card2=({id,children,visual,wide})=><article id={'sym-'+id} style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'2px solid '+OR,display:'grid',gridTemplateColumns:wide?'minmax(280px,1fr) minmax(0,1.4fr)':'1fr',gridColumn:wide?'1 / -1':'auto'}}><div style={{background:'var(--surface-page)',borderBottom:wide?0:'var(--hairline)',borderRight:wide?'var(--hairline)':0,display:'grid',placeItems:'center',padding:'var(--space-6)',minHeight:220,minWidth:0,overflow:'hidden'}}>{visual}</div><div style={{padding:'var(--space-6)',display:'grid',gap:10,alignContent:'start'}}><h2 style={{font:'var(--type-h5)'}}>{S(id).nom}</h2><p style={{font:falc?'var(--type-body)':'var(--type-body-sm)',maxWidth:'var(--measure)'}}>{S(id).d}</p>{children}</div></article>;
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Symboles & valeurs" num={1}>Ce qui nous rassemble</SectionTitle>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:'var(--space-6)'}}>
      <Card2 id="drapeau" wide visual={<Flag/>}><div style={{display:'flex',gap:16,flexWrap:'wrap',marginTop:4}}>{[['#007A5E','Vert','forêt, espérance'],['#CE1126','Rouge','unité, souveraineté'],['#FCD116','Jaune','savane, soleil']].map(([c,n,s])=><span key={n} style={{display:'inline-flex',gap:8,alignItems:'center',font:'var(--type-caption)'}}><span style={{width:14,height:14,background:c,border:'1px solid var(--border-default)'}}/><b>{n}</b><span style={{color:'var(--text-muted)'}}>{s}</span><span style={{fontFamily:'var(--font-mono)',color:'var(--text-subtle)'}}>{c}</span></span>)}</div></Card2>
      <Card2 id="armoiries" wide visual={<div style={{width:'100%',maxWidth:320,boxSizing:'border-box',display:'grid',gap:8}}><Overline color="var(--text-muted)">Fiche héraldique</Overline>{[['Écu','tiercé en pal vert, rouge, jaune',['#007A5E','#CE1126','#FCD116']],['Centre','carte du Cameroun, en bleu',['#254A85']],['Brochant','balance de la justice et glaive',[]],['En chef','étoile d’or',['#FCD116']],['Support','deux faisceaux de licteur croisés',['#6B3F2A']],['Listel','République du Cameroun · Paix – Travail – Patrie',[]]].map(([k,v,cs])=><div key={k} style={{display:'grid',gridTemplateColumns:'80px 1fr auto',gap:10,alignItems:'center',padding:'8px 0',borderBottom:'var(--hairline)',font:'var(--type-body-sm)'}}><b>{k}</b><span>{v}</span><span style={{display:'inline-flex',gap:3}}>{cs.map(c=><span key={c} style={{width:12,height:12,background:c}}/>)}</span></div>)}</div>}><Alert status="info" size="sm" title="Reproduction officielle uniquement">Le fichier vectoriel des armoiries est fourni par les services du Premier ministre ; le Musée ne publie aucune reconstitution. Emplacement prêt : 240 × 280 px, fond blanc, marge 24 px.</Alert></Card2>
      <Card2 id="hymne" wide visual={<div style={{width:'100%',maxWidth:360,boxSizing:'border-box',background:'var(--cm-ebene)',color:'var(--cm-papier)',padding:'var(--space-5)',display:'grid',gap:12,minWidth:0}}><Overline color="var(--cm-jaune-500)">Hymne national · 1928 → 1957</Overline><div style={{fontFamily:'var(--font-display)',fontWeight:700,fontSize:'var(--text-xl)',lineHeight:1.25}}>Ô Cameroun, berceau de nos ancêtres</div><div style={{font:'var(--type-body-sm)',color:'var(--cm-gris-300)',fontStyle:'italic'}}>O Cameroon, Thou Cradle of our Fathers</div><div style={{borderTop:'1px solid var(--cm-gris-800)',paddingTop:12,display:'grid',gridTemplateColumns:'auto 1fr',gap:'4px 12px',font:'var(--type-caption)',color:'var(--cm-gris-300)'}}><span>Musique</span><span style={{color:'var(--cm-papier)'}}>René Djam Afame</span><span>Paroles</span><span style={{color:'var(--cm-papier)'}}>S. Minkio Bamba, M. Nyatte Nko’o</span><span>Anglais</span><span style={{color:'var(--cm-papier)'}}>Bernard N. Fonlon</span><span>Lieu</span><span style={{color:'var(--cm-papier)'}}>École normale de Foulassi</span></div><Button size="sm" variant="inverse" iconLeft="play" disabled>Écouter — enregistrement officiel à fournir</Button></div>}/>
      <Card2 id="devise" visual={<div style={{display:'grid',gap:6,textAlign:'center'}}><div style={{fontFamily:'var(--font-display)',fontWeight:800,letterSpacing:'0.14em',textTransform:'uppercase',fontSize:'clamp(18px,2.4vw,26px)',display:'flex',gap:14,justifyContent:'center',flexWrap:'wrap'}}><span style={{color:'#007A5E'}}>Paix</span><span style={{color:'var(--text-subtle)'}}>–</span><span style={{color:'#CE1126'}}>Travail</span><span style={{color:'var(--text-subtle)'}}>–</span><span style={{color:'#B98A00'}}>Patrie</span></div><div style={{font:'var(--type-caption)',letterSpacing:'0.14em',textTransform:'uppercase',color:'var(--text-muted)'}}>Peace – Work – Fatherland</div><div aria-hidden="true" style={{height:3,width:96,background:'var(--brand-band)',margin:'8px auto 0'}}/></div>}/>
      <Card2 id="langues" visual={<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',width:'100%',maxWidth:280,boxSizing:'border-box',border:'var(--hairline)'}}><div style={{display:'grid',placeItems:'center',padding:24,background:'var(--surface-brand-soft)',fontFamily:'var(--font-display)',fontWeight:800,fontSize:'var(--text-4xl)',color:'var(--cm-vert-800)'}}>FR</div><div style={{display:'grid',placeItems:'center',padding:24,background:'var(--cm-indigo-50)',fontFamily:'var(--font-display)',fontWeight:800,fontSize:'var(--text-4xl)',color:'var(--cm-indigo-700)'}}>EN</div><div style={{gridColumn:'1 / -1',padding:'8px 12px',font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'center',borderTop:'var(--hairline)'}}>+ 250 langues nationales</div></div>}/>
      <Card2 id="sceau" visual={<div style={{display:'grid',gap:10,width:'100%',maxWidth:280,boxSizing:'border-box'}}>{[['Ordre de la Valeur','1957 · 5 grades'],['Ordre du Mérite camerounais','1972 · 4 grades'],['Médaille de la Vaillance','militaire']].map(([n,d])=><div key={n} style={{display:'grid',gridTemplateColumns:'8px 1fr',gap:12,alignItems:'center'}}><span style={{width:8,height:36,background:'var(--brand-band-v)'}}/><span><span style={{font:'var(--type-label)',fontWeight:600,display:'block'}}>{n}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{d}</span></span></div>)}</div>}/>
      <Card2 id="lion" visual={<div style={{width:'100%',boxSizing:'border-box',padding:24,background:'var(--motif-toghu)',display:'grid',placeItems:'center'}}><span style={{background:'var(--cm-ebene)',color:'var(--cm-jaune-500)',fontFamily:'var(--font-display)',fontWeight:800,fontSize:'var(--text-xl)',padding:'10px 18px',textTransform:'uppercase',letterSpacing:'0.06em'}}>Lions indomptables</span></div>}/>
    </div>
    <Toghu style={{marginTop:'var(--space-20)'}}/><SectionTitle top overline="Valeurs" num={2} id="sym-valeurs">Six valeurs, un récit</SectionTitle>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)'}}>{VALEURS.map((v,i)=><article key={v.id} id={'sym-'+v.id} style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid '+['#007A5E','#CE1126','#B98A00','#254A85','#6B3F2A','#A8452B'][i]}}><div style={{fontFamily:'var(--font-display)',fontWeight:800,fontSize:'var(--text-2xl)'}}>{v.nom}</div><p style={{font:'var(--type-body-sm)',marginTop:8}}>{v.d}</p></article>)}</div>
    <SectionTitle top overline="Célébrations" num={3} id="sym-fetes">Le calendrier de la nation</SectionTitle>
    <Table caption="Fêtes nationales, commémorations et grandes fêtes traditionnelles" columns={[{key:'0',label:'Date',mono:true},{key:'1',label:'Célébration',strong:true}]} rows={FETES}/>
    <Toghu style={{marginTop:'var(--space-20)'}}/><SectionTitle top overline="Bibliographie" num={4} id="sym-sources">Sources du musée</SectionTitle>
    <Table caption="Ouvrages, documentaires, archives et institutions cités" columns={[{key:'0',label:'Type',render:v=><Badge status={v==='Livre'?'brand':v==='Documentaire'?'info':v==='Archive'?'warning':'neutral'}>{v}</Badge>},{key:'1',label:'Référence',strong:true}]} rows={SOURCES}/>
    <p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:16,maxWidth:'70ch'}}>Chaque repère de la frise indique sa source principale. Les erreurs ou compléments se signalent depuis la fiche concernée ; les propositions sont examinées par le comité scientifique du musée avant publication.</p>
  </Container>;
}
Object.assign(window,{Symboles,Flag});
