const {Button,Badge,Stat,Tag,Icon,Table,Breadcrumb,Accordion,Stepper,Timeline,Field,Input,Select,Textarea,Checkbox,Switch,Alert}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
function Transactions({go}){
  const [an,setAn]=React.useState('2026');const [b,setB]=React.useState('Tous');
  const ben=['Tous',...new Set(TRANSACTIONS.map(t=>t.b))];const list=TRANSACTIONS.filter(t=>b==='Tous'||t.b===b);
  const total=list.filter(t=>t.statut==='Réglé').reduce((s,t)=>s+t.m,0);
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Mes paiements" num={1} action={<div style={{display:'flex',gap:8}}><Button variant="secondary" iconLeft="download">Relevé annuel (PDF)</Button><Button variant="tertiary" iconLeft="file-spreadsheet">Export CSV</Button></div>}>Tout ce que vous avez payé à l’État</SectionTitle>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-4)',marginBottom:'var(--space-6)'}}><Stat size="sm" value={fcfa(total)} label="réglés en 2026" accent="vert"/><Stat size="sm" value={list.length} label="opérations" accent="indigo"/><Stat size="sm" value={list.filter(t=>t.statut!=='Réglé'&&t.statut!=='Gratuit').length} label="en attente" accent="laterite"/><Stat size="sm" value="0" label="litige ouvert" accent="neutre"/></div>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:'var(--space-4)'}}>{ben.map(x=><Tag key={x} size="sm" selected={b===x} onClick={()=>setB(x)}>{x}</Tag>)}</div>
    <Table caption="Journal des paiements à l’État" columns={[{key:'date',label:'Date'},{key:'t',label:'Objet',strong:true},{key:'b',label:'Bénéficiaire'},{key:'moyen',label:'Moyen'},{key:'m',label:'Montant',align:'right',render:v=><Money v={v}/>},{key:'statut',label:'Statut',render:v=><Badge status={v==='Réglé'?'success':v==='Gratuit'?'neutral':'warning'} size="sm">{v}</Badge>},{key:'id',label:'Quittance',render:(v,r)=><Button size="sm" variant="tertiary" iconRight="chevron-right" onClick={()=>go('quittance',v)}>Voir</Button>}]} rows={list}/>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:16,maxWidth:'70ch'}}>Chaque ligne est ancrée dans le registre d’intégrité du Trésor : l’empreinte figure sur la quittance et peut être vérifiée par un tiers sans accès à vos données.</p>
  </Container>;
}
function QuittanceP({go,id}){
  const t=TRANSACTIONS.find(x=>x.id===id)||TRANSACTIONS[0];
  return <Container style={{padding:'var(--space-8) var(--gutter) var(--space-16)'}}>
    <Breadcrumb items={[{label:'Accueil',href:'#'},{label:'Mes paiements',href:'#'},{label:t.id}]}/>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',marginTop:'var(--space-8)',alignItems:'start'}}>
      <div><Alert status="success" title="Paiement enregistré" style={{marginBottom:'var(--space-6)'}}>La quittance a été transmise à {t.b}. Votre démarche liée avance automatiquement ; une copie est dans votre coffre.</Alert>
        <Quittance t={t}/>
        <h2 style={{font:'var(--type-h4)',marginTop:'var(--space-10)'}}>Traçabilité</h2>
        <Timeline style={{marginTop:12}} items={[{title:'Montant affiché depuis le barème',when:t.date,status:'done',description:'Aucune saisie manuelle du montant.'},{title:'Paiement confirmé par '+t.moyen,when:t.date,status:'done'},{title:'Quittance émise et empreinte ancrée',when:t.date,status:'done',description:'Empreinte '+t.hash+' inscrite au registre d’intégrité (Trésor, DGI, bénéficiaire).'},{title:'Transmis à '+t.b,when:t.date,status:'done',description:'Le service voit le paiement ; vous n’avez rien à présenter.'},{title:'Reversement aux bénéficiaires',when:'J+1',status:t.statut==='Réglé'?'done':'todo',description:t.red.join(' · ')}]}/>
      </div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline>Où va cet argent</Overline><div style={{display:'grid',gap:8,marginTop:10}}>{t.red.map(r=>{const p=parseInt((r.match(/(\d+) %/)||[0,100])[1]);return <div key={r}><div style={{display:'flex',justifyContent:'space-between',font:'var(--type-body-sm)'}}><span>{r.replace(/ \d+ %/,'')}</span><span style={{fontFamily:'var(--font-mono)'}}>{p} %</span></div><div style={{height:4,background:'var(--cm-gris-100)',marginTop:4}}><div style={{height:'100%',width:p+'%',background:'var(--cm-vert-800)'}}/></div></div>;})}</div></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-jaune-50)'}}><Overline color="var(--cm-jaune-800)">Un problème sur ce paiement ?</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Montant différent de celui exigé sur place, service non rendu, double paiement : signalez-le avec cette quittance comme preuve.</p><Button size="sm" variant="danger" iconLeft="flag" onClick={()=>go('signaler',t.id)} style={{marginTop:10}}>Signaler</Button></div>
        <Button variant="secondary" iconLeft="arrow-left" onClick={()=>go('transactions')}>Mes paiements</Button>
      </aside>
    </div>
  </Container>;
}
function Redistribution(){
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Transparence" num={1}>Où va l’argent</SectionTitle>
    <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>Le Trésor collecte pour tous les services de l’État, puis redistribue selon les textes. Chaque quittance indique sa répartition ; chaque bénéficiaire reçoit les données utiles à son contexte (le service voit « payé », pas votre relevé). Les agrégats sont publiés en données ouvertes.</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:'var(--space-4)',marginTop:'var(--space-8)'}}>{REDIST.map(([t,src,g],i)=><article key={t} style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid '+['var(--cm-vert-800)','var(--cm-laterite-600)','var(--cm-indigo-600)','var(--cm-kola-600)','var(--cm-jaune-600)','var(--cm-rouge-600)'][i]}}><div style={{padding:'var(--space-5)'}}><h2 style={{font:'var(--type-h5)'}}>{t}</h2><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:6,textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>Ressources</div><p style={{font:'var(--type-body-sm)',marginTop:2}}>{src}</p><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:10,textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>Gestionnaire</div><p style={{font:'var(--type-body-sm)',marginTop:2}}>{g}</p></div></article>)}</div>
    <h2 style={{font:'var(--type-h4)',marginTop:'var(--space-16)'}}>Ce que chaque service reçoit du Trésor</h2>
    <Table style={{marginTop:12}} caption="Données partagées selon le contexte (principe de minimisation)" columns={[{key:'0',label:'Destinataire',strong:true},{key:'1',label:'Reçoit'},{key:'2',label:'Ne reçoit pas'}]} rows={[['Service instructeur (DGSN, commune, école…)','Statut « payé », référence du dossier, montant, date','Votre relevé, vos autres paiements'],['DGI','Paiements fiscaux rattachés au NIU','Péages, timbres communaux, santé'],['Commune','Timbres et taxes locales, agrégés et par dossier','Impôts nationaux'],['Fonds routier','Agrégats de péage par poste et par jour','Identité des usagers'],['Vous','Tout, quittances et répartitions','—'],['Public (données ouvertes)','Agrégats mensuels par service et par région','Toute donnée nominative']]}/>
  </Container>;
}
function Signaler({go,quittance}){
  const [anon,setAnon]=React.useState(false);const [type,setType]=React.useState(SIGNALEMENTS_TYPES[0]);const [sent,setSent]=React.useState(false);const [where,setWhere]=React.useState('');const [txt,setTxt]=React.useState('');
  if(sent)return <Container style={{padding:'var(--space-12) var(--gutter) var(--space-20)',maxWidth:760}}><div style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)',padding:'var(--space-8)',display:'grid',gap:16}}><Icon name="shield-check" size={32} color="var(--cm-vert-800)"/><h1 style={{font:'var(--type-h3)'}}>Signalement reçu</h1><p>Numéro de suivi <b style={{fontFamily:'var(--font-mono)'}}>SG-2026-09-20-04471</b>. Conservez-le : il permet de suivre le traitement et d’ajouter des preuves, même en anonyme. Les signalements sont transmis à la cellule intégrité du Trésor et, selon la gravité, à la CONAC ou à l’ANIF.</p><Timeline items={[{title:'Reçu et horodaté',status:'done',when:'aujourd’hui'},{title:'Analyse par la cellule intégrité',status:'current',when:'sous 5 jours ouvrés'},{title:'Transmission CONAC / ANIF si nécessaire',status:'todo'},{title:'Réponse sur le suivi',status:'todo',when:'sous 30 jours'}]}/><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Button variant="secondary" onClick={()=>go('accueil')}>Retour à l’accueil</Button><Button variant="tertiary" iconLeft="printer">Imprimer le récépissé</Button></div></div></Container>;
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)',display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}>
    <div><SectionTitle level={1} overline="Intégrité" num={1}>Signaler un abus ou une corruption</SectionTitle>
      <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>Un frais hors barème, un paiement en espèces sans quittance, un « geste » demandé : chaque signalement compte. Vous pouvez rester anonyme ; les preuves sont chiffrées et les métadonnées des fichiers sont retirées.</p>
      <div style={{background:'var(--surface-card)',border:'var(--hairline)',marginTop:'var(--space-6)'}}>
        <div style={{padding:'var(--space-5) var(--space-6)',borderBottom:'var(--hairline)',display:'flex',gap:16,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'}}><div><div style={{font:'var(--type-h6)'}}>{anon?'Signalement anonyme':'Signalement identifié'}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:2}}>{anon?'Aucune donnée d’identité n’est enregistrée ; vous suivez le dossier avec le numéro remis.':'Votre identité est connue de la seule cellule intégrité ; vous êtes protégé·e par la loi sur les lanceurs d’alerte.'}</div></div><Switch checked={anon} onChange={setAnon} label="Rester anonyme"/></div>
        <div style={{padding:'var(--space-6)',display:'grid',gap:'var(--space-5)'}}>
          <Field label="Nature des faits" required htmlFor="type"><Select id="type" value={type} onChange={e=>setType(e.target.value)} options={SIGNALEMENTS_TYPES}/></Field>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'var(--space-4)'}}><Field label="Lieu ou service" hint="Guichet, poste de péage, commissariat, hôpital…" required htmlFor="where"><Input id="where" value={where} onChange={e=>setWhere(e.target.value)} iconLeft="map-pin" placeholder="ex. poste de péage de Nkometou"/></Field><Field label="Date des faits" htmlFor="when"><Input id="when" type="date"/></Field></div>
          <Field label="Quittance ou dossier concerné" hint="Facultatif — une quittance jointe fait preuve du montant réellement payé." htmlFor="q"><Input id="q" defaultValue={quittance||''} placeholder="TR-2026-… ou D-2026-…" style={{fontFamily:'var(--font-mono)'}}/></Field>
          <Field label="Description des faits" hint="Ce qui a été demandé, par qui (fonction, pas nécessairement le nom), le montant, ce que vous avez fait." required htmlFor="txt"><Textarea id="txt" rows={5} value={txt} onChange={e=>setTxt(e.target.value)} placeholder="Le 15 septembre à 9 h, au poste de …"/></Field>
          <div><div style={{font:'var(--type-label)',fontWeight:600,marginBottom:6}}>Preuves</div><div style={{border:'2px dashed var(--border-strong)',padding:'var(--space-6)',display:'grid',justifyItems:'center',gap:8,textAlign:'center'}}><Icon name="upload" size={22} color="var(--text-muted)"/><div style={{font:'var(--type-body-sm)'}}>Photos, reçus manuscrits, enregistrements, captures d’écran</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>Jusqu’à 10 fichiers · 50 Mo · métadonnées (lieu, appareil) retirées automatiquement</div><Button size="sm" variant="secondary">Choisir des fichiers</Button></div></div>
          {!anon&&<Checkbox label="J’accepte d’être recontacté·e par la cellule intégrité pour préciser les faits" hint="Par le canal sécurisé de votre compte, jamais par téléphone non identifié."/>}
          <Checkbox label="Je déclare les faits de bonne foi" hint="Un signalement de bonne foi ne peut donner lieu à aucune poursuite, même s’il n’est pas confirmé."/>
        </div>
        <div style={{padding:'var(--space-4) var(--space-6)',borderTop:'var(--hairline)',display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><span style={{font:'var(--type-caption)',color:'var(--text-muted)',display:'inline-flex',gap:6,alignItems:'center'}}><Icon name="lock" size={12}/>Chiffré ; transmis à la cellule intégrité, CONAC, ANIF</span><Button size="lg" variant="danger" iconLeft="flag" onClick={()=>setSent(true)}>Envoyer le signalement</Button></div>
      </div></div>
    <aside style={{display:'grid',gap:'var(--space-4)'}}>
      <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-ebene)',color:'#fff',borderTop:'2px solid '+OR}}><Overline color="var(--cm-jaune-500)">Vos droits</Overline><ul style={{margin:'10px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)',color:'var(--cm-gris-200)'}}><li>Refuser tout paiement hors barème ou sans quittance.</li><li>Exiger le nom de la structure et le numéro de l’avis.</li><li>Signaler anonymement, avec suivi.</li><li>Être protégé·e contre toute représaille (loi lanceurs d’alerte, CONAC).</li></ul></div>
      <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Autres canaux</Overline><div style={{display:'grid',gap:6,marginTop:10,font:'var(--type-body-sm)'}}><span><b style={{fontFamily:'var(--font-mono)'}}>1517</b> — CONAC, ligne verte</span><span><b style={{fontFamily:'var(--font-mono)'}}>8100</b> — Cameroun numérique</span><span>Boîte à signalement dans chaque guichet</span></div></div>
      <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Suivre un signalement</Overline><div style={{display:'flex',gap:8,marginTop:10}}><Input placeholder="SG-2026-…" size="sm" style={{fontFamily:'var(--font-mono)'}}/><Button size="sm" variant="secondary">Suivre</Button></div></div>
    </aside>
  </Container>;
}
Object.assign(window,{Transactions,QuittanceP,Redistribution,Signaler});
