const {Button,Badge,Stat,SearchBar,Tag,Icon,Table,Breadcrumb,Accordion,Stepper,Timeline,Field,Input,Select,Textarea,Checkbox,Radio,RadioGroup,Switch,Alert}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
function Accueil({go,falc}){
  const [q,setQ]=React.useState('');const total=TRANSACTIONS.filter(t=>t.statut==='Réglé').reduce((s,t)=>s+t.m,0);
  return <>
    <section style={{background:'var(--cm-ebene)',color:'#fff',position:'relative',isolation:'isolate'}}><div aria-hidden="true" style={{position:'absolute',inset:0,background:'var(--motif-ndop)',opacity:.3,overflow:'hidden',zIndex:-1}}/>
      <Container style={{position:'relative',padding:'var(--space-16) var(--gutter) var(--space-12)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'end'}}>
        <div><Overline color="var(--cm-jaune-500)">{tr('Trésor public · Paiements de l’État','Public Treasury · State payments')}</Overline><div aria-hidden="true" style={{width:48,height:1,background:OR,margin:'14px 0 0'}}/><h1 style={{font:'var(--type-display)',color:'#fff',fontSize:'clamp(2.25rem,5vw,3.75rem)',marginTop:14,letterSpacing:'var(--tracking-tight)'}}>{falc?tr('Payer l’État, sans surprise.','Pay the State, no surprises.'):tr('Le prix avant. La quittance après. Chaque franc tracé.','The price before. The receipt after. Every franc traced.')}</h1><p style={{font:'var(--type-lead)',color:'var(--cm-gris-200)',maxWidth:'52ch',marginTop:14}}>Tous les paiements dus à l’État — timbres, taxes, péages, frais de procédure, amendes — au même endroit, avec les moyens de paiement légaux, un reçu certifié et la destination de l’argent.</p>
          <RechercheGlobale placeholder="Combien coûte… ? ex. passeport, péage, timbre, permis de construire" label="Consulter un frais ou rechercher un service" onSubmit={q=>go('frais',q)} style={{marginTop:28,maxWidth:680}} exemples={['Passeport','CNI','Péage','Timbre fiscal','Casier judiciaire','e-Visa']}/></div>
        <div style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.2)',borderTop:'2px solid '+OR,padding:'var(--space-6)',display:'grid',gap:12}}><Overline color="var(--cm-jaune-500)">Trois garanties</Overline>{[['search-check','Le prix est public et unique','Le barème officiel s’affiche avant tout paiement. Rien d’autre n’est dû.'],['receipt','Une quittance certifiée, toujours','Numéro unique, empreinte ancrée, vérifiable par quiconque en 3 secondes.'],['route','Vous voyez où va l’argent','Chaque paiement indique sa répartition entre bénéficiaires.']].map(([ic,t,d])=><div key={t} style={{display:'grid',gridTemplateColumns:'20px 1fr',gap:12}}><Icon name={ic} size={18} color="var(--cm-jaune-500)"/><div><div style={{font:'var(--type-label)',fontWeight:700,color:'#fff'}}>{t}</div><div style={{font:'var(--type-caption)',color:'var(--cm-gris-300)',marginTop:2}}>{d}</div></div></div>)}</div>
      </Container></section>
    <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',borderTop:'2px solid '+OR}}><Container style={{padding:'var(--space-8) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-6)'}}><Stat size="sm" value={FRAIS.length} label="frais référencés" detail="barèmes officiels" accent="vert"/><Stat size="sm" value={MOYENS.length} label="moyens de paiement" detail="tous légaux, 0 frais mobile" accent="kola"/><Stat size="sm" value="3 s" label="pour vérifier une quittance" accent="indigo"/><Stat size="sm" value="100 %" label="des paiements tracés" detail="registre d’intégrité" accent="laterite"/><Stat size="sm" value="Anonyme" label="signalement possible" detail="CONAC · ANIF" accent="neutre"/></Container></section>
    <Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'start'}}>
      <div><SectionTitle overline="Payer" num={1}>Trois façons de régler</SectionTitle><div style={{display:'grid',gap:'var(--space-3)'}}>{[['qr-code','Je tiens un dossier ou un avis','Scannez le QR ou saisissez la référence D-… : le montant exact s’affiche, déjà rattaché au bon bénéficiaire.','payer','dossier'],['list','Je choisis un frais dans le barème','Péage, timbre, frais de procédure : sélectionnez, payez, la quittance est émise au nom de votre identité.','payer','bareme'],['building','Je paie au guichet','Espèces au Trésor, en banque partenaire ou à CAMPOST : présentez le QR ; la quittance numérique arrive sur votre compte.','payer','guichet']].map(([ic,t,d,p,a])=><button key={t} type="button" onClick={()=>go(p,a)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'44px 1fr 16px',gap:14,alignItems:'center',padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',textAlign:'left'}}><span style={{width:44,height:44,background:'var(--surface-brand-soft)',display:'grid',placeItems:'center'}}><Icon name={ic} size={20} color="var(--cm-vert-800)"/></span><span><span style={{font:'var(--type-h6)',display:'block'}}>{t}</span><span style={{font:'var(--type-body-sm)',color:'var(--text-muted)',display:'block',marginTop:4}}>{d}</span></span><Icon name="chevron-right" size={16} color="var(--text-subtle)"/></button>)}</div>
        <SectionTitle overline="Moyens de paiement" num={2} top><span>Tous légaux, tous tracés</span></SectionTitle>
        <Table caption="Moyens de paiement autorisés" columns={[{key:'nom',label:'Moyen',strong:true,render:(v,r)=><span style={{display:'inline-flex',gap:8,alignItems:'center'}}><Icon name={r.icon} size={16} color="var(--cm-vert-800)"/>{v}</span>},{key:'frais',label:'Frais pour vous'},{key:'delai',label:'Délai'},{key:'note',label:'Note'}]} rows={MOYENS}/></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}>
        <div style={{border:'var(--hairline)',borderTop:'4px solid var(--cm-ebene)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline>Dernière quittance</Overline><div style={{marginTop:10,font:'var(--type-h6)'}}>{TRANSACTIONS[0].t}</div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:2,fontFamily:'var(--font-mono)'}}>{TRANSACTIONS[0].id}</div><Money v={TRANSACTIONS[0].m} style={{display:'block',font:'var(--type-h4)',fontFamily:'var(--font-mono)',marginTop:8}}/><Button size="sm" variant="tertiary" iconRight="arrow-right" onClick={()=>go('transactions')} style={{marginTop:8}}>Mes paiements · {fcfa(total)} cette année</Button></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-jaune-50)'}}><Overline color="var(--cm-jaune-800)">On vous demande plus que le barème ?</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Refusez, gardez la preuve, signalez. Anonymement si vous le souhaitez ; vous recevez un numéro de suivi.</p><Button size="sm" variant="danger" iconLeft="flag" onClick={()=>go('signaler')} style={{marginTop:10}}>Signaler un abus</Button></div>
        <div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Vérifier une quittance</Overline><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:8}}>Employeur, école, notaire : saisissez le numéro pour confirmer qu’un paiement est réel.</p><div style={{display:'flex',gap:8,marginTop:10}}><Input placeholder="TR-2026-…" size="sm" style={{fontFamily:'var(--font-mono)'}}/><Button size="sm" variant="secondary">Vérifier</Button></div></div>
      </aside>
    </Container>
  </>;
}
function Frais({go,query}){
  const [q,setQ]=React.useState(query||'');const [cat,setCat]=React.useState('Tous');
  const list=FRAIS.filter(f=>(cat==='Tous'||f.cat===cat)&&(!q||(f.t+' '+f.b+' '+f.cat).toLowerCase().includes(q.toLowerCase())));
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Barème" num={1}>Combien ça coûte, avant de payer</SectionTitle>
    <p style={{color:'var(--text-muted)',maxWidth:'70ch',marginTop:-8}}>Les montants proviennent des textes cités (Code général des impôts, décrets, arrêtés, délibérations). Un montant absent ou différent sur place est un motif de signalement.</p>
    <SearchBar value={q} onChange={setQ} onSubmit={()=>{}} placeholder="ex. passeport, péage, timbre" label="Rechercher un frais" style={{maxWidth:520,marginTop:'var(--space-6)'}}/>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:12}}>{CATS.map(c=><Tag key={c} selected={cat===c} onClick={()=>setCat(c)}>{c}</Tag>)}</div>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:14}} aria-live="polite">{list.length} frais</p>
    <div style={{marginTop:'var(--space-4)'}}><Table caption="Barème des frais et taxes" columns={[{key:'t',label:'Frais',strong:true},{key:'cat',label:'Catégorie',render:v=><Badge size="sm">{v}</Badge>},{key:'m',label:'Montant',mono:true},{key:'ref',label:'Texte',render:v=><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{v}</span>},{key:'b',label:'Bénéficiaire'},{key:'x',label:'',align:'right',render:(_,r)=><Button size="sm" variant="tertiary" iconRight="arrow-right" onClick={()=>go('payer','bareme',r.t)}>Payer</Button>}]} rows={list}/></div>
  </Container>;
}
function Payer({go,mode,preset,user}){
  const [m,setM]=React.useState(mode||'dossier');const [step,setStep]=React.useState(1);const [ref,setRef]=React.useState('');const [frais,setFrais]=React.useState(preset||FRAIS[8].t);const [moyen,setMoyen]=React.useState('momo');const [tel,setTel]=React.useState('');
  const f=FRAIS.find(x=>x.t===frais)||FRAIS[8];const montant=m==='dossier'?2800:(parseInt((f.m.match(/\d[\d\s]*/)||['500'])[0].replace(/\s/g,''))||500);
  const chosen=MOYENS.find(x=>x.id===moyen);
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)',display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}>
    <div><SectionTitle level={1} overline="Payer" num={1}>Un paiement en trois étapes</SectionTitle>
      <div role="tablist" style={{display:'inline-flex',border:'1px solid var(--border-default)',background:'var(--surface-card)',marginBottom:'var(--space-6)'}}>{[['dossier','Dossier / avis'],['bareme','Barème'],['guichet','Au guichet']].map(([v,l])=><button key={v} type="button" role="tab" aria-selected={m===v} onClick={()=>{setM(v);setStep(1);}} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',height:40,padding:'0 16px',font:'var(--type-label)',fontWeight:600,background:m===v?'var(--cm-vert-800)':'transparent',color:m===v?'#fff':'var(--text-body)'}}>{l}</button>)}</div>
      <div style={{background:'var(--surface-card)',border:'var(--hairline)'}}>
        <div style={{padding:'var(--space-6)',borderBottom:'var(--hairline)'}}><Stepper steps={['Quoi','Comment','Confirmer']} current={step}/></div>
        <div style={{padding:'var(--space-6)',display:'grid',gap:'var(--space-5)'}}>
          {step===1&&m==='dossier'&&<><Field label="Référence du dossier ou de l’avis" hint="Sur votre convocation, votre avis d’imposition ou dans votre compte citoyen." required htmlFor="ref"><Input id="ref" size="lg" value={ref} onChange={e=>setRef(e.target.value)} iconLeft="qr-code" placeholder="D-2026-… ou scanner le QR" style={{fontFamily:'var(--font-mono)'}}/></Field><Alert status="info" size="sm" title="Dossier reconnu : CNI-2026-113-4482">Renouvellement de la carte nationale d’identité — DGSN. Montant dû : <Money v={2800}/>. Aucun autre frais.</Alert></>}
          {step===1&&m==='bareme'&&<><Field label="Frais à régler" required htmlFor="frais"><Select id="frais" value={frais} onChange={e=>setFrais(e.target.value)} options={FRAIS.map(x=>x.t)}/></Field><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12,padding:'var(--space-4)',background:'var(--surface-page)',border:'var(--hairline)'}}>{[['Montant',f.m],['Texte',f.ref],['Bénéficiaire',f.b]].map(([k,v])=><div key={k}><div style={{font:'var(--type-caption)',color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>{k}</div><div style={{font:'var(--type-label)',fontWeight:600,marginTop:2}}>{v}</div></div>)}</div></>}
          {step===1&&m==='guichet'&&<><p>Présentez ce QR au guichet du Trésor, d’une banque partenaire ou de CAMPOST. L’agent encaisse le montant exact ; votre quittance numérique arrive dans votre compte dès l’encaissement.</p><div style={{display:'grid',gridTemplateColumns:'auto 1fr',gap:20,alignItems:'center',padding:'var(--space-5)',border:'var(--hairline)',background:'var(--surface-page)'}}><div aria-label="Code QR du dossier" role="img" style={{width:120,height:120,background:'repeating-conic-gradient(var(--cm-ebene) 0 25%,transparent 0 50%) 0 0/20px 20px',border:'6px solid #fff',outline:'1px solid var(--border-default)'}}/><div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>Référence</div><div style={{font:'var(--type-h5)',fontFamily:'var(--font-mono)'}}>D-2026-113-4482</div><div style={{marginTop:8}}>Montant dû : <Money v={2800} style={{fontWeight:700}}/></div><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:4}}>Valable 30 jours · l’agent ne peut pas modifier le montant.</div></div></div></>}
          {step===2&&<><fieldset style={{border:0,padding:0,margin:0}}><legend style={{font:'var(--type-label)',fontWeight:600,marginBottom:8}}>Moyen de paiement</legend><div role="radiogroup" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:8}}>{MOYENS.filter(x=>m==='guichet'?['guichet','campost','cheque'].includes(x.id):!['guichet'].includes(x.id)).map(x=><button key={x.id} type="button" role="radio" aria-checked={moyen===x.id} onClick={()=>setMoyen(x.id)} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'20px 1fr',gap:10,alignItems:'start',padding:'12px 14px',border:'2px solid '+(moyen===x.id?'var(--cm-vert-800)':'var(--border-default)'),background:moyen===x.id?'var(--surface-brand-soft)':'transparent',textAlign:'left'}}><Icon name={x.icon} size={18} color={moyen===x.id?'var(--cm-vert-800)':'var(--text-muted)'}/><span><span style={{font:'var(--type-label)',fontWeight:600,display:'block'}}>{x.nom}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)'}}>{x.frais} · {x.delai}</span></span></button>)}</div></fieldset>{(moyen==='momo'||moyen==='om')&&<Field label="Numéro de téléphone" hint="Vous confirmerez sur votre téléphone avec votre code Mobile Money. Nous ne le demandons jamais." required htmlFor="tel"><Input id="tel" size="lg" value={tel} onChange={e=>setTel(e.target.value)} inputMode="tel" placeholder="6•• ••• •••"/></Field>}</>}
          {step===3&&<><div style={{display:'grid',gap:2}}>{[['Objet',m==='dossier'?'Renouvellement CNI — CNI-2026-113-4482':f.t],['Bénéficiaire',m==='dossier'?'DGSN':f.b],['Moyen',chosen.nom],['Frais de transaction',chosen.frais],['Payé par',user?user.name:'Identité Cameroun requise']].map(([k,v])=><div key={k} style={{display:'grid',gridTemplateColumns:'160px 1fr',gap:12,padding:'10px 0',borderBottom:'var(--hairline)',font:'var(--type-body-sm)'}}><span style={{color:'var(--text-muted)'}}>{k}</span><span style={{fontWeight:600}}>{v}</span></div>)}<div style={{display:'grid',gridTemplateColumns:'160px 1fr',gap:12,padding:'14px 0',font:'var(--type-body)'}}><span style={{fontWeight:700}}>Total à payer</span><Money v={montant} style={{font:'var(--type-h4)',fontFamily:'var(--font-mono)'}}/></div></div><Checkbox label="J’ai vérifié le montant. Il correspond au barème affiché." hint="Aucun autre frais ne peut vous être demandé pour cet acte."/></>}
        </div>
        <div style={{padding:'var(--space-4) var(--space-6)',borderTop:'var(--hairline)',display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><Button variant="tertiary" iconLeft="arrow-left" disabled={step===1} onClick={()=>setStep(step-1)}>Précédent</Button>{step<3?<Button size="lg" iconRight="arrow-right" onClick={()=>setStep(step+1)}>Continuer</Button>:<Button size="lg" iconLeft="lock" onClick={()=>go('quittance',TRANSACTIONS[2].id)}>Payer {fcfa(montant)}</Button>}</div>
      </div></div>
    <aside style={{display:'grid',gap:'var(--space-4)'}}>
      <div style={{border:'var(--hairline)',borderTop:'4px solid var(--cm-ebene)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline>Récapitulatif</Overline><div style={{marginTop:10,font:'var(--type-h6)'}}>{m==='dossier'||m==='guichet'?'Renouvellement CNI':f.t}</div><Money v={montant} style={{display:'block',font:'var(--type-h3)',fontFamily:'var(--font-mono)',marginTop:6}}/><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:6}}>Bénéficiaire : {m==='dossier'||m==='guichet'?'DGSN':f.b}</div><div style={{marginTop:12,display:'grid',gap:6,font:'var(--type-caption)'}}>{['Montant conforme au barème','Frais mobile pris en charge par l’État','Quittance émise instantanément'].map(x=><span key={x} style={{display:'inline-flex',gap:6,alignItems:'center'}}><Icon name="check" size={12} color="var(--cm-vert-800)"/>{x}</span>)}</div></div>
      <div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-jaune-50)'}}><Overline color="var(--cm-jaune-800)">Après le paiement</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>La quittance est transmise au service concerné : votre démarche avance sans que vous ayez à la présenter. Elle reste dans votre coffre, vérifiable par son numéro.</p></div>
    </aside>
  </Container>;
}
Object.assign(window,{Accueil,Frais,Payer});
