const __NS=window.SystMeDeDesignDeLTatDuCameroun_f51bf6||{};const {Header,Footer,Button,Card,Badge,Stat,SearchBar,Tag,Icon,Table,Breadcrumb,Accordion,Tabs,Stepper,Timeline,Field,Input,Select,Textarea,Checkbox,Radio,RadioGroup,Switch,Alert,IconButton}=__NS;
const GovBar=__NS.GovBar||(()=>null);const AccessPanel=__NS.AccessPanel||(()=>null);const applyA11y=__NS.applyA11y||(()=>{});const readA11y=__NS.readA11y||(()=>({falc:false}));
const OR='#B98A00';
const SITES=window.SITES_RESEAU||[];
const LINKS={hub:'../hub/index.html',presidence:'../presidence/index.html',sports:'../sports/index.html',tresor:'../tresor/index.html',musee:'../musee/index.html',impots:'../ministeres/index.html#minfi',tourisme:'../ministeres/index.html#mintoul'};
const NAVF=()=>[{value:'accueil',label:tr('Accueil','Home')},{value:'frais',label:tr('Consulter les frais','Fee schedule')},{value:'payer',label:tr('Payer','Pay')},{value:'transactions',label:tr('Mes paiements','My payments')},{value:'redistribution',label:tr('Où va l’argent','Where the money goes')},{value:'signaler',label:tr('Signaler un abus','Report abuse')}];
const Container=({children,style})=><div style={{maxWidth:'var(--container-lg)',margin:'0 auto',padding:'0 var(--gutter)',boxSizing:'border-box',width:'100%',...style}}>{children}</div>;
const ROMAN=['I','II','III','IV','V','VI','VII','VIII'];
const Overline=({children,color='var(--accent-laterite)',num,style})=><div style={{font:'var(--type-overline)',letterSpacing:'var(--tracking-caps)',textTransform:'uppercase',color,display:'flex',alignItems:'center',gap:10,flexWrap:'wrap',...style}}>{num!=null&&<span style={{fontFamily:'var(--font-display)',fontWeight:700,color:OR}}>{ROMAN[num-1]||num}</span>}{num!=null&&<span aria-hidden="true" style={{width:20,height:1,background:OR}}/>}<span>{children}</span></div>;
const SectionTitle=({children,overline,action,id,level=2,num,top})=><div id={id} style={{marginBottom:'var(--space-6)',marginTop:top?'var(--space-20)':0,display:'flex',alignItems:'flex-end',justifyContent:'space-between',gap:16,flexWrap:'wrap',scrollMarginTop:100}}><div>{overline&&<Overline num={num} style={{marginBottom:6}}>{overline}</Overline>}{level===1?<h1 style={{font:'var(--type-h2)'}}>{children}</h1>:<h2 style={{font:'var(--type-h3)'}}>{children}</h2>}<div aria-hidden="true" style={{height:'var(--rule-title)',width:'var(--rule-title-w)',background:'var(--brand-band)',marginTop:10}}/></div>{action}</div>;
const Star=({size=12,color=OR})=><svg viewBox="0 0 100 100" width={size} height={size} aria-hidden="true"><polygon fill={color} points="50,5 61.8,38.2 96.6,38.2 68.4,58.8 79.4,92 50,71.4 20.6,92 31.6,58.8 3.4,38.2 38.2,38.2"/></svg>;
const fcfa=v=>v===0?'Gratuit':v.toLocaleString('fr-FR').replace(/[\u202f\u00a0]/g,' ')+' FCFA';
const Money=({v,style})=><span style={{fontFamily:'var(--font-mono)',fontVariantNumeric:'tabular-nums',...style}}>{fcfa(v)}</span>;
const Row=({title,meta,right,onClick,icon,style})=><button type="button" onClick={onClick} style={{all:'unset',boxSizing:'border-box',cursor:onClick?'pointer':'default',display:'grid',gridTemplateColumns:(icon?'20px ':'')+'1fr auto'+(onClick?' 16px':''),gap:14,alignItems:'center',width:'100%',minHeight:44,padding:'10px 12px',borderBottom:'var(--hairline)',textAlign:'left',...style}}>{icon&&<Icon name={icon} size={18} color="var(--cm-vert-800)"/>}<span style={{minWidth:0}}><span style={{font:'var(--type-label)',fontWeight:600,color:'var(--text-heading)',display:'block'}}>{title}</span>{meta&&<span style={{font:'var(--type-caption)',fontWeight:500,color:'var(--text-muted)'}}>{meta}</span>}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'right'}}>{right}</span>{onClick&&<Icon name="chevron-right" size={16} color="var(--text-subtle)"/>}</button>;
/* Quittance : bloc certifié, numéro unique, empreinte ancrée, QR (à générer côté serveur) */
const Quittance=({t,compact})=><article aria-label={'Quittance '+t.id} style={{background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-ebene)',display:'grid',gridTemplateColumns:compact?'1fr':'minmax(0,1fr) auto',gap:'var(--space-5)',padding:'var(--space-5)'}}>
  <div style={{display:'grid',gap:10,minWidth:0}}><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><Star size={14}/><span style={{font:'var(--type-overline)',letterSpacing:'var(--tracking-caps)',textTransform:'uppercase'}}>Quittance du Trésor public</span><Badge status={t.statut==='Réglé'?'success':t.statut==='Gratuit'?'neutral':'warning'} size="sm">{t.statut}</Badge></div><div style={{font:'var(--type-h5)'}}>{t.t}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,font:'var(--type-caption)',color:'var(--text-muted)'}}>{[['Numéro',t.id,true],['Date',t.date],['Bénéficiaire',t.b],['Moyen',t.moyen],['Empreinte',t.hash,true]].map(([k,v,m])=><div key={k}><div style={{textTransform:'uppercase',letterSpacing:'var(--tracking-wide)'}}>{k}</div><div style={{color:'var(--text-heading)',fontWeight:600,fontFamily:m?'var(--font-mono)':'inherit',marginTop:2}}>{v}</div></div>)}</div></div>
  <div style={{display:'grid',gap:10,alignContent:'start',justifyItems:compact?'start':'end'}}><Money v={t.m} style={{font:'var(--type-h3)',fontFamily:'var(--font-mono)'}}/><div aria-label="Code QR de vérification" role="img" style={{width:72,height:72,background:'repeating-conic-gradient(var(--cm-ebene) 0 25%,transparent 0 50%) 0 0/16px 16px',border:'4px solid #fff',outline:'1px solid var(--border-default)'}}/><div style={{display:'flex',gap:4}}><IconButton icon="download" label="Télécharger la quittance PDF" variant="tertiary" size="sm"/><IconButton icon="share-2" label="Partager un lien de vérification" variant="tertiary" size="sm"/><IconButton icon="flag" label="Signaler un problème sur ce paiement" variant="tertiary" size="sm"/></div></div>
</article>;
function Shell({page,go,falc,setFalc,user,children}){
  const [lang,setLang]=useLang();
  const [a11y,setA11y]=React.useState(false);
  React.useEffect(()=>{const p=readA11y();applyA11y(p);setFalc(!!p.falc);},[]);
  const active={paiement:'payer',quittance:'transactions'}[page]||page;
  const fp=footerProps({site:tr('Trésor public — Paiements de l’État','Public Treasury — State payments'),lang,desc:tr("Tout paiement à l’État passe ici : le prix est connu avant, la quittance est certifiée après, et chaque franc est tracé jusqu’à son bénéficiaire.","Every payment to the State goes through here: the price is known beforehand, the receipt is certified afterwards, and every franc is traced to its beneficiary.")});
  return <div style={{minHeight:'100vh',display:'flex',flexDirection:'column',background:'var(--surface-page)'}}>
    <a href="#main" style={{position:'absolute',left:-9999,top:8,zIndex:2000,background:'var(--a11y-skip-bg)',padding:'8px 12px',font:'var(--type-label)',color:'var(--a11y-skip-text)'}} onFocus={e=>{e.target.style.left='8px';}} onBlur={e=>{e.target.style.left='-9999px';}}>Aller au contenu</a>
    <GovBar ministry="tresor" hubHref="../hub/index.html" sites={SITES} onSiteChange={id=>{const s=SITES.find(x=>x.id===id);if(s&&s.href)location.href=s.href;}} suggest={window.rechercher} onSearch={q=>location.href='../hub/index.html#recherche/'+encodeURIComponent(q)} onAccessibility={()=>setA11y(true)} lang={lang} onLangChange={setLang} user={user} onLogin={()=>location.href=LINKS.hub}/>
    <Header compact showLogin={false} serviceName={tr('Trésor public — Paiements de l’État','Public Treasury — State payments')} tagline={tr('Ministère des Finances · Direction générale du Trésor','Ministry of Finance · Directorate-General of the Treasury')} nav={NAVF()} active={typeof activeNav!=='undefined'?activeNav:active} onNavigate={v=>go(v)}/>
    {falc&&<div role="status" style={{background:'var(--cm-jaune-100)',borderBottom:'1px solid var(--cm-jaune-300)',font:'var(--type-body-sm)',padding:'8px var(--gutter)',textAlign:'center'}}>Version <b>facile à lire</b> activée.</div>}
    <main id="main" style={{flex:1}}>{children}</main>
    <Footer {...fp}/>
    <AccessPanel open={a11y} onClose={()=>setA11y(false)} onChange={p=>setFalc(!!p.falc)}/>
  </div>;
}
Object.assign(window,{Shell,Container,Overline,SectionTitle,Star,Money,fcfa,Row,Quittance,SITES,LINKS,NAVF,OR});
