/* Site générique des ministères : un seul gabarit, 40 institutions, FR/EN. Route : #<id>/<page> (accueil · demarches · ministere). */
const {Button,Badge,Stat,Tag,Icon,Table,Breadcrumb,Accordion,Timeline,Alert,Card}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
/* Missions FR/EN par ministère (une ligne intérieure, une ligne extérieure) + 3 démarches phares [titre FR, titre EN, service, coût, délai]. */
const FICHES={
 spm:{m:['Coordonne l’action gouvernementale et arbitre entre ministères.','Coordinates government action and arbitrates between ministries.'],x:['Suivi des grands programmes financés par les partenaires.','Monitors major partner-funded programmes.'],d:[['Consulter les communiqués du Conseil de cabinet','Cabinet Council communiqués','SPM','Gratuit','Publication'],['Saisir le Premier ministre (recours)','Petition the Prime Minister','Cabinet du PM','Gratuit','60 jours'],['Consulter les décrets du Premier ministre','Prime Minister’s decrees','SPM','Gratuit','Publication']]},
 an:{m:['Vote la loi et le budget, contrôle le gouvernement.','Passes laws and the budget, oversees government.'],x:['Diplomatie parlementaire.','Parliamentary diplomacy.'],d:[['Suivre une proposition de loi','Track a bill','Assemblée nationale','Gratuit','Session'],['Assister à une séance publique','Attend a public sitting','Questure','Gratuit','Inscription'],['Contacter son député ou sénateur','Contact your MP or senator','Assemblée / Sénat','Gratuit','—']]},
 minrex:{m:['Camerounais de l’étranger, passeports diplomatiques, protocole.','Cameroonians abroad, diplomatic passports, protocol.'],x:['Ambassades, consulats, ONU, UA, CEMAC, Commonwealth, Francophonie ; e-Visa.','Embassies, consulates, UN, AU, CEMAC, Commonwealth, Francophonie; e-Visa.'],d:[['Demander un e-Visa','Apply for an e-Visa','evisacam.cm','50 000 – 100 000 FCFA','72 h'],['S’immatriculer au consulat','Register with the consulate','Consulat','Gratuit','7 jours'],['Légaliser un document pour l’étranger','Legalise a document','Affaires consulaires','Timbre','48 h']]},
 minat:{m:['Régions, départements, chefferies, élections, protection civile, associations.','Regions, divisions, chiefdoms, elections, civil protection, associations.'],x:['Coopération transfrontalière.','Cross-border cooperation.'],d:[['Déclarer une association','Register an association','Préfecture','Gratuit','2 mois'],['Alerter la protection civile','Alert civil protection','117 / 118','Gratuit','Immédiat'],['Demander une autorisation de manifestation','Request an event permit','Sous-préfecture','Gratuit','7 jours']]},
 mindef:{m:['Forces armées, gendarmerie, service civique.','Armed forces, gendarmerie, civic service.'],x:['Opérations de paix, coopération militaire.','Peace operations, military cooperation.'],d:[['Consulter les recrutements','Recruitment notices','MINDEF','Gratuit','Campagne'],['Déposer une plainte en gendarmerie','File a complaint (gendarmerie)','Brigade','Gratuit','Immédiat'],['Demander un certificat de position militaire','Military status certificate','Bureau du service national','Gratuit','15 jours']]},
 dgsn:{m:['Police, CNI, passeports, sécurité publique.','Police, national ID, passports, public safety.'],x:['Police des frontières, Interpol.','Border police, Interpol.'],d:[['Renouveler sa CNI','Renew national ID card','Pré-enrôlement en ligne','2 800 FCFA','48 h – 15 j'],['Obtenir un passeport biométrique','Biometric passport','passeport.dgsn.cm','110 000 FCFA','48 h'],['Déposer une plainte','File a complaint','Commissariat','Gratuit','Immédiat']]},
 minjustice:{m:['Tribunaux, casier judiciaire, aide juridictionnelle, droits humains.','Courts, criminal record, legal aid, human rights.'],x:['Coopération judiciaire, extradition.','Judicial cooperation, extradition.'],d:[['Extrait de casier judiciaire','Criminal record extract','Tribunal','1 500 FCFA','72 h'],['Aide juridictionnelle','Legal aid','Commission','Gratuit','30 jours'],['Certificat de nationalité','Nationality certificate','Tribunal','Timbre','15 jours']]},
 mindevel:{m:['Communes, état civil (BUNEC), régions, FEICOM.','Councils, civil status (BUNEC), regions, FEICOM.'],x:['Coopération décentralisée.','Decentralised cooperation.'],d:[['Acte de naissance (copie)','Birth certificate copy','BUNEC','Gratuit','48 h'],['Déclarer une naissance','Declare a birth','Centre d’état civil','Gratuit (90 j)','Immédiat'],['Mariage civil','Civil marriage','Mairie','Timbre communal','30 jours']]},
 minepat:{m:['SND30, investissements publics, statistiques.','NDS30, public investment, statistics.'],x:['Coopération au développement, bailleurs.','Development cooperation, donors.'],d:[['Consulter le budget d’investissement public','Public investment budget','MINEPAT','Gratuit','Publication'],['Données de l’INS','National statistics','INS','Gratuit','Immédiat'],['Soumettre un projet au PIP','Submit a project to the PIP','Délégation','Gratuit','Campagne']]},
 minmap:{m:['Appels d’offres, COLEPS, contrôle des marchés.','Tenders, COLEPS, contract oversight.'],x:['Marchés financés par les partenaires.','Partner-funded contracts.'],d:[['Consulter les appels d’offres','Browse tenders','COLEPS','Gratuit','Selon avis'],['Soumissionner en ligne','Submit a bid online','COLEPS','Gratuit','Selon avis'],['Contester une attribution','Challenge an award','ARMP','Gratuit','15 jours']]},
 mincommerce:{m:['Prix, concurrence, consommateur, métrologie.','Prices, competition, consumers, metrology.'],x:['OMC, ZLECAf, import-export.','WTO, AfCFTA, import-export.'],d:[['Licence d’import-export','Import-export licence','Guichet','15 000 FCFA','7 jours'],['Signaler un prix abusif','Report abusive pricing','Brigade des prix','Gratuit','Immédiat'],['Certificat d’origine ZLECAf','AfCFTA certificate of origin','MINCOMMERCE','Selon barème','48 h']]},
 minpmeesa:{m:['Création d’entreprise (CFCE), artisanat, coopératives.','Business creation (CFCE), crafts, cooperatives.'],x:['Promotion des PME à l’export.','SME export promotion.'],d:[['Créer une entreprise en 72 h','Create a business in 72 h','CFCE','41 500 FCFA (SARL)','72 h'],['Carte d’artisan','Craftsperson card','Délégation','Gratuit','15 jours'],['Financement PME (BC-PME)','SME financing','BC-PME','—','Dossier']]},
 minmidt:{m:['Permis miniers, normes (ANOR), zones industrielles.','Mining permits, standards (ANOR), industrial zones.'],x:['Investisseurs, transferts de technologie.','Investors, technology transfer.'],d:[['Certificat de conformité ANOR','ANOR conformity certificate','ANOR','Selon produit','30 jours'],['Permis d’exploitation artisanale','Artisanal mining permit','MINMIDT','Selon barème','60 jours'],['Consulter le cadastre minier','Mining cadastre','MINMIDT','Gratuit','Immédiat']]},
 minsante:{m:['Hôpitaux, Couverture santé universelle, vaccination, médicaments.','Hospitals, Universal Health Coverage, vaccination, medicines.'],x:['OMS, Gavi, coopération sanitaire.','WHO, Gavi, health cooperation.'],d:[['S’inscrire à la CSU','Enrol in UHC','csu.cm','Gratuit (cibles)','Immédiat'],['Carnet de vaccination numérique','Digital vaccination record','PEV','Gratuit','Immédiat'],['Trouver un hôpital','Find a hospital','Carte sanitaire','Gratuit','Immédiat']]},
 mintss:{m:['Code du travail, CNPS, inspection, dialogue social.','Labour code, CNPS, inspection, social dialogue.'],x:['OIT, conventions internationales.','ILO, international conventions.'],d:[['S’immatriculer à la CNPS','Register with CNPS','e-CNPS','Gratuit','7 jours'],['Simuler sa pension','Simulate your pension','e-CNPS','Gratuit','Immédiat'],['Visa d’un contrat de travail étranger','Foreign work contract visa','Délégation','Gratuit','15 jours']]},
 minas:{m:['Personnes handicapées, enfance, personnes âgées, aide sociale.','Disability, childhood, elderly, social assistance.'],x:['Conventions sur le handicap et l’enfance.','Disability and child-rights conventions.'],d:[['Carte nationale d’invalidité','National disability card','Délégation','Gratuit','30 jours'],['Aide sociale d’urgence','Emergency social aid','Centre social','Gratuit','Commission'],['Signaler un enfant en danger','Report a child at risk','116','Gratuit','Immédiat']]},
 minproff:{m:['Égalité, famille, mariages collectifs, lutte contre les violences.','Equality, family, collective weddings, ending violence.'],x:['ONU Femmes.','UN Women.'],d:[['Signaler des violences','Report violence','Centre de promotion de la femme','Gratuit','Immédiat'],['S’inscrire à un mariage collectif','Register for a collective wedding','Délégation','Gratuit','Campagne'],['Formation des femmes entrepreneures','Women entrepreneurs training','CPFF','Gratuit','Session']]},
 minfopra:{m:['Concours, carrières des agents publics, SIGIPES.','Competitive exams, civil-service careers, SIGIPES.'],x:['Réformes appuyées par les partenaires.','Partner-supported reforms.'],d:[['Consulter les concours','Browse competitive exams','MINFOPRA','Gratuit','Publication'],['Suivre sa carrière (SIGIPES)','Track your career','SIGIPES','Gratuit','Immédiat'],['Demander un acte de carrière','Career document','MINFOPRA','Gratuit','30 jours']]},
 minedub:{m:['Maternelle et primaire, CEP, manuels, cantines.','Nursery and primary, CEP, textbooks, canteens.'],x:['UNESCO, UNICEF.','UNESCO, UNICEF.'],d:[['Inscrire un enfant au primaire public','Enrol a child in public primary school','École de secteur','Gratuit','Rentrée'],['Résultats du CEP','CEP results','MINEDUB','Gratuit','Publication'],['Liste officielle des manuels','Official textbook list','MINEDUB','Gratuit','Publication']]},
 minesec:{m:['Collèges et lycées, BEPC, probatoire, baccalauréat, GCE.','Secondary schools, BEPC, probatoire, baccalauréat, GCE.'],x:['Équivalences, examens internationaux.','Equivalences, international exams.'],d:[['Résultats BEPC, probatoire, bac','Exam results','OBC','Gratuit','Publication'],['Résultats du GCE','GCE results','GCE Board','Gratuit','Publication'],['Inscription au lycée public','Public secondary enrolment','Lycée','7 500 FCFA','Rentrée']]},
 minesup:{m:['Universités d’État, bourses, LMD, recherche universitaire.','State universities, scholarships, LMD, research.'],x:['Mobilité étudiante, CAMES.','Student mobility, CAMES.'],d:[['Demander une bourse','Apply for a scholarship','MINESUP','Gratuit','Campagne'],['Reconnaissance d’un diplôme étranger','Foreign degree recognition','Commission','Timbre','60 jours'],['Préinscription universitaire','University pre-registration','Université','Gratuit','Campagne']]},
 minefop:{m:['FNE, centres de formation, certification des compétences.','FNE, training centres, skills certification.'],x:['Partenariats de formation.','Training partnerships.'],d:[['S’inscrire au FNE','Register with the FNE','fnecm.org','Gratuit','Immédiat'],['Trouver une formation professionnelle','Find vocational training','MINEFOP','Gratuit','Immédiat'],['Certifier ses compétences','Certify your skills','Centre agréé','Selon module','Session']]},
 minresi:{m:['Instituts de recherche (IRAD, IMPM, IRGM), innovation.','Research institutes (IRAD, IMPM, IRGM), innovation.'],x:['Coopération scientifique.','Scientific cooperation.'],d:[['Déposer un brevet ou une innovation','File a patent or innovation','MINRESI / OAPI','Selon barème','90 jours'],['Bulletin volcanologique et sismique','Volcanic and seismic bulletin','IRGM','Gratuit','Publication'],['Semences améliorées IRAD','Improved seeds','IRAD','Selon variété','Campagne']]},
 mint:{m:['Permis de conduire, cartes grises, sécurité routière, aviation, ports.','Driving licences, registration, road safety, aviation, ports.'],x:['OACI, OMI, corridors CEMAC.','ICAO, IMO, CEMAC corridors.'],d:[['Permis de conduire','Driving licence','Délégation','Selon catégorie','Session'],['Carte grise','Vehicle registration','Délégation','Selon puissance','72 h'],['Visite technique','Roadworthiness test','Centre agréé','Selon catégorie','Immédiat']]},
 mintp:{m:['Routes, ponts, entretien routier, autoroutes.','Roads, bridges, maintenance, motorways.'],x:['Financements d’infrastructures.','Infrastructure financing.'],d:[['État des routes','Road conditions','Bulletin routier','Gratuit','Immédiat'],['Signaler un danger sur la route','Report a road hazard','MINTP','Gratuit','Immédiat'],['Péage — barème','Toll fees','Trésor public','500 – 2 000 FCFA','Immédiat']]},
 minhdu:{m:['Permis de construire, logement social, urbanisme.','Building permits, social housing, urban planning.'],x:['ONU-Habitat.','UN-Habitat.'],d:[['Permis de construire','Building permit','Commune','1 % des travaux','30 jours'],['Logement social (SIC)','Social housing','sic.cm','Dossier','Commission'],['Certificat d’urbanisme','Planning certificate','Délégation','Timbre','15 jours']]},
 mindcaf:{m:['Titres fonciers, cadastre, domaine national.','Land titles, cadastre, national estate.'],x:['—','—'],d:[['Titre foncier','Land title','Conservation foncière','Selon superficie','60 jours + enquête'],['Certificat de propriété','Certificate of ownership','Conservation','Timbre','7 jours'],['Non-litige foncier coutumier','Customary land clearance','Chefferie → commission','Gratuit','15 jours']]},
 minee:{m:['Électricité, eau potable, hydrocarbures.','Electricity, drinking water, hydrocarbons.'],x:['Interconnexions régionales.','Regional interconnections.'],d:[['Branchement eau ou électricité','Water or power connection','CAMWATER / ENEO','Selon devis','15 jours'],['Signaler une coupure','Report an outage','ENEO / CAMWATER','Gratuit','Immédiat'],['Tarifs de l’électricité','Electricity tariffs','ARSEL','Gratuit','Publication']]},
 minpostel:{m:['Télécoms, Identité Cameroun, ANTIC, CAMPOST, cybersécurité.','Telecoms, Identité Cameroun, ANTIC, CAMPOST, cybersecurity.'],x:['UIT, câbles sous-marins.','ITU, submarine cables.'],d:[['Activer Identité Cameroun','Activate Identité Cameroun','identite.gouv.cm','Gratuit','Immédiat'],['Certificat de signature électronique','Electronic signature certificate','ANTIC','Selon niveau','7 jours'],['Suivre un colis','Track a parcel','CAMPOST','Gratuit','Immédiat']]},
 minader:{m:['Filières cacao-café, coton, vivrier ; coopératives ; intrants.','Cocoa-coffee, cotton, food crops; cooperatives; inputs.'],x:['FAO, FIDA, exportations.','FAO, IFAD, exports.'],d:[['Immatriculer une coopérative','Register a cooperative','Registre OHADA','Gratuit','30 jours'],['Intrants subventionnés','Subsidised inputs','Délégation','Subventionné','Campagne'],['Agrément phytosanitaire','Phytosanitary approval','MINADER','Selon barème','30 jours']]},
 minepia:{m:['Élevage, pêche, santé animale, abattoirs.','Livestock, fisheries, animal health, abattoirs.'],x:['Normes sanitaires, exportations.','Sanitary standards, exports.'],d:[['Certificat sanitaire vétérinaire','Veterinary health certificate','Délégation','Selon acte','48 h'],['Licence de pêche','Fishing licence','MINEPIA','Selon catégorie','15 jours'],['Vaccination du bétail','Livestock vaccination','Centre zootechnique','Subventionné','Campagne']]},
 minfof:{m:['Permis forestiers, parcs nationaux, lutte contre le braconnage.','Forest permits, national parks, anti-poaching.'],x:['CITES, APV-FLEGT.','CITES, VPA-FLEGT.'],d:[['Permis d’exploitation forestière','Forest exploitation permit','MINFOF','Selon surface','90 jours'],['Visiter un parc national','Visit a national park','MINFOF','Selon parc','Immédiat'],['Signaler un braconnage','Report poaching','MINFOF','Gratuit','Immédiat']]},
 minepded:{m:['Études d’impact, déchets, climat, biodiversité.','Impact studies, waste, climate, biodiversity.'],x:['Accord de Paris, COP.','Paris Agreement, COP.'],d:[['Déposer une étude d’impact','File an impact assessment','MINEPDED','Frais d’examen','Comité'],['Signaler une pollution','Report pollution','MINEPDED','Gratuit','Immédiat'],['Certificat de conformité environnementale','Environmental compliance certificate','MINEPDED','Selon barème','60 jours']]},
 minjec:{m:['Fête de la Jeunesse, PAJER-U, service civique, civisme.','Youth Day, PAJER-U, civic service, citizenship.'],x:['Programmes jeunesse internationaux.','International youth programmes.'],d:[['S’inscrire au service civique','Join civic service','ASCNPD','Gratuit','Campagne'],['Financement de projet jeune (PAJER-U)','Youth project funding','MINJEC','Gratuit','Dossier'],['Carte jeune','Youth card','Délégation','Gratuit','15 jours']]},
 mincom:{m:['Presse, CRTV, Cameroon Tribune, communication gouvernementale.','Press, CRTV, Cameroon Tribune, government communication.'],x:['Image du pays, accréditations.','Country image, accreditations.'],d:[['Accréditation presse','Press accreditation','MINCOM','Gratuit','15 jours'],['Consulter le Journal officiel','Official Gazette','SOPECAM','Gratuit','Publication'],['Déclarer un organe de presse','Register a media outlet','MINCOM','Gratuit','30 jours']]}
};
/* Âme propre des institutions de poids ≥ 4 : accent, devise de service, chiffres clés, section signature. Le gabarit reste commun. */
const AME={
 spm:{accent:'var(--cm-indigo-700)',motto:['Coordonner, arbitrer, rendre compte.','Coordinate, arbitrate, account.'],chiffres:[['1','Conseil de cabinet / mois','Cabinet Council / month'],['40','institutions coordonnées','institutions coordinated'],['SND30','stratégie 2020-2030','2020-2030 strategy']],focus:['Suivi des réformes','Reform tracker','Tableau public d’avancement des réformes prioritaires (état civil, foncier, numérique), mis à jour chaque trimestre.','Public dashboard of priority reforms (civil status, land, digital), updated quarterly.'],variant:'tableau'},
 an:{accent:'var(--cm-rouge-600)',motto:['La loi se fait en public.','Law is made in public.'],chiffres:[['180','députés','MPs'],['100','sénateurs','senators'],['2','sessions ordinaires / an','ordinary sessions / year']],focus:['Suivre un texte','Track a bill','Chaque projet ou proposition de loi a une page : dépôt, commission, séance, promulgation, texte final FR/EN.','Every bill has a page: filing, committee, plenary, promulgation, final FR/EN text.'],variant:'tableau'},
 minrex:{accent:'var(--cm-indigo-600)',motto:['Le Cameroun dans le monde, le monde au Cameroun.','Cameroon in the world, the world in Cameroon.'],chiffres:[['50+','ambassades et consulats','embassies & consulates'],['72 h','délai e-Visa','e-Visa lead time'],['4 M','Camerounais de l’étranger (est.)','Cameroonians abroad (est.)']],focus:['Trouver une représentation','Find a mission','Carte des ambassades et consulats avec horaires, services et prise de rendez-vous ; alertes voyageurs.','Map of embassies and consulates with hours, services and appointments; travel advisories.'],variant:'carte'},
 minat:{accent:'var(--cm-kola-600)',motto:['L’État au plus près du territoire.','The State close to the ground.'],chiffres:[['10','régions','regions'],['58','départements','divisions'],['360','arrondissements','sub-divisions']],focus:['Alertes et protection civile','Alerts & civil protection','Bulletins d’alerte (inondations, éruptions, épidémies) par région, consignes et numéros d’urgence 117 / 118.','Alert bulletins (floods, eruptions, epidemics) by region, instructions and emergency numbers 117 / 118.'],variant:'carte'},
 mindef:{accent:'var(--cm-vert-900)',motto:['Servir, protéger, bâtir.','Serve, protect, build.'],chiffres:[['1960','création des Forces armées','Armed Forces founded'],['5','régions militaires','military regions'],['Génie','ponts et routes au service civil','bridges & roads for civil use']],focus:['Recrutement et service','Recruitment & service','Calendrier des recrutements, conditions, centres, résultats ; service civique de participation au développement.','Recruitment calendar, requirements, centres, results; civic development service.'],variant:'agenda'},
 dgsn:{accent:'var(--cm-indigo-800)',motto:['Une identité sûre pour chacun.','A secure identity for everyone.'],chiffres:[['48 h','CNI après enrôlement','ID card after enrolment'],['110 000','FCFA — passeport','FCFA — passport'],['117','police secours','police emergency']],focus:['Suivre ma CNI ou mon passeport','Track my ID or passport','Statut en temps réel de la production et du centre de retrait ; SMS à chaque étape.','Real-time production status and pick-up centre; SMS at every step.'],variant:'suivi'},
 minjustice:{accent:'var(--cm-ebene)',motto:['Le droit, accessible et lisible.','Law, accessible and legible.'],chiffres:[['10','cours d’appel','courts of appeal'],['72 h','casier judiciaire','criminal record'],['Gratuit','aide juridictionnelle','legal aid']],focus:['Comprendre une procédure','Understand a procedure','Fiches en langage clair (FALC) : divorce, succession, litige foncier, garde à vue ; annuaire des tribunaux.','Plain-language guides: divorce, inheritance, land dispute, custody; court directory.'],variant:'tableau'},
 mindevel:{accent:'var(--cm-laterite-600)',motto:['Chaque commune, un guichet de l’État.','Every council, a State desk.'],chiffres:[['374','communes','councils'],['BUNEC','état civil national','national civil status'],['FEICOM','financement des communes','council financing']],focus:['Ma commune','My council','Page de chaque commune : état civil, budget, projets, élus, horaires ; notation citoyenne de l’accueil.','A page per council: civil status, budget, projects, elected officials, hours; citizen rating.'],variant:'carte'},
 minepat:{accent:'var(--cm-kola-700)',motto:['Planifier aujourd’hui le Cameroun de 2030.','Planning today the Cameroon of 2030.'],chiffres:[['SND30','stratégie nationale','national strategy'],['INS','statistiques publiques','public statistics'],['PIP','investissement public','public investment']],focus:['Données du pays','Country data','Indicateurs de l’INS en accès ouvert : population, prix, emploi, comptes nationaux, par région.','Open INS indicators: population, prices, jobs, national accounts, by region.'],variant:'tableau'},
 minsante:{accent:'var(--cm-vert-700)',motto:['La santé pour tous, partout.','Health for all, everywhere.'],chiffres:[['CSU','couverture santé universelle','universal health coverage'],['190','districts de santé','health districts'],['1510','urgences sanitaires','health emergency line']],focus:['Trouver un soin près de chez soi','Find care nearby','Carte des formations sanitaires par district : services, garde, tarifs CSU, disponibilité des vaccins.','Map of health facilities by district: services, on-call, UHC tariffs, vaccine availability.'],variant:'carte'},
 mintss:{accent:'var(--cm-indigo-600)',motto:['Un travail digne, une retraite sûre.','Decent work, a secure pension.'],chiffres:[['CNPS','sécurité sociale','social security'],['e-CNPS','déclarations en ligne','online filings'],['1967','création de la CNPS','CNPS founded']],focus:['Ma carrière et ma pension','My career and pension','Relevé de carrière consolidé, simulateur de pension, alertes de cotisations manquantes.','Consolidated career record, pension simulator, missing-contribution alerts.'],variant:'suivi'},
 minedub:{accent:'var(--cm-jaune-700)',motto:['Chaque enfant à l’école, chaque école équipée.','Every child in school, every school equipped.'],chiffres:[['CEP','fin du primaire','end of primary'],['Gratuit','primaire public','public primary'],['2','langues d’enseignement','languages of instruction']],focus:['Trouver une école','Find a school','Carte des écoles publiques par secteur : effectifs, cantine, accessibilité, résultats au CEP.','Map of public schools by sector: enrolment, canteen, accessibility, CEP results.'],variant:'carte'},
 minesec:{accent:'var(--cm-rouge-700)',motto:['Réussir, du collège au baccalauréat.','Succeed, from college to baccalauréat.'],chiffres:[['OBC','examens officiels','official exams'],['GCE','sous-système anglophone','anglophone subsystem'],['7 500','FCFA — inscription lycée','FCFA — secondary fee']],focus:['Résultats et relevés','Results & transcripts','Résultats par numéro de candidat, relevé certifié dans le coffre, réclamations en ligne.','Results by candidate number, certified transcript in the vault, online appeals.'],variant:'suivi'},
 minesup:{accent:'var(--cm-indigo-700)',motto:['Savoir, recherche, insertion.','Knowledge, research, employment.'],chiffres:[['11','universités d’État','state universities'],['LMD','licence-master-doctorat','bachelor-master-PhD'],['CAMES','reconnaissance régionale','regional accreditation']],focus:['Bourses et préinscriptions','Scholarships & pre-registration','Un dossier unique pour toutes les universités d’État ; suivi des bourses ; reconnaissance des diplômes étrangers.','One file for all state universities; scholarship tracking; foreign degree recognition.'],variant:'agenda'},
 mint:{accent:'var(--cm-kola-600)',motto:['Se déplacer en sécurité.','Travel safely.'],chiffres:[['72 h','carte grise','vehicle registration'],['2021','code de la route','highway code'],['ADC','aviation civile','civil aviation']],focus:['Mon véhicule','My vehicle','Carte grise, visite technique, assurance et amendes rattachées à l’immatriculation ; rappels avant échéance.','Registration, roadworthiness, insurance and fines linked to the plate; reminders before deadlines.'],variant:'suivi'},
 mintp:{accent:'var(--cm-laterite-700)',motto:['Des routes qui relient.','Roads that connect.'],chiffres:[['500','FCFA — péage léger','FCFA — light-vehicle toll'],['Fonds routier','entretien','maintenance'],['10','corridors prioritaires','priority corridors']],focus:['État des routes en direct','Live road conditions','Carte des chantiers, coupures, pesages et péages ; signalement d’un danger avec photo.','Map of works, closures, weighbridges and tolls; report a hazard with photo.'],variant:'carte'},
 minee:{accent:'var(--cm-indigo-500)',motto:['L’eau et la lumière pour chaque foyer.','Water and light for every home.'],chiffres:[['Nachtigal','420 MW (2024)','420 MW (2024)'],['ENEO','électricité','electricity'],['CAMWATER','eau potable','drinking water']],focus:['Coupures et travaux','Outages & works','Carte des coupures programmées et incidents par quartier ; signalement ; suivi de branchement.','Map of scheduled outages and incidents by neighbourhood; reporting; connection tracking.'],variant:'carte'},
 minpostel:{accent:'var(--cm-vert-800)',motto:['Le numérique, bien commun.','Digital, a common good.'],chiffres:[['Identité','Cameroun numérique','Cameroun numérique'],['ANTIC','cybersécurité','cybersecurity'],['CAMPOST','poste et colis','post & parcels']],focus:['Cameroun numérique','Cameroun numérique','Pilote du langage commun, de l’identité numérique et du registre d’intégrité ; publie le guide et le journal des changements.','Steward of the common language, digital identity and integrity ledger; publishes the guide and changelog.'],variant:'tableau'},
 minader:{accent:'var(--cm-vert-700)',motto:['Nourrir le pays, faire vivre les campagnes.','Feed the country, sustain the countryside.'],chiffres:[['Cacao','1er produit d’exportation agricole','top agricultural export'],['Coton','Grand Nord','Far North'],['OHADA','coopératives','cooperatives']],focus:['Calendrier agricole et prix','Farming calendar & prices','Prix des marchés par région, météo agricole, campagnes d’intrants, alertes phytosanitaires.','Market prices by region, agro-weather, input campaigns, phytosanitary alerts.'],variant:'tableau'}
};
const T=(fr,en)=>tr(fr,en);
function MinistereApp(){
  const [lang,setLangState]=useLang();
  const [route,setRoute]=React.useState(()=>lireHash()||{page:'minsante',arg:'accueil'});
  const id=route.page;const page=route.arg||'accueil';const m=MINISTERES.find(x=>x.id===id)||MINISTERES.find(x=>x.id==='minsante');const f=FICHES[m.id]||FICHES.minsante;const inst=(window.INSTITUTIONS||[]).find(i=>i.id===m.id)||{};
  const go=(p,a)=>{setRoute({page:p,arg:a||'accueil'});ecrireHash(p,a||'accueil');window.scrollTo(0,0);};
  React.useEffect(()=>{const f=()=>{const h=lireHash();if(h)setRoute(h);};window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f);},[]);
  const nom=lang==='EN'?m.en:m.fr;const full=(lang==='EN'?'Ministry of ':'Ministère de ')+(m.cat==='souv'&&['prc','spm','an','dgsn'].includes(m.id)?'':'')+nom;
  const titre=['prc','spm','an','dgsn'].includes(m.id)?nom:(lang==='EN'?'Ministry of '+nom:('Ministère '+(/^[AEIOUÉ]/.test(nom)?'de l’':'de ')+nom).replace('de Éducation','de l’Éducation'));
  const SITE={id:m.id,nom:titre,tagline:(inst.sigle||m.id.toUpperCase())+' · '+T('République du Cameroun','Republic of Cameroon'),nav:[{value:'accueil',label:T('Accueil','Home')},{value:'demarches',label:T('Démarches & services','Services')},{value:'ministere',label:T('Le ministère','The ministry')}],footer:T('Site officiel. Démarches avec coût et délai, textes et organisation du ministère. Membre du réseau Cameroun numérique.','Official site. Services with fee and lead time, texts and organisation of the ministry. Member of the Cameroun numérique network.')};
  window.SITE=SITE;
  const dem=f.d.map(([fr,en,svc,cout,delai])=>({t:lang==='EN'?en:fr,svc,cout,delai}));
  const img=IMG_CTX[m.img];const credit=CREDIT_CTX[m.img];const ame=AME[m.id];const AC=ame?ame.accent:OR;
  return <Shell page={page} go={p=>go(m.id,p)} lang={lang} setLang={setLangState}><Garde k={id+page} onHome={()=>go(m.id,'accueil')}>
    {page==='accueil'&&<>
      <section style={{position:'relative',background:'var(--cm-ebene)',color:'#fff',overflow:'hidden'}}><div aria-hidden="true" style={{position:'absolute',inset:0,background:'url('+img+') center/cover',opacity:.32,zIndex:-2}}/><div aria-hidden="true" style={{position:'absolute',inset:0,background:'linear-gradient(90deg,rgba(21,17,14,.96) 0%,rgba(21,17,14,.8) 55%,rgba(21,17,14,.45))'}}/>
        <Container style={{position:'relative',padding:'var(--space-16) var(--gutter) var(--space-12)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'end'}}>
          <div><Overline color="var(--cm-jaune-500)">{CAT_MIN[m.cat][lang==='EN'?1:0]} · {inst.sigle||m.id.toUpperCase()}</Overline><div aria-hidden="true" style={{width:48,height:3,background:AC,margin:'14px 0 0'}}/><h1 style={{font:'var(--type-display)',color:'#fff',fontSize:'clamp(2rem,4.4vw,3.25rem)',marginTop:14,letterSpacing:'var(--tracking-tight)'}}>{titre}</h1>{ame&&<p style={{fontFamily:'var(--font-display)',fontWeight:500,fontStyle:'italic',fontSize:'var(--text-xl)',color:'var(--cm-jaune-500)',marginTop:10}}>{lang==='EN'?ame.motto[1]:ame.motto[0]}</p>}<p style={{font:'var(--type-lead)',color:'var(--cm-gris-200)',maxWidth:'54ch',marginTop:14}}>{lang==='EN'?f.m[1]:f.m[0]}</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:24}}><Button variant="inverse" iconRight="arrow-right" onClick={()=>go(m.id,'demarches')}>{T('Démarches et services','Services')}</Button><Button variant="tertiary" style={{color:'#fff'}} iconRight="arrow-right" onClick={()=>go(m.id,'ministere')}>{T('Le ministère','The ministry')}</Button></div></div>
          <div style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.2)',borderTop:'2px solid '+OR,padding:'var(--space-6)',display:'grid',gap:10}}><Overline color="var(--cm-jaune-500)">{T('Démarches phares','Key services')}</Overline>{dem.map(d=><button key={d.t} type="button" onClick={()=>go(m.id,'demarches')} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:'1fr 16px',gap:10,alignItems:'center',padding:'10px 0',borderBottom:'1px solid rgba(255,255,255,.14)',textAlign:'left'}}><span><span style={{font:'var(--type-label)',fontWeight:600,color:'#fff',display:'block'}}>{d.t}</span><span style={{font:'var(--type-caption)',color:'var(--cm-gris-300)'}}>{d.cout} · {d.delai}</span></span><Icon name="chevron-right" size={14} color="var(--cm-gris-400)"/></button>)}</div>
          <div style={{position:'absolute',right:24,bottom:8,font:'var(--type-caption)',color:'var(--cm-gris-400)'}}>© {credit}</div>
        </Container></section>
      <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',borderTop:'2px solid '+AC}}><Container style={{padding:'var(--space-8) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-6)'}}>{ame?ame.chiffres.map(([v,fr,en])=><Stat key={fr} size="sm" value={v} label={lang==='EN'?en:fr} accent="vert"/>):<Stat size="sm" value={dem.length} label={T('démarches en ligne','online services')} accent="vert"/>}<Stat size="sm" value="8100" label={T('assistance gratuite','free helpline')} detail="7 j/7 · FR/EN" accent="kola"/><Stat size="sm" value={inst.poids||3} label={T('poids institutionnel','institutional weight')} detail="/ 5" accent="indigo"/><Stat size="sm" value="AA" label={T('accessibilité visée','target accessibility')} detail="WCAG 2.2" accent="neutre"/></Container></section>
      <Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'start'}}>
        <div><SectionTitle overline={T('Missions','Missions')} num={1}>{T('Vie intérieure, relations extérieures','At home and abroad')}</SectionTitle><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'var(--space-4)'}}><div style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-vert-800)'}}><Overline>{T('Vie intérieure','Domestic')}</Overline><p style={{marginTop:8}}>{lang==='EN'?f.m[1]:(inst.int||f.m[0])}</p></div><div style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)',borderTop:'4px solid var(--cm-indigo-600)'}}><Overline color="var(--cm-indigo-700)">{T('Relations extérieures','International')}</Overline><p style={{marginTop:8}}>{lang==='EN'?f.x[1]:(inst.ext||f.x[0])}</p></div></div>
          {ame&&<><SectionTitle top overline={T('Service signature','Signature service')} num={2}>{lang==='EN'?ame.focus[1]:ame.focus[0]}</SectionTitle><div style={{display:'grid',gridTemplateColumns:ame.variant==='carte'?'minmax(0,1fr) minmax(0,1fr)':'1fr',gap:'var(--space-4)'}}><div style={{padding:'var(--space-6)',background:'var(--cm-ebene)',color:'#fff',borderLeft:'4px solid '+AC,display:'grid',gap:12,alignContent:'start'}}><p style={{color:'var(--cm-gris-200)'}}>{lang==='EN'?ame.focus[3]:ame.focus[2]}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Button variant="inverse" size="sm" iconRight="arrow-right" onClick={()=>go(m.id,'demarches')}>{T('Ouvrir','Open')}</Button><Badge status="warning" size="sm">{T('en construction — proposé au vote','in progress — up for vote')}</Badge></div></div>{ame.variant==='carte'&&<div role="img" aria-label={T('Carte à raccorder','Map to connect')} style={{minHeight:200,background:'var(--motif-laterite)',border:'var(--hairline)',display:'grid',placeItems:'center',font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'center',padding:16}}><span><Icon name="map" size={22}/><br/>{T('Carte interactive (données MINAT / INS à raccorder)','Interactive map (MINAT / INS data to connect)')}</span></div>}{ame.variant==='tableau'&&<Table caption={lang==='EN'?ame.focus[1]:ame.focus[0]} columns={[{key:'0',label:T('Indicateur','Indicator'),strong:true},{key:'1',label:T('Valeur','Value'),mono:true,align:'right'},{key:'2',label:T('Source','Source')}]} rows={ame.chiffres.map(([v,fr,en])=>[lang==='EN'?en:fr,v,inst.sigle||m.id.toUpperCase()])}/>}{ame.variant==='suivi'&&<div style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)'}}><Timeline items={[{title:T('Demande déposée','Request filed'),when:'J',status:'done'},{title:T('Vérification','Verification'),when:'J+1',status:'done'},{title:T('Production','Production'),when:'J+2',status:'current'},{title:T('Retrait ou remise','Pick-up or delivery'),when:'J+3',status:'todo'}]}/></div>}{ame.variant==='agenda'&&<div style={{padding:'var(--space-5)',background:'var(--surface-card)',border:'var(--hairline)'}}><Timeline items={[{title:T('Ouverture des inscriptions','Registration opens'),when:'oct.',status:'done'},{title:T('Clôture des dossiers','Deadline'),when:'nov.',status:'current'},{title:T('Épreuves / commission','Tests / committee'),when:'déc.',status:'todo'},{title:T('Résultats','Results'),when:'janv.',status:'todo'}]}/></div>}</div></>}
          <SectionTitle top overline={T('Actualité','News')} num={ame?3:2}>{T('Communiqués récents','Recent releases')}</SectionTitle><div style={{display:'grid',gap:2}}>{[[T('Communiqué','Press release'),T('Point hebdomadaire du ministère','Weekly ministry briefing'),'19 sept. 2026'],[T('Avis','Notice'),T('Calendrier des services pendant la fête de la Réunification','Service calendar for Reunification Day'),'15 sept. 2026'],[T('Publication','Publication'),T('Rapport annuel d’activité 2025','2025 annual activity report'),'2 sept. 2026']].map(([k,t,d])=><Row key={t} icon="newspaper" title={t} meta={k} right={d} onClick={()=>{}} style={{background:'var(--surface-card)'}}/>)}</div></div>
        <aside style={{display:'grid',gap:'var(--space-4)'}}><Photo src={img} credit={credit} ratio="4/3"/><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">{T('Où se rendre','Where to go')}</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>{T('Délégations régionales dans les dix chefs-lieux ; guichets Cameroun numérique pour l’accompagnement.','Regional delegations in the ten regional capitals; Cameroun numérique desks for assistance.')}</p><Button size="sm" variant="secondary" iconLeft="map-pin" href="../hub/index.html#relais" style={{marginTop:10}}>{T('Relais locaux','Local desks')}</Button></div></aside>
      </Container>
    </>}
    {page==='demarches'&&<Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}><SectionTitle level={1} overline={T('Démarches & services','Services')} num={1}>{T('Coût et délai avant de commencer','Fee and lead time before you start')}</SectionTitle>
      <div style={{display:'grid',gap:2}}>{dem.map(d=><div key={d.t} style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',display:'grid',gridTemplateColumns:'1fr auto',gap:12,alignItems:'center',padding:'14px 16px'}}><div><div style={{font:'var(--type-label)',fontWeight:600,color:'var(--text-heading)'}}>{d.t}</div><div style={{display:'flex',gap:14,flexWrap:'wrap',marginTop:6,font:'var(--type-caption)',color:'var(--text-muted)'}}><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name="coins" size={12}/>{d.cout}</span><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name="clock" size={12}/>{d.delai}</span><span style={{display:'inline-flex',gap:5,alignItems:'center'}}><Icon name="landmark" size={12}/>{d.svc}</span></div></div><Button size="sm" iconRight="arrow-right" href="../hub/index.html#connexion">{T('Commencer','Start')}</Button></div>)}</div>
      <Alert status="info" size="sm" title={T('Paiement au Trésor public','Payment at the Public Treasury')} style={{marginTop:'var(--space-6)'}}>{T('Tout frais est réglé au Trésor avec quittance ; aucun paiement n’est dû au guichet du ministère.','Every fee is paid to the Treasury with a receipt; nothing is due at the ministry counter.')} <a href="../tresor/index.html#frais">{T('Barème','Fee schedule')}</a> · <a href="../tresor/index.html#signaler">{T('Signaler un abus','Report abuse')}</a></Alert></Container>}
    {page==='ministere'&&<Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}><SectionTitle level={1} overline={T('Le ministère','The ministry')} num={1}>{titre}</SectionTitle>
      <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}><div><Photo src={img} credit={credit} ratio="16/7"/><Accordion style={{marginTop:'var(--space-6)'}} defaultOpen={['o']} items={[{id:'o',title:T('Organisation','Organisation'),content:<p>{T('Cabinet du ministre, secrétariat général, directions centrales, délégations régionales et départementales. Organigramme officiel à publier par le ministère.','Minister’s office, secretariat-general, central directorates, regional and divisional delegations. Official chart to be published by the ministry.')}</p>},{id:'t',title:T('Textes de référence','Reference texts'),content:<p>{T('Décret d’organisation du gouvernement ; décret d’organisation du ministère ; textes sectoriels. Versions FR/EN au Journal officiel.','Government organisation decree; ministry organisation decree; sectoral texts. FR/EN versions in the Official Gazette.')}</p>},{id:'c',title:T('Contact','Contact'),content:<p>{T('Siège à Yaoundé ; délégations régionales ; 8100 pour l’orientation ; courrier depuis votre compte Identité Cameroun.','Headquarters in Yaoundé; regional delegations; 8100 for guidance; mail from your Identité Cameroun account.')}</p>}]}/></div>
      <aside style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">{T('Dans le réseau','In the network')}</Overline><div style={{display:'grid',gap:2,marginTop:8}}>{MINISTERES.filter(x=>x.cat===m.cat&&x.id!==m.id).slice(0,6).map(x=><Row key={x.id} title={lang==='EN'?x.en:x.fr} href={x.href} style={{padding:'8px 0'}}/>)}</div><Button size="sm" variant="tertiary" iconRight="arrow-right" href="../hub/index.html#annuaire" style={{marginTop:10}}>{T('Tous les ministères','All ministries')}</Button></aside></div></Container>}
  </Garde></Shell>;
}
Object.assign(window,{MinistereApp,FICHES});
