const {Button,Badge,Stat,Tag,Icon,Table,Breadcrumb,Accordion,Timeline,Stepper,Field,Input,Select,Alert,SearchBar}=window.SystMeDeDesignDeLTatDuCameroun_f51bf6;
const SITE={id:'sports',get nom(){return tr('Sports et Éducation physique','Sports & Physical Education');},get tagline(){return tr('Ministère des Sports et de l’Éducation physique — MINSEP','Ministry of Sports and Physical Education — MINSEP');},get nav(){return [{value:'accueil',label:tr('Accueil','Home')},{value:'licences',label:tr('Fédérations & licences','Federations & licences')},{value:'infrastructures',label:tr('Stades & événements','Stadiums & events')},{value:'scolaire',label:tr('Sport scolaire & santé','School sport & health')}];},get footer(){return tr('Site officiel du ministère des Sports et de l’Éducation physique. Fédérations, licences sportives, infrastructures, calendrier des Lions et Lionnes indomptables, sport scolaire et sport-santé.','Official site of the Ministry of Sports and Physical Education. Federations, sports licences, facilities, Indomitable Lions and Lionesses calendar, school sport and health.');},activeOf:p=>p};
const FEDES=[['FECAFOOT','Football','1959','fecafoot.cm','43 000'],['FECABASKET','Basket-ball','1966','—','6 200'],['FECAVOLLEY','Volley-ball','1965','—','3 800'],['FECAHAND','Handball','1965','—','4 100'],['FECATHLETISME','Athlétisme','1960','—','5 400'],['FECABOXE','Boxe','1962','—','1 900'],['FECAJUDO','Judo','1970','—','2 700'],['FECALUTTE','Lutte','1976','—','1 300'],['FECAWEIGHT','Haltérophilie','1985','—','600'],['FECATENNIS','Tennis','1962','—','900'],['FECACYCLISME','Cyclisme','1965','—','700'],['FECAVOLLEY-BEACH','Beach-volley','2004','—','—']];
const STADES=[{nom:'Stade Paul-Biya (Olembé)',ville:'Yaoundé',cap:'60 000',an:'2022',usage:'Lions, finales, CAN 2022'},{nom:'Stade omnisports Ahmadou-Ahidjo',ville:'Yaoundé',cap:'42 500',an:'1972 · 2020',usage:'Lions, fêtes nationales'},{nom:'Stade de Japoma',ville:'Douala',cap:'50 000',an:'2019',usage:'Lions, championnat'},{nom:'Stade de la Réunification',ville:'Douala',cap:'30 000',an:'1972 · 2021',usage:'Championnat'},{nom:'Stade Kouekong',ville:'Bafoussam',cap:'20 000',an:'2016',usage:'CAN 2022, championnat'},{nom:'Stade Roumdé-Adjia',ville:'Garoua',cap:'30 000',an:'1978 · 2021',usage:'CAN 2022, championnat'},{nom:'Stade municipal de Limbe',ville:'Limbe',cap:'20 000',an:'2016',usage:'CAN 2022'},{nom:'Palais polyvalent des sports (PAPOSY)',ville:'Yaoundé',cap:'5 200',an:'2009',usage:'Basket, volley, handball'}];
const AGENDA=[{d:'9 oct. 2026',t:'Lions indomptables — qualifications Coupe du monde',lieu:'Olembé, Yaoundé',type:'Football'},{d:'18 oct. 2026',t:'Lionnes indomptables — amical',lieu:'Japoma, Douala',type:'Football'},{d:'nov. 2026',t:'Championnats nationaux d’athlétisme',lieu:'Ahmadou-Ahidjo, Yaoundé',type:'Athlétisme'},{d:'fév. 2027',t:'Course de l’espoir — Mont Cameroun',lieu:'Buea',type:'Athlétisme'},{d:'mars 2027',t:'Jeux universitaires',lieu:'Bamenda',type:'Universitaire'},{d:'mai 2027',t:'FENASSCO — finales nationales',lieu:'Ebolowa',type:'Scolaire'}];
function Accueil({go}){
  return <>
    <Hero overline={tr('Ministère des Sports et de l’Éducation physique','Ministry of Sports and Physical Education')} title={tr('Le sport, pour toutes et tous, à tous les âges','Sport for everyone, at every age')} lead={tr('Licences sportives, fédérations agréées, stades et centres, calendrier des équipes nationales, sport scolaire et sport-santé : les services du MINSEP en un seul lieu.','Sports licences, accredited federations, stadiums and centres, national teams calendar, school sport and health: MINSEP services in one place.')} actions={<><Button variant="inverse" iconLeft="id-card" onClick={()=>go('licences')}>Obtenir une licence sportive</Button><Button variant="tertiary" style={{color:'#fff'}} iconRight="arrow-right" onClick={()=>go('infrastructures')}>Stades et calendrier</Button></>}
      aside={<><Overline color="var(--cm-jaune-500)">Prochain match des Lions</Overline><div style={{font:'var(--type-h5)',color:'#fff'}}>{AGENDA[0].t}</div><div style={{font:'var(--type-body-sm)',color:'var(--cm-gris-300)'}}>{AGENDA[0].d} · {AGENDA[0].lieu}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:4}}><Button size="sm" variant="inverse" iconLeft="ticket" href={LINKS.tresor}>Billetterie officielle</Button><Button size="sm" variant="tertiary" style={{color:'#fff'}} onClick={()=>go('infrastructures')}>Calendrier</Button></div><p style={{font:'var(--type-caption)',color:'var(--cm-gris-400)'}}>Billets vendus uniquement via le Trésor public : prix unique, quittance, aucun revendeur.</p></>}/>
    <section style={{background:'var(--surface-card)',borderBottom:'var(--hairline)',borderTop:'2px solid '+OR}}><Container style={{padding:'var(--space-8) var(--gutter)',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:'var(--space-6)'}}><Stat size="sm" value={FEDES.length} label="fédérations agréées" accent="vert"/><Stat size="sm" value={STADES.length} label="stades et palais" detail="≥ 5 000 places" accent="kola"/><Stat size="sm" value="5" label="CAN remportées" detail="1984 · 88 · 2000 · 02 · 17" accent="laterite"/><Stat size="sm" value="3" label="ors olympiques" detail="2000 · 2004 · 2008" accent="indigo"/><Stat size="sm" value="72 h" label="délai d’une licence" detail="en ligne" accent="neutre"/></Container></section>
    <section><Container style={{padding:'var(--space-16) var(--gutter)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'start'}}>
      <div><SectionTitle overline="Démarches" num={1}>Les plus demandées</SectionTitle><div style={{display:'grid',gap:2}}>{[['id-card','Obtenir ou renouveler une licence sportive','Fédération concernée · 2 000 – 10 000 FCFA · 72 h','licences'],['file-badge','Agréer une association ou un club sportif','MINSEP · gratuit · 30 jours','licences'],['stethoscope','Certificat médical d’aptitude au sport','Centre de médecine du sport · selon tarif · 24 h','scolaire'],['calendar','Réserver une infrastructure publique','Délégation régionale MINSEP · selon barème · 7 jours','infrastructures'],['trophy','Inscrire un établissement à la FENASSCO','MINSEP / MINESEC · gratuit · rentrée','scolaire']].map(([ic,t,m,p])=><Row key={t} icon={ic} title={t} meta={m} onClick={()=>go(p)} style={{background:'var(--surface-card)'}}/>)}</div></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Agenda</Overline><Timeline style={{marginTop:10}} items={AGENDA.slice(0,4).map(a=>({title:a.t,description:a.lieu,when:a.d,status:'todo'}))}/></div><div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Palmarès</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Lions indomptables, Lionnes, Françoise Mbango, Roger Milla : l’histoire sportive est racontée au <a href={LINKS.musee}>Musée numérique</a>.</p></div></aside>
    </Container></section>
    <section style={{background:'var(--surface-card)',borderTop:'var(--hairline)'}}><Container style={{padding:'var(--space-16) var(--gutter)'}}><SectionTitle overline="Infrastructures" num={2} action={<Button variant="tertiary" iconRight="arrow-right" onClick={()=>go('infrastructures')}>Tous les stades</Button>}>Les grands stades</SectionTitle><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))',gap:'var(--space-4)'}}>{STADES.slice(0,4).map(s=><article key={s.nom} style={{border:'var(--hairline)',background:'var(--surface-page)'}}><Photo ratio="16/9" placeholder={s.nom+' — photo à fournir'}/><div style={{padding:'var(--space-4)'}}><h3 style={{font:'var(--type-h6)'}}>{s.nom}</h3><div style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:4}}>{s.ville} · <span style={{fontFamily:'var(--font-mono)'}}>{s.cap}</span> places · {s.an}</div></div></article>)}</div></Container></section>
  </>;
}
function Licences({go}){
  const [step,setStep]=React.useState(1);const [fed,setFed]=React.useState('FECAFOOT');
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Fédérations & licences" num={1}>Une licence, une fédération, un dossier</SectionTitle>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:'var(--space-10)',alignItems:'start'}}>
      <div><div style={{background:'var(--surface-card)',border:'var(--hairline)'}}><div style={{padding:'var(--space-6)',borderBottom:'var(--hairline)'}}><Stepper steps={['Fédération','Identité & certificat','Paiement au Trésor','Licence']} current={step}/></div><div style={{padding:'var(--space-6)',display:'grid',gap:'var(--space-5)'}}>
        {step===1&&<><Field label="Discipline / fédération" required htmlFor="fed"><Select id="fed" value={fed} onChange={e=>setFed(e.target.value)} options={FEDES.map(f=>f[0]+' — '+f[1])}/></Field><Field label="Catégorie" required htmlFor="cat"><Select id="cat" options={['Joueur·euse amateur','Joueur·euse professionnel·le','Entraîneur·e','Arbitre','Dirigeant·e']}/></Field><Field label="Club" htmlFor="club" hint="Recherche parmi les clubs agréés de la fédération."><Input id="club" iconLeft="search" placeholder="ex. Canon de Yaoundé"/></Field></>}
        {step===2&&<><Alert status="success" size="sm" title="Identité vérifiée">Nom, date de naissance et photo repris d’Identité Cameroun (niveau 2). Rien à ressaisir.</Alert><Field label="Certificat médical d’aptitude" required hint="Délivré par un centre de médecine du sport agréé ; il est déjà dans votre coffre s’il a été émis en ligne." htmlFor="cert"><Select id="cert" options={['Certificat du 3 fév. 2026 — Dr Tchoumi (coffre)','Déposer un autre certificat']}/></Field><Field label="Assurance sportive" hint="Incluse dans la licence pour les amateurs." htmlFor="ass"><Select id="ass" options={['Assurance fédérale incluse','Assurance personnelle (joindre attestation)']}/></Field></>}
        {step===3&&<><p>Le montant est fixé par la fédération et validé par le MINSEP. Il est réglé au Trésor public ; la quittance déclenche l’émission.</p><div style={{display:'grid',gridTemplateColumns:'160px 1fr',gap:12,padding:'var(--space-4)',background:'var(--surface-page)',border:'var(--hairline)',font:'var(--type-body-sm)'}}><span style={{color:'var(--text-muted)'}}>Licence amateur {fed}</span><span style={{fontFamily:'var(--font-mono)',fontWeight:700}}>5 000 FCFA</span><span style={{color:'var(--text-muted)'}}>Frais mobile</span><span>0 FCFA</span><span style={{color:'var(--text-muted)'}}>Bénéficiaires</span><span>Fédération 80 % · MINSEP (fonds sport) 20 %</span></div><Button iconLeft="lock" href={LINKS.tresor}>Payer au Trésor public</Button></>}
        {step===4&&<><Alert status="success" title="Licence émise">Licence n° <span style={{fontFamily:'var(--font-mono)'}}>{fed}-2026-118344</span>, valable jusqu’au 31 août 2027. Elle est dans votre coffre et vérifiable par QR par tout club, arbitre ou organisateur.</Alert><div style={{padding:'var(--space-5)',background:'var(--cm-ebene)',color:'#fff',border:'1px solid '+OR,maxWidth:380,display:'grid',gap:10}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontFamily:'var(--font-display)',fontWeight:700,letterSpacing:'0.1em',textTransform:'uppercase',fontSize:12}}>Licence sportive · {fed}</span><Star size={14}/></div><div style={{font:'var(--type-h6)',color:'#fff'}}>NGO BASSONG Élise</div><div style={{font:'var(--type-caption)',color:'var(--cm-gris-300)'}}>Amateur · Canon de Yaoundé · saison 2026-2027</div><div style={{fontFamily:'var(--font-mono)',fontSize:12,color:'var(--cm-gris-300)'}}>{fed}-2026-118344</div></div></>}
      </div><div style={{padding:'var(--space-4) var(--space-6)',borderTop:'var(--hairline)',display:'flex',justifyContent:'space-between',gap:12}}><Button variant="tertiary" iconLeft="arrow-left" disabled={step===1} onClick={()=>setStep(step-1)}>Précédent</Button><Button iconRight="arrow-right" disabled={step===4} onClick={()=>setStep(step+1)}>{step===3?'J’ai payé — continuer':'Continuer'}</Button></div></div>
        <Ornement style={{margin:'var(--space-12) 0'}}/><SectionTitle overline="Fédérations agréées" num={2}>{FEDES.length} fédérations sous tutelle du MINSEP</SectionTitle><Table caption="Fédérations sportives nationales agréées" columns={[{key:'0',label:'Sigle',mono:true},{key:'1',label:'Discipline',strong:true},{key:'2',label:'Création'},{key:'4',label:'Licenciés',align:'right',mono:true},{key:'3',label:'Site'}]} rows={FEDES}/></div>
      <aside style={{display:'grid',gap:'var(--space-4)'}}><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--surface-card)'}}><Overline color="var(--text-muted)">Pièces</Overline><ul style={{margin:'8px 0 0',paddingLeft:18,font:'var(--type-body-sm)',lineHeight:'var(--leading-relaxed)'}}><li>Identité Cameroun (niveau 2)</li><li>Certificat médical de moins de 3 mois</li><li>Autorisation parentale pour les mineurs (compte famille)</li></ul></div><div style={{border:'var(--hairline)',padding:'var(--space-5)',background:'var(--cm-jaune-50)'}}><Overline color="var(--cm-jaune-800)">Prix unique</Overline><p style={{font:'var(--type-body-sm)',marginTop:8}}>Aucun frais n’est dû au club ou à un intermédiaire pour la licence. Tout paiement passe par le Trésor. <a href={LINKS.tresor}>Signaler un abus</a></p></div><div style={{border:'var(--hairline)',padding:'var(--space-5)'}}><Overline color="var(--text-muted)">Clubs et associations</Overline><p style={{font:'var(--type-body-sm)',color:'var(--text-muted)',marginTop:8}}>Agrément d’un club : statuts, récépissé de la préfecture, affiliation fédérale. Gratuit, 30 jours.</p><Button size="sm" variant="secondary" style={{marginTop:10}}>Demander un agrément</Button></div></aside>
    </div>
  </Container>;
}
function Infrastructures(){
  const [type,setType]=React.useState('Tous');const types=['Tous',...new Set(AGENDA.map(a=>a.type))];
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Stades & événements" num={1}>Les grands équipements et le calendrier</SectionTitle>
    <Table caption="Stades et palais des sports (capacité ≥ 5 000)" columns={[{key:'nom',label:'Équipement',strong:true},{key:'ville',label:'Ville'},{key:'cap',label:'Capacité',align:'right',mono:true},{key:'an',label:'Ouverture · rénovation'},{key:'usage',label:'Usage'},{key:'x',label:'',align:'right',render:()=><Button size="sm" variant="tertiary" iconRight="arrow-right">Réserver</Button>}]} rows={STADES}/>
    <SectionTitle top overline="Calendrier" num={2}>Événements à venir</SectionTitle>
    <div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:'var(--space-4)'}}>{types.map(t=><Tag key={t} size="sm" selected={type===t} onClick={()=>setType(t)}>{t}</Tag>)}</div>
    <div style={{display:'grid',gap:2}}>{AGENDA.filter(a=>type==='Tous'||a.type===type).map(a=><Row key={a.t} icon="calendar" title={a.t} meta={a.lieu+' · '+a.type} right={a.d} href={LINKS.tresor} style={{background:'var(--surface-card)'}}/>)}</div>
    <p style={{font:'var(--type-caption)',color:'var(--text-muted)',marginTop:16}}>Billetterie : prix affichés au barème du Trésor public, quittance nominative, contrôle par QR à l’entrée.</p>
  </Container>;
}
function Scolaire(){
  return <Container style={{padding:'var(--space-10) var(--gutter) var(--space-16)'}}>
    <SectionTitle level={1} overline="Sport scolaire & sport-santé" num={1}>De l’école au stade, et pour la vie</SectionTitle>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:'var(--space-4)'}}>{[['trophy','FENASSCO','Fédération nationale du sport scolaire (ligues A et B) : compétitions départementales, régionales et finales nationales chaque année scolaire. Inscription des établissements par le chef d’établissement.'],['graduation-cap','INJS','Institut national de la jeunesse et des sports (Yaoundé) : formation des professeurs d’EPS, entraîneurs et cadres. Concours annuel.'],['heart-pulse','Sport-santé','Programme « Bouger pour sa santé » avec le MINSANTE : marches populaires, certificats d’aptitude, centres de médecine du sport à Yaoundé, Douala, Garoua.'],['accessibility','Handisport','Fédération camerounaise des sports pour personnes handicapées ; accès et équipements adaptés dans les stades rénovés (CAN 2022).']].map(([ic,t,d])=><article key={t} style={{background:'var(--surface-card)',border:'var(--hairline)',padding:'var(--space-5)',display:'grid',gridTemplateColumns:'40px 1fr',gap:14,alignItems:'start'}}><span style={{width:40,height:40,background:'var(--surface-brand-soft)',display:'grid',placeItems:'center'}}><Icon name={ic} size={20} color="var(--cm-vert-800)"/></span><span><span style={{font:'var(--type-h6)',display:'block'}}>{t}</span><span style={{font:'var(--type-body-sm)',color:'var(--text-muted)',display:'block',marginTop:6}}>{d}</span></span></article>)}</div>
    <SectionTitle top overline="Démarches" num={2}>Pour les établissements et les familles</SectionTitle>
    <div style={{display:'grid',gap:2}}>{[['Inscrire un établissement à la FENASSCO','MINSEP / MINESEC · gratuit · avant le 31 octobre'],['Certificat médical d’aptitude au sport (élève)','Centre de santé · selon tarif · 24 h · versé au compte famille'],['Candidater au concours de l’INJS','MINSEP · frais de dossier au Trésor · session annuelle'],['Demander une subvention d’équipement (école, club)','Délégation régionale · dossier · commission annuelle']].map(([t,m])=><Row key={t} icon="chevron-right" title={t} meta={m} href={LINKS.hub} style={{background:'var(--surface-card)'}}/>)}</div>
  </Container>;
}
Object.assign(window,{SITE,Accueil,Licences,Infrastructures,Scolaire});
