/* Couche commune v2 : langue, mentions légales, réseau des ministères, pied de page standard. Chargé après recherche.jsx. */
const LANG_KEY='cm-lang';
const getLang=()=>{try{return localStorage.getItem(LANG_KEY)||'FR';}catch(e){return 'FR';}};
const setLang=l=>{try{localStorage.setItem(LANG_KEY,l);}catch(e){}document.documentElement.lang=l==='EN'?'en':'fr';window.dispatchEvent(new CustomEvent('cm-lang',{detail:l}));};
const useLang=()=>{const [l,setL]=React.useState(getLang);React.useEffect(()=>{const f=e=>setL(e.detail);window.addEventListener('cm-lang',f);document.documentElement.lang=l==='EN'?'en':'fr';return()=>window.removeEventListener('cm-lang',f);},[]);return [l,v=>{setLang(v);setL(v);}];};
const tr=(fr,en)=>getLang()==='EN'?(en??fr):fr;
/* Ministères : identifiant, nom FR/EN, catégorie, image contextuelle. Sites dédiés → href propre ; sinon site générique ../ministeres/index.html#id */
const MINISTERES=[
 ['prc','Présidence de la République','Presidency of the Republic','souv','palais','../presidence/index.html'],
 ['spm','Services du Premier ministre','Prime Minister’s Office','souv','palais'],
 ['an','Assemblée nationale & Sénat','National Assembly & Senate','souv','palais'],
 ['minrex','Relations extérieures','External Relations','souv','douala'],
 ['minat','Administration territoriale','Territorial Administration','souv','paysage'],
 ['mindef','Défense','Defence','souv','paysage'],
 ['dgsn','Sûreté nationale (DGSN)','National Security (DGSN)','souv','douala'],
 ['minjustice','Justice','Justice','souv','palais'],
 ['mindevel','Décentralisation et Développement local','Decentralisation & Local Development','souv','douala'],
 ['minfi','Finances','Finance','eco','douala','../tresor/index.html'],
 ['minepat','Économie, Planification et Aménagement du territoire','Economy, Planning & Regional Development','eco','kribi'],
 ['minmap','Marchés publics','Public Contracts','eco','douala'],
 ['mincommerce','Commerce','Trade','eco','douala'],
 ['minpmeesa','PME, Économie sociale et Artisanat','SMEs, Social Economy & Handicrafts','eco','art'],
 ['minmidt','Mines, Industrie et Développement technologique','Mines, Industry & Technological Development','eco','kribi'],
 ['minsante','Santé publique','Public Health','social','nature'],
 ['mintss','Travail et Sécurité sociale','Labour & Social Security','social','douala'],
 ['minas','Affaires sociales','Social Affairs','social','nature'],
 ['minproff','Promotion de la Femme et de la Famille','Women’s Empowerment & the Family','social','art'],
 ['minfopra','Fonction publique et Réforme administrative','Public Service & Administrative Reform','social','palais'],
 ['minedub','Éducation de base','Basic Education','edu','nature'],
 ['minesec','Enseignements secondaires','Secondary Education','edu','nature'],
 ['minesup','Enseignement supérieur','Higher Education','edu','palais'],
 ['minefop','Emploi et Formation professionnelle','Employment & Vocational Training','edu','douala'],
 ['minresi','Recherche scientifique et Innovation','Scientific Research & Innovation','edu','nature'],
 ['mint','Transports','Transport','terr','douala'],
 ['mintp','Travaux publics','Public Works','terr','paysage'],
 ['minhdu','Habitat et Développement urbain','Housing & Urban Development','terr','douala'],
 ['mindcaf','Domaines, Cadastre et Affaires foncières','State Property, Surveys & Land Tenure','terr','paysage'],
 ['minee','Eau et Énergie','Water & Energy','terr','kribi'],
 ['minpostel','Postes et Télécommunications','Posts & Telecommunications','terr','douala'],
 ['minader','Agriculture et Développement rural','Agriculture & Rural Development','prod','nature'],
 ['minepia','Élevage, Pêches et Industries animales','Livestock, Fisheries & Animal Industries','prod','paysage'],
 ['minfof','Forêts et Faune','Forestry & Wildlife','prod','nature'],
 ['minepded','Environnement, Protection de la nature et Développement durable','Environment, Nature Protection & Sustainable Development','prod','nature'],
 ['minac','Arts et Culture','Arts & Culture','cult','foumban','../musee/index.html'],
 ['minsep','Sports et Éducation physique','Sports & Physical Education','cult','art','../sports/index.html'],
 ['mintoul','Tourisme et Loisirs','Tourism & Leisure','cult','kribi','../ministeres/index.html#mintoul'],
 ['minjec','Jeunesse et Éducation civique','Youth & Civic Education','cult','art'],
 ['mincom','Communication','Communication','cult','douala']
].map(([id,fr,en,cat,img,href])=>({id,fr,en,cat,img,href:href||('../ministeres/index.html#'+id)}));
const CAT_MIN={souv:['Institutions de souveraineté','Sovereign institutions'],eco:['Économie & finances','Economy & finance'],social:['Social & santé','Social affairs & health'],edu:['Éducation & savoirs','Education & knowledge'],terr:['Territoire & infrastructures','Territory & infrastructure'],prod:['Production & environnement','Production & environment'],cult:['Culture, jeunesse & communication','Culture, youth & communication']};
const IMG_CTX={kribi:'https://images.unsplash.com/photo-1637244018403-785e7fa8707a?w=1600&q=75&fit=crop',paysage:'https://images.unsplash.com/photo-1615463668140-d294c94ec8ef?w=1600&q=75&fit=crop',nature:'https://images.unsplash.com/photo-1696541665406-a2517f84f934?w=1600&q=75&fit=crop',foumban:'https://images.unsplash.com/photo-1659947234294-b217aaeb25f8?w=1600&q=75&fit=crop',palais:'https://images.unsplash.com/photo-1659947234286-213fd15f0bcc?w=1600&q=75&fit=crop',art:'https://images.unsplash.com/photo-1659947234279-92bc8f2cd2fe?w=1600&q=75&fit=crop',douala:'https://images.unsplash.com/photo-1636385918427-7aa474ffa8ae?w=1600&q=75&fit=crop'};
const CREDIT_CTX={kribi:'Edouard Tamba / Unsplash',paysage:'Edouard Tamba / Unsplash',nature:'Christian Aime Nanga / Unsplash',foumban:'Ariel Nathan Ada Mbita / Unsplash',palais:'Ariel Nathan Ada Mbita / Unsplash',art:'Ariel Nathan Ada Mbita / Unsplash',douala:'Youssouf Nchetkou Ndam / Unsplash'};
// Ajout des ministères à l'index de recherche
MINISTERES.forEach(m=>{if(window.RECHERCHE&&!RECHERCHE.some(e=>e.href===m.href&&e.group==='Institutions'))RECHERCHE.push({group:'Institutions',label:m.fr+' / '+m.en,hint:CAT_MIN[m.cat][0],href:m.href,icon:'landmark',keys:m.id+' ministere ministry '+m.en.toLowerCase()});});
/* Mentions légales et textes de pied de page — FR / EN, ordonnés. */
const LEGAL=[
 {id:'accessibilite',fr:'Accessibilité',en:'Accessibility',icon:'accessibility',txt:{fr:['Les sites du réseau Cameroun numérique visent la conformité au RGAA 4.1 et aux WCAG 2.2 niveau AA. Cette déclaration est établie site par site et mise à jour à chaque version majeure.','État de conformité : ce site est partiellement conforme (audit interne, septembre 2026). Les écarts connus concernent certaines cartes interactives et les documents PDF anciens.','Réglages disponibles partout : taille du texte, contraste renforcé, espacement, police à lecture facilitée, version facile à lire (FALC), liens renforcés, animations réduites. Ils sont conservés dans votre Identité Cameroun.','Vous rencontrez un obstacle : écrivez depuis votre compte (« Signaler un obstacle »), appelez le 8100 (gratuit) ou rendez-vous dans un guichet Cameroun numérique. Réponse sous 15 jours. Sans réponse, vous pouvez saisir le médiateur du réseau.'],en:['Sites of the Cameroun numérique network aim for RGAA 4.1 and WCAG 2.2 level AA. This statement is issued per site and updated at every major release.','Compliance status: this site is partially compliant (internal audit, September 2026). Known gaps concern some interactive maps and legacy PDF documents.','Settings available everywhere: text size, high contrast, spacing, legible typeface, easy-to-read version, strong links, reduced motion. They are stored in your Identité Cameroun.','If you meet a barrier: write from your account (“Report a barrier”), call 8100 (free) or visit a Cameroun numérique desk. Reply within 15 days; otherwise you may refer the matter to the network ombudsman.']}},
 {id:'mentions',fr:'Mentions légales',en:'Legal notice',icon:'scale',txt:{fr:['Éditeur : République du Cameroun. Chaque site est édité par l’institution indiquée dans son en-tête, sous la coordination du programme Cameroun numérique (ministère des Postes et Télécommunications, ANTIC).','Directeur de la publication : le responsable de l’institution éditrice. Hébergement : centre de données de l’État (CAMTEL), Yaoundé.','Les textes officiels font foi dans leur version publiée au Journal officiel. Les informations pratiques (coûts, délais) reprennent les textes en vigueur et sont datées ; en cas de divergence, le texte l’emporte.','Contact : 8100 (gratuit, 7 j/7, FR/EN) — courrier depuis votre compte — guichets Cameroun numérique dans chaque chef-lieu.'],en:['Publisher: Republic of Cameroon. Each site is published by the institution named in its header, coordinated by the Cameroun numérique programme (Ministry of Posts and Telecommunications, ANTIC).','Publication director: the head of the publishing institution. Hosting: State data centre (CAMTEL), Yaoundé.','Official texts prevail in their Official Gazette version. Practical information (fees, lead times) reflects the texts in force and is dated; in case of discrepancy, the text prevails.','Contact: 8100 (free, 7/7, FR/EN) — mail from your account — Cameroun numérique desks in every regional capital.']}},
 {id:'donnees',fr:'Données personnelles',en:'Personal data',icon:'shield-check',txt:{fr:['Responsable de traitement : l’institution éditrice de chaque site ; Identité Cameroun est opérée par l’ANTIC sous le contrôle du MINPOSTEL.','Finalités : instruire vos démarches, vous notifier, sécuriser votre compte, produire des statistiques anonymes. Base légale : mission de service public et consentement pour les notifications.','Minimisation : chaque service ne reçoit que les données nécessaires à sa mission (ex. le Trésor transmet « payé », pas votre relevé). Aucune donnée personnelle n’est inscrite dans le registre d’intégrité.','Vos droits : accès, rectification, opposition, portabilité, journal de tous les accès à vos données, depuis votre compte. Durées : dossiers conservés selon les textes ; journaux d’accès 5 ans. Cadre : loi n° 2010/012 sur la cybersécurité et la cybercriminalité ; textes sur la protection des données à venir.'],en:['Controller: the publishing institution of each site; Identité Cameroun is operated by ANTIC under MINPOSTEL supervision.','Purposes: process your requests, notify you, secure your account, produce anonymous statistics. Legal basis: public-service mission and consent for notifications.','Minimisation: each service receives only the data needed for its mission (e.g. the Treasury forwards “paid”, not your statement). No personal data is written to the integrity ledger.','Your rights: access, rectification, objection, portability and a log of every access to your data, from your account. Retention: files as provided by law; access logs 5 years. Framework: Law No. 2010/012 on cybersecurity and cybercrime; forthcoming data-protection texts.']}},
 {id:'cookies',fr:'Cookies et mesure d’audience',en:'Cookies & analytics',icon:'cookie',txt:{fr:['Cookies strictement nécessaires : session Identité Cameroun, préférences d’accessibilité et de langue. Ils ne requièrent pas de consentement.','Mesure d’audience : statistiques anonymisées hébergées par l’État (aucun tiers publicitaire). Vous pouvez la refuser depuis vos préférences.','Aucun traceur tiers, aucune publicité, aucun partage à des fins commerciales.'],en:['Strictly necessary cookies: Identité Cameroun session, accessibility and language preferences. No consent required.','Analytics: anonymised statistics hosted by the State (no advertising third party). You can opt out in your preferences.','No third-party trackers, no advertising, no commercial sharing.']}},
 {id:'licence',fr:'Licence CC BY-NC-SA 4.0',en:'CC BY-NC-SA 4.0 licence',icon:'unlock',txt:{fr:['Ce prototype de langage de conception est publié par Johan Kenneth Nken sous licence Creative Commons CC BY-NC-SA 4.0 : réutilisation autorisée avec crédit, sans usage commercial, et partage des versions modifiées sous la même licence.','Crédit à recopier : « Cameroun numérique — Johan Kenneth Nken (github.com/jokenkpro/cameroun-numerique), CC BY-NC-SA 4.0 ».','Usage commercial, institutionnel ou rémunéré : accord écrit préalable — jokenkpro@gmail.com.','Non couverts : symboles de l’État, photographies créditées (Unsplash, Wikimedia Commons), polices (SIL OFL), bibliothèques tierces (MIT, BSD).'],en:['This design-language prototype is published by Johan Kenneth Nken under Creative Commons CC BY-NC-SA 4.0: reuse allowed with credit, no commercial use, and modified versions shared under the same licence.','Credit to reproduce: “Cameroun numérique — Johan Kenneth Nken (github.com/jokenkpro/cameroun-numerique), CC BY-NC-SA 4.0”.','Commercial, institutional or paid use: prior written agreement — jokenkpro@gmail.com.','Not covered: State symbols, credited photographs (Unsplash, Wikimedia Commons), fonts (SIL OFL), third-party libraries (MIT, BSD).']}},
 {id:'plan',fr:'Plan du réseau',en:'Sitemap',icon:'map',txt:{fr:['Hub Cameroun numérique : démarches par besoin, ministères & services, relais locaux, Identité Cameroun, communauté.','Services transverses : Trésor public — Paiements de l’État ; Identité Cameroun ; relais locaux.','Sites de ministère : gabarit commun (accueil, démarches, le ministère). Sites dédiés : Présidence, Sports, Musée numérique, Impôts, Tourisme.'],en:['Cameroun numérique hub: services by need, ministries & services, local desks, Identité Cameroun, community.','Cross-cutting services: Public Treasury — State payments; Identité Cameroun; local desks.','Ministry sites: common template (home, services, the ministry). Dedicated sites: Presidency, Sports, Digital Museum, Taxes, Tourism.']}},
 {id:'journal',fr:'Journal des changements',en:'Changelog',icon:'git-commit-horizontal',txt:{fr:['v2.1 — 21 sept. 2026 : pied de page refondu (devise tricolore, mentions ordonnées), recherche unifiée avec suggestions, panneau « Ministères & services », sites bilingues FR/EN, 40 ministères au gabarit commun.','v2.0 — 20 sept. 2026 : hub, Identité Cameroun (première connexion au relais, clés d’accès), Trésor public, Musée numérique, Présidence, Sports, relais locaux.','v1 — sept. 2026 : fondations, composants, portail des services, Impôts, Tourisme, plateforme communautaire.','Chaque évolution est proposée au vote de la communauté avant généralisation.'],en:['v2.1 — 21 Sept 2026: redesigned footer (tricolour motto, ordered legal links), unified search with suggestions, “Ministries & services” panel, bilingual FR/EN sites, 40 ministries on the common template.','v2.0 — 20 Sept 2026: hub, Identité Cameroun (first enrolment at a local desk, passkeys), Public Treasury, Digital Museum, Presidency, Sports, local desks.','v1 — Sept 2026: foundations, components, services portal, Taxes, Tourism, community platform.','Every change is put to the community vote before roll-out.']}}
];
const VERSION_LANGAGE='Langage v2.1 · 21 sept. 2026';
/* Pied de page standard : colonnes non redondantes avec l'en-tête (aide, réseau, participer), mentions ordonnées. */
function footerProps({site,lang,extraLinks=[],desc}){
  const EN=lang==='EN';const L=id=>'../hub/index.html#legal/'+id;
  return {lang,serviceName:site,description:desc,version:VERSION_LANGAGE,
    contact:[{icon:'phone',label:EN?'8100 — free, 7/7, FR/EN':'8100 — gratuit, 7 j/7, FR/EN'},{icon:'map-pin',label:EN?'Cameroun numérique desks in every regional capital':'Guichets Cameroun numérique dans chaque chef-lieu',href:'../hub/index.html#relais'},{icon:'flag',label:EN?'Report abuse or corruption':'Signaler un abus ou une corruption',href:'../tresor/index.html#signaler'}],
    columns:[{title:EN?'Help':'Aide',links:[{label:EN?'Find a service by need':'Trouver une démarche par besoin',href:'../hub/index.html#besoins'},{label:EN?'Local desks (town halls, chiefdoms…)':'Relais locaux (mairies, chefferies…)',href:'../hub/index.html#relais'},{label:EN?'Identité Cameroun — first login':'Identité Cameroun — première connexion',href:'../hub/index.html#premiere'},{label:EN?'Check a receipt':'Vérifier une quittance',href:'../tresor/index.html#accueil'},...extraLinks]},
      {title:EN?'The network':'Le réseau',links:[{label:'Cameroun numérique',href:'../hub/index.html'},{label:EN?'All ministries':'Tous les ministères',href:'../hub/index.html#annuaire'},{label:EN?'Public Treasury — payments':'Trésor public — paiements',href:'../tresor/index.html'},{label:EN?'Digital Museum of Cameroon':'Musée numérique du Cameroun',href:'../musee/index.html'}]},
      {title:EN?'Take part':'Participer',links:[{label:EN?'Vote on the design language':'Voter sur le langage',href:'../hub/index.html#communaute'},{label:EN?'Suggest an improvement':'Proposer une amélioration',href:'../hub/index.html#communaute'},{label:EN?'Open data':'Données ouvertes',href:'../tresor/index.html#redistribution'},{label:EN?'Changelog':'Journal des changements',href:L('journal')}]}],
    legal:LEGAL.filter(l=>l.id!=='journal').map(l=>({label:EN?l.en:l.fr,href:L(l.id)})),
    onTop:()=>window.scrollTo({top:0})};
}
Object.assign(window,{getLang,setLang,useLang,tr,MINISTERES,CAT_MIN,IMG_CTX,CREDIT_CTX,LEGAL,VERSION_LANGAGE,footerProps});
