/* Gabarit commun des sites de ministère (v2). Chaque site fournit SITE={id,nom,tagline,nav,footer} avant de charger ce fichier. */
const __NS=window.SystMeDeDesignDeLTatDuCameroun_f51bf6||{};const {Header,Footer,Icon}=__NS;
const GovBar=__NS.GovBar||(()=>null);const AccessPanel=__NS.AccessPanel||(()=>null);const applyA11y=__NS.applyA11y||(()=>{});const readA11y=__NS.readA11y||(()=>({falc:false}));
const OR='#B98A00';
const SITES=window.SITES_RESEAU||[];
const LINKS={hub:'../hub/index.html',presidence:'../presidence/index.html',sports:'../sports/index.html',tresor:'../tresor/index.html',musee:'../musee/index.html',impots:'../ministeres/index.html#minfi',tourisme:'../ministeres/index.html#mintoul'};
const Container=({children,style})=><div style={{maxWidth:'var(--container-lg)',margin:'0 auto',padding:'0 var(--gutter)',boxSizing:'border-box',width:'100%',...style}}>{children}</div>;
const ROMAN=['I','II','III','IV','V','VI','VII','VIII'];
const Overline=({children,color='var(--accent-laterite)',num,style})=><div style={{font:'var(--type-overline)',letterSpacing:'var(--tracking-caps)',textTransform:'uppercase',color,display:'flex',alignItems:'center',gap:10,flexWrap:'wrap',...style}}>{num!=null&&<span style={{fontFamily:'var(--font-display)',fontWeight:700,color:OR}}>{ROMAN[num-1]||num}</span>}{num!=null&&<span aria-hidden="true" style={{width:20,height:1,background:OR}}/>}<span>{children}</span></div>;
const SectionTitle=({children,overline,action,id,level=2,num,top})=><div id={id} style={{marginBottom:'var(--space-6)',marginTop:top?'var(--space-20)':0,display:'flex',alignItems:'flex-end',justifyContent:'space-between',gap:16,flexWrap:'wrap',scrollMarginTop:100}}><div>{overline&&<Overline num={num} style={{marginBottom:6}}>{overline}</Overline>}{level===1?<h1 style={{font:'var(--type-h2)'}}>{children}</h1>:<h2 style={{font:'var(--type-h3)'}}>{children}</h2>}<div aria-hidden="true" style={{height:'var(--rule-title)',width:'var(--rule-title-w)',background:'var(--brand-band)',marginTop:10}}/></div>{action}</div>;
const Star=({size=12,color=OR})=><svg viewBox="0 0 100 100" width={size} height={size} aria-hidden="true"><polygon fill={color} points="50,5 61.8,38.2 96.6,38.2 68.4,58.8 79.4,92 50,71.4 20.6,92 31.6,58.8 3.4,38.2 38.2,38.2"/></svg>;
const Ornement=({style})=><div aria-hidden="true" style={{display:'grid',gridTemplateColumns:'1fr auto 1fr',alignItems:'center',gap:16,...style}}><span style={{height:1,background:'linear-gradient(90deg,transparent,'+OR+')'}}/><Star/><span style={{height:1,background:'linear-gradient(90deg,'+OR+',transparent)'}}/></div>;
const Row=({title,meta,right,onClick,href,icon,style})=>{const T=href?'a':'button';return <T {...(href?{href}:{type:'button',onClick})} style={{all:'unset',boxSizing:'border-box',cursor:'pointer',display:'grid',gridTemplateColumns:(icon?'20px ':'')+'1fr auto 16px',gap:14,alignItems:'center',width:'100%',minHeight:44,padding:'10px 12px',borderBottom:'var(--hairline)',textAlign:'left',...style}}>{icon&&<Icon name={icon} size={18} color="var(--cm-vert-800)"/>}<span style={{minWidth:0}}><span style={{font:'var(--type-label)',fontWeight:600,color:'var(--text-heading)',display:'block'}}>{title}</span>{meta&&<span style={{font:'var(--type-caption)',fontWeight:500,color:'var(--text-muted)'}}>{meta}</span>}</span><span style={{font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'right'}}>{right}</span><Icon name="chevron-right" size={16} color="var(--text-subtle)"/></T>;};
const Photo=({src,credit,ratio='3/2',placeholder='Photographie à fournir (service de communication)',alt,style,children})=><figure role="img" aria-label={alt||(src?(credit?'Photographie — '+credit:'Photographie'):placeholder)} style={{margin:0,position:'relative',aspectRatio:ratio,background:src?'var(--cm-gris-200) url('+src+') center/cover':'var(--motif-laterite)',overflow:'hidden',border:src?0:'1px solid var(--border-default)',...style}}>{src&&<div aria-hidden="true" style={{position:'absolute',inset:0,background:'var(--photo-protect)'}}/>}{!src&&<div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',font:'var(--type-caption)',color:'var(--text-muted)',textAlign:'center',padding:16}}>{placeholder}</div>}{credit&&<figcaption style={{position:'absolute',right:8,top:8,color:'#fff',font:'var(--type-caption)',fontWeight:500,background:'rgba(21,17,14,.6)',padding:'2px 6px'}}>© {credit}</figcaption>}{children}</figure>;
/* Hero de ministère : ébène + motif, overline, titre, chapeau, 3 démarches phares */
const Hero=({overline,title,lead,actions,aside})=><section style={{background:'var(--cm-ebene)',color:'#fff',position:'relative',isolation:'isolate'}}><div aria-hidden="true" style={{position:'absolute',inset:0,background:'var(--motif-ndop)',opacity:.3,overflow:'hidden',zIndex:-1}}/><Container style={{position:'relative',padding:'var(--space-16) var(--gutter) var(--space-12)',display:'grid',gridTemplateColumns:'minmax(0,3fr) minmax(280px,2fr)',gap:'var(--space-12)',alignItems:'end'}}><div><Overline color="var(--cm-jaune-500)">{overline}</Overline><div aria-hidden="true" style={{width:48,height:1,background:OR,margin:'14px 0 0'}}/><h1 style={{font:'var(--type-display)',color:'#fff',fontSize:'clamp(2.1rem,4.6vw,3.5rem)',marginTop:14,letterSpacing:'var(--tracking-tight)'}}>{title}</h1><p style={{font:'var(--type-lead)',color:'var(--cm-gris-200)',maxWidth:'52ch',marginTop:14}}>{lead}</p>{actions&&<div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:24}}>{actions}</div>}</div>{aside&&<div style={{background:'rgba(255,255,255,.06)',border:'1px solid rgba(255,255,255,.2)',borderTop:'2px solid '+OR,padding:'var(--space-6)',display:'grid',gap:12}}>{aside}</div>}</Container></section>;
function Shell({page,go,children,lang:langP,setLang:setLangP}){
  const [a11y,setA11y]=React.useState(false);const [langS,setLangS]=useLang();const lang=langP||langS;const setLang=setLangP||setLangS;const [falc,setFalc]=React.useState(false);
  React.useEffect(()=>{const p=readA11y();applyA11y(p);setFalc(!!p.falc);},[]);
  const user=(()=>{try{const u=JSON.parse(localStorage.getItem('cm-hub-user')||'null');return u?{name:u.nom,initials:u.initials}:null;}catch(e){return null;}})();
  return <div style={{minHeight:'100vh',display:'flex',flexDirection:'column',background:'var(--surface-page)'}}>
    <a href="#main" style={{position:'absolute',left:-9999,top:8,zIndex:2000,background:'var(--a11y-skip-bg)',padding:'8px 12px',font:'var(--type-label)',color:'var(--a11y-skip-text)'}} onFocus={e=>{e.target.style.left='8px';}} onBlur={e=>{e.target.style.left='-9999px';}}>Aller au contenu</a>
    <GovBar ministry={SITE.id} hubHref="../hub/index.html" sites={SITES} onSiteChange={id=>{const s=SITES.find(x=>x.id===id);if(s&&s.href)location.href=s.href;}} suggest={window.rechercher} onSearch={q=>location.href='../hub/index.html#recherche/'+encodeURIComponent(q)} onAccessibility={()=>setA11y(true)} lang={lang} onLangChange={setLang} user={user} onLogin={()=>location.href=LINKS.hub}/>
    <Header compact showLogin={false} serviceName={SITE.nom} tagline={SITE.tagline} nav={SITE.nav} active={SITE.activeOf?SITE.activeOf(page):page} onNavigate={v=>go(v)}/>
    {falc&&<div role="status" key="falc" style={{background:'var(--cm-jaune-100)',borderBottom:'1px solid var(--cm-jaune-300)',font:'var(--type-body-sm)',padding:'8px var(--gutter)',textAlign:'center'}}>Version <b>facile à lire</b> activée.</div>}
    <main id="main" style={{flex:1}}>{children}</main>
    <Footer {...footerProps({site:SITE.nom,lang,desc:SITE.footer})}/>
    <AccessPanel open={a11y} onClose={()=>setA11y(false)} onChange={p=>setFalc(!!p.falc)}/>
  </div>;
}
class Garde extends React.Component{constructor(p){super(p);this.state={err:null};}static getDerivedStateFromError(e){return{err:e};}componentDidUpdate(p){if(p.k!==this.props.k&&this.state.err)this.setState({err:null});}render(){if(this.state.err)return <Container style={{padding:'var(--space-12) var(--gutter)'}}><h1 style={{font:'var(--type-h3)'}}>Cette page a rencontré un problème</h1><p style={{color:'var(--text-muted)',marginTop:8}}>Le reste du site fonctionne. <a href="#" onClick={e=>{e.preventDefault();this.props.onHome();}}>Retour à l’accueil</a></p></Container>;return this.props.children;}}
Object.assign(window,{Shell,Garde,Container,Overline,SectionTitle,Star,Ornement,Row,Photo,Hero,SITES,LINKS,OR});
